### ISSUE TITLE
Depth weighting

### ISSUE THREAD

**Issue by xiaolongw1223** [simpeg/simpeg#1000]
Hi, guys, 
Seems depth weighting is unavailable in SimPEG. Is "utils" a good place to create a function to generate depth weighting?
Then we can do something like: 

reg.cell_weights = utils.depth_weighting(v, z0), where v and z0 are adjustable.

If "utils" is a good place for depth weighting, I can do that.

**Comment by domfournier** [comment]
hey @xiaolongw1223 : There is a function under `potential_fields.base.get_dist_wgt` but that's distance weight and super specific to mag. If you are interested in moving this around to `utils` that sounds great to me. We could give it an argument for the power of decay I guess?

**Comment by dccowan** [comment]
Why not use sensitivity weighting in directives?
# Add sensitivity weights
sensitivity_weights = directives.UpdateSensitivityWeights(everyIter=False)

Since it's constant, set update every iteration to False

**Comment by RichardScottOZ** [comment]
Sounds like a good thing to have

**Comment by xiaolongw1223** [comment]
> hey @xiaolongw1223 : There is a function under `potential_fields.base.get_dist_wgt` but that's distance weight and super specific to mag. If you are interested in moving this around to `utils` that sounds great to me. We could give it an argument for the power of decay I guess?

Yup, we could do that.

**Comment by xiaolongw1223** [comment]
> Why not use sensitivity weighting in directives?
> 
> # Add sensitivity weights
> sensitivity_weights = directives.UpdateSensitivityWeights(everyIter=False)
> 
> Since it's constant, set update every iteration to False

Sensitivity works well. 
Here I just wanna provide another option in case some people need it. Also, we could change the power of decay.

**Comment by thast** [comment]
PR #1000! Well played,  @xiaolongw1223 ! 🥳  Is there a price for that? 🥇

**Comment by xiaolongw1223** [comment]
> Sounds like a good thing to have

Will do that!

**Comment by lianghcug** [comment]
Hello @xiaolongw1223 , that sounds great! Have your finished this updated?  I just want to perform gravity inversion with depth weighting. I'm looking forward to your updated.

**Comment by xiaolongw1223** [comment]
> Hello @xiaolongw1223 , that sounds great! Have your finished this updated? I just want to perform gravity inversion with depth weighting. I'm looking forward to your updated.

Hi @lianghcug sorry for late reply, internet is unavailable to me in the past week. I've already finished updates, but the function still needs a review by SimPEG before merging into main branch. Please finds more details [here](https://github.com/simpeg/simpeg/pull/1004)

**Comment by jcapriot** [comment]
The utility was included in #1004, Together with the recent regularization updates, this should be good!
