### ISSUE TITLE
cell_volumes in Regularization 

### ISSUE THREAD

**Issue by domfournier** [simpeg/simpeg#1010]
Currently the behaviour between Tikhonov and Simple is different with respect to the cell_weights.
- Tikhonov always multiply by cell_volumes
- Simple only multiply if cell_weights are None

We need to change the behaviour such that 
- cell_weights are always multiplied by all regularization functions.
- SensitivityWeight directive needs to normalize the volumes out
- Edit doc strings to let know users that cell_weights must be volume normalized

**Comment by dccowan** [comment]
@domfournier I am running into this issue with DC/IP octree inversion. Current on the branch "tiled_simulations", I cannot do a straightforward L2 DCR inversion on a tree mesh.

- I re-ran the tutorial example for 3D DCR inversion on the simpeg website and it breaks: https://docs.simpeg.xyz/content/tutorials/05-dcr/plot_inv_3_dcr3d.html#sphx-glr-content-tutorials-05-dcr-plot-inv-3-dcr3d-py

- Also have a zero topography example for the code validations where all the cells are active. I used simple regularization. Nothing fancy, but I get a dimensions mismatch somehow. Here is the error printout

![image](https://user-images.githubusercontent.com/12970009/133856953-6599c65f-629f-444b-8557-fd2e7f564e83.png)

**Comment by domfournier** [comment]
yep, don't use Tikhonov. The cell difference operator doesn't handle the handing faces the same way.

**Comment by dccowan** [comment]
> yep, don't use Tikhonov. The cell difference operator doesn't handle the handing faces the same way.

I was using simple. Not Tikhonov on either

**Comment by domfournier** [comment]
Well your log above seems to pull from regularization\tikhonov ?

**Comment by dccowan** [comment]
> Well your log above seems to pull from regularization\tikhonov ?

Interesting. Here is a screenshot of the regularization and directives
![image](https://user-images.githubusercontent.com/12970009/133859955-28175833-a2cb-401b-a8bd-a262aba5a26c.png)

**Comment by domfournier** [comment]
Oh yep, my bad. Simple is inside Tikhonov... I will need to run it in debug mode.

**Comment by domfournier** [comment]
@dccowan Updated the branch with out fork + minor edits.
Looking good on this side.
![image](https://user-images.githubusercontent.com/55204635/133863239-35129e2c-50ad-419c-8a24-e4f8b8e9d7a0.png)

![image](https://user-images.githubusercontent.com/55204635/133863220-9df9ce79-02ce-4c30-87cb-b010325d4432.png)

**Comment by domfournier** [comment]
And just as a side note, watch out with setting `alpha_s=1e-2`. You are dealing with simple reg here... should be 1 by default.
The reference model will help stabilize the model outside the sensitivity... as you know.
![image](https://user-images.githubusercontent.com/55204635/133863837-c77d3431-88b8-4ff9-b301-ab25f42c4843.png)

**Comment by dccowan** [comment]
Awesome. I'll give it a shot

**Comment by jcapriot** [comment]
Believe this should be all fixed as of `0.18.0` with the new Regularization refactor.
