### ISSUE TITLE
Curvilinear mesh does not have a get_interpolation_matrix method

### ISSUE THREAD

**Issue by ngodber** [simpeg/simpeg#1012]
![image](https://user-images.githubusercontent.com/11834846/120945494-8ff4f680-c77c-11eb-990f-b205adc997d4.png)

**Comment by jcapriot** [comment]
Was having thoughts on this, my current plan is to combine a nearest neighbor lookup with a directed search to find the containing cell, then interpolate from there, but it’ll be subtle to implement properly

**Comment by ngodber** [comment]
I can make a start on this. I'm not on top of the interpolation itself. 
![image](https://user-images.githubusercontent.com/11834846/120948389-72785a80-c785-11eb-878c-d19b77b774b3.png) Blue is average of nodes to cc, yellow is cc to edges, red is cc to node purple is edge to cc. Turning that these into a _matrix_ that performs the averaging via multiplication is the real brain strain
