### ISSUE TITLE
ImportError: cannot import name 'Pardiso' from 'pymatsolver'

### ISSUE THREAD

**Issue by domfournier** [simpeg/simpeg#1015]
The import error seems to occur after updating the simpeg requirements.

- Likely caused by mixing channels `conda` and `conda-forge` in the environment

Workaround needed.

**Comment by jcapriot** [comment]
This might be related to https://github.com/dwfmarchant/pyMKL/pull/14, Have the user print out
```
import sys
print(sys.version)
```

**Comment by domfournier** [comment]
I have managed to make it work with these two steps:

1- Simply trying to import `pyMKL` would return this error:
![Capture](https://user-images.githubusercontent.com/55204635/123309782-33af0800-d4da-11eb-9351-2e599505bded.PNG)

**Solution**: Downgrade mkl to 2020.4

`conda install -c conda-forge mkl=2020.4`

2- The user had a `OMP_NUM_THREADS` in his windows variables. This turns out to be interpreted as a `string` in the initialization of the `pymatsolver.direct` module
![image](https://user-images.githubusercontent.com/55204635/123310267-c18af300-d4da-11eb-86ad-3b3936545519.png)

which causes the importer to crash
![image](https://user-images.githubusercontent.com/55204635/123310651-29d9d480-d4db-11eb-923b-f1132390f195.png)


So the workaround for now is to either get rid of the OMP_NUM_THREADS or add a conversion to `int` in pymatsolver

![image](https://user-images.githubusercontent.com/55204635/123310819-5b52a000-d4db-11eb-81b2-4b5482aa4983.png)


Hope this helps

**Comment by domfournier** [comment]
It also looks like `mkl=2021.2.0` is incompatible with `pymatsolver`

![image](https://user-images.githubusercontent.com/55204635/123311942-91445400-d4dc-11eb-96ca-83b228b305d4.png)

Recommend downgrading to 2020.4

**conda install -c conda-forge mkl=2020.4**

![image](https://user-images.githubusercontent.com/55204635/123312306-02840700-d4dd-11eb-94ac-d6e8181f34aa.png)

**Comment by jcapriot** [comment]
This is probably a good time to just write our own wrapper for it..

Also you're correct. The assignment should've been cast to an integer, my bad.

**Comment by domfournier** [comment]
Fun fact, the `mkl_get_max_threads` returns the number of cores on the machine, which is half the thread count for multi-threaded machines...

**Comment by jcapriot** [comment]
As we no longer use pyMKL to interface with intel's pardiso solver, i'm closing this issue.
