### ISSUE TITLE
order of release notes in the docs 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#1017]
Right now, the order is oldest (0.14.0 -- when we started including them in the docs) to most recent. This means that the most recent is at the bottom. I would suggest that we reverse this so that the most recent release notes are always at the top http://docs.simpeg.xyz/content/release/index.html#release-notes

**Comment by lheagy** [comment]
Also, adding a release date to each would be helpful for reference (exactly how long has it been since I updated??)

**Comment by prisae** [comment]
I agree, I think dates are important.

Also, I usually have a file CHANGELOG.md in the root file. This has a couple of advantages, in my opinion:

- It is also distributed with the package (e.g. PyPI)
- Every PR can add its changes to the changelog file, making it easier to create a release as all changes should already be listed
- In the docs it is simply the CHANGELOG.md file that is rendered
- When releasing, one can simply copy the changelog-content to the GitHub release info

This is just as info/suggestion, there are of course a gazillion way how to handle this. Example links of what I mention above:

- Changelog in the root repo: https://github.com/emsig/emg3d/blob/main/CHANGELOG.rst
- Rendered version in the manual: https://emg3d.emsig.xyz/en/latest/manual/changelog.html
- When releasing, simply copy it to the release notes: https://github.com/emsig/emg3d/releases

**Comment by jcapriot** [comment]
Believe this was fixed a while ago. If we still do want a changelog in the root folder, lets open another issue just for that.
