### ISSUE TITLE
Confusion in contras density and gz anomaly

### ISSUE THREAD

**Issue by dickyaz** [simpeg/simpeg#1023]
Hi, I am following the SimPEG Forward Simulation of Gravity Anomaly in this [page](https://docs.simpeg.xyz/content/tutorials/03-gravity/plot_1a_gravity_anomaly.html)
I noticed that the the sphere model which has positive value of contrast density is resulting negative anomaly, in opposite the block model which has negative value is resulting positive anomaly.
Isn't that the density contrast and anomaly supposed to be proportional to each other?
I got confused, if I would like to simulate anomaly as I measure using gravimeter, what is the receiver component that should be used? Thank you.

**Comment by xiaolongw1223** [comment]
SimPEG uses the right handed coordinate system where Z is positive upward, so gravity anomalies look "inconsistent" with density values. An option is you can flip the sign of data in visualization to make positive gravity signals correspond to positive density models.

In most cases, I think you should use "gz" component for the data measured from gravimeter, unless you purposely measured the data at different hight to simulate the gravity gradient data using gravimeter.

**Comment by dickyaz** [comment]
Thank you for your answer @xiaolongw1223 

I also found "inconsistent" result between the "gz" and "gzz" component. Here I attached the results from same model with positive contrast density, I fliped the sign of simulated data and found the "gzz" component resulting negative anomaly.
Is it caused by the same issue of coordinate system?

![gz](https://user-images.githubusercontent.com/33740692/126730609-e7c7eb29-edb8-466a-b53b-176cbe0d97de.png)
![gzz](https://user-images.githubusercontent.com/33740692/126730611-118f9bbb-e1af-49fa-8447-d469b6c58915.png)

**Comment by xiaolongw1223** [comment]
You are welcome! We don't need to flip sign for gzz data, an example shown [here](https://docs.simpeg.xyz/content/tutorials/03-gravity/plot_1b_gravity_gradiometry.html#sphx-glr-content-tutorials-03-gravity-plot-1b-gravity-gradiometry-py)

I think z direction doesn't affect gzz data. For example, assuming we have two data: d1 (low elevation), d2 (high elevation),  so gzz=(d1-d2)/h, if z is positive downward, and gzz=(d2-d1)/h, if z is positive upward. I assume the sign was flipped in forward modeling for gravity gradiometry data.

**Comment by domfournier** [comment]
That's correct, but the same issue should happen for gxz and gyz.

**Comment by dickyaz** [comment]
@xiaolongw1223 Wonderful! I got the point.
I also checked "gxz" and "gyz" as @domfournier said, yes it has same issue.
So in conclusion to obtained true value we need to flip the sign for "gz", "gxz", and "gyz" component.

Here are the "gy" and "gyz" anomaly of model with positive contrast density, as is without flip the sign.
![gy](https://user-images.githubusercontent.com/33740692/126737919-bb9ffb7c-3ec5-4580-a2ad-8c500d33275c.png)
![gyz](https://user-images.githubusercontent.com/33740692/126737918-5be42eb8-f5db-48d6-b06b-366f64dc2968.png)

**Comment by jcapriot** [comment]
This is a common confusion in SimPEG's gravity module, an unfortunate side effect of us adhering to the right handed coordinate system (Which makes sense for us to do in my opinion because of self-consistency).

The reason it does not effect `gzz` is essentially because the `z` direction is done twice so it comes out the same either way, `(-1 * -1) = (1 * 1)`.
