### ISSUE TITLE
DC 2D Fields with boundary conditions

### ISSUE THREAD

**Issue by jcapriot** [simpeg/simpeg#1033]
The 2D DC field object other properties (besides potential) need to be updated to properly account for the boundary conditions.

I believe this only effects the cell centered discretization though.

**Comment by ngodber** [comment]
For posterity - note taking screen captures in case thread exceeds 90 days age in slack.

![image](https://user-images.githubusercontent.com/11834846/198752109-b428a084-724d-4348-a689-212dbfa87fc9.png)
![image](https://user-images.githubusercontent.com/11834846/198752145-d5822746-055f-461a-b20a-ef2b2f11058a.png)
@jcapriot @sgkang
