### ISSUE TITLE
Issue between simpeg and sklearn

### ISSUE THREAD

**Issue by Patrick-Cole** [simpeg/simpeg#1055]
I have tried to do a fresh install of simpeg in anaconda and get the following error (after import SimPEG):

File "C:\Users\pcole.CGS\Anaconda3\envs\ptest\lib\site-packages\SimPEG\utils\pgi_utils.py", line 22, in <module>
    from sklearn.mixture._base import _check_X, check_random_state, ConvergenceWarning
ImportError: cannot import name '_check_X' from 'sklearn.mixture._base' (C:\Users\pcole.CGS\Anaconda3\envs\ptest\lib\site-packages\sklearn\mixture\_base.py)

After investigation, I discovered that it is due to a change in the sklearn library, after they updated from 0.24 to the newest version 1.0.1. If I downgrade my sklearn, it seems to work, but I would prefer using the latest version if possible. In addition, anaconda installer will automatically install version 1.0.1, which breaks simpeg.

**Comment by thast** [comment]
thanks! It has been fixed in the new release `0.15.2`
