### ISSUE TITLE
add python version to requirements?

### ISSUE THREAD

**Issue by ckohnke** [simpeg/simpeg#1068]
Had a colleague running some MT forward modeling on the 0.16 release and was getting a singular matrix warning during the simulation. After much investigation, it seems that parts of the simulation class are incompatible with python 3.6. The code does not give an indication that the error lies with the python versioning and keeps going until instead dpred just returns NaN values! Quite difficult to track down! Updating to python 3.9 fixed the issue with no changes to the code.

While python 3.6 is end of life now, and 3.7-3.10 are the active releases, I do think parts of the codebase use features that are newly available in 3.9 (possibly 3.8). It would be nice to know the lowest active python release compatible with SimPEG and have that enforced during install, or throw a warning that the current python version is unsupported (on install? on SimPEG import?). The easiest way is likely just adding the python version (whatever that happens to be) to the requirements(_dev).txt so the environment manager can handle the details.

**Comment by jcapriot** [comment]
Hey this was added during the #1179 !
