### ISSUE TITLE
from __future__ imports

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#1078]
We have quite a number of `from __future__ import X` statements still around in SimPEG. Since we don't support python 2.7 (#731), these are no longer needed, correct?

**Comment by mplough-kobold** [comment]
There are no Python 2.7 `__future__` statements left anymore (they were cleaned up in https://github.com/simpeg/simpeg/pull/1123), so I think this can be closed as completed.

The only remaining instances of `from __future__ import X` are:

```
SimPEG/regularization/base.py
1:from __future__ import annotations

SimPEG/regularization/pgi.py
1:from __future__ import annotations

SimPEG/regularization/sparse.py
1:from __future__ import annotations

SimPEG/regularization/vector.py
1:from __future__ import annotations

SimPEG/utils/code_utils.py
1:from __future__ import annotations
```

These should stay; according to Python's [`__future__` documentation](https://docs.python.org/3.12/library/__future__.html), annotations are not yet mandatory as of Python 3.12.

**Comment by jcapriot** [comment]
You are correct!
