### ISSUE TITLE
Tikhonov regularization issue

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#108]
When using the regularization with .smoothModel = True, a non 0 value is returned for the m_0 calculation, where m_ref = m_0. This rises from that in Regularization.py, in the Tikhonov class (line 280), the return from if self.smoothMod == True should be a difference not a sum. 
            return 0.5*(r1.dot(r1)+r2.dot(r2)) but should return 0.5*np.abs(r1.dot(r1)-r2.dot(r2))

Right?

**Comment by lheagy** [comment]
The issue was in the calculation of r1, r2 they should be using m-mref not just m. see the pull request I just made

**Comment by lheagy** [comment]
@grosenkj : can we close this?

**Comment by grosenkj** [comment]
This has been fixed.
