### ISSUE TITLE
Not predicting halfspace value

### ISSUE THREAD

**Issue by alkirkby** [simpeg/simpeg#1088]
Hello,

I am running the example for predicting 3D DC resistivity data. I have modified it such that the conductivity model is a halfspace (100 ohm-m) with no topography.

The apparent resistivities that I predict range from 100 to 110 ohm-m. In my own (more complex) example the range is even more. Why is this? Shouldn't the code be predicting the halfspace value of 100 ohm-m?

I am using the version that is up on conda forge. 

Cheers, Alison.

**Comment by lheagy** [comment]
Thanks for your question @alkirkby! This can be a result of discretization errors and might indicate that you want to further refine your mesh. We talked a bit about this in the [2020 Transform tutorial](https://curvenote.com/@simpeg/transform-2020-simpeg-tutorial/geophysical-inversions-with-simpeg) and explore some aspects of how mesh design impacts errors. In the video, this discussion starts at 1:57 (https://youtu.be/jZ7Sj9cnnso?t=7035)

**Comment by alkirkby** [comment]
Thanks @lheagy, good to know. Will take a look when I get a chance.

**Comment by lheagy** [comment]
I will close this, but feel free to re-open @alkirkby if you still have questions here!
