### ISSUE TITLE
Better handling of _Jmatrix updates

### ISSUE THREAD

**Issue by domfournier** [simpeg/simpeg#1090]
Going through the latest update I noticed a major slowdown of the inversion. I came to realize that `simulation._Jmatrix` gets deleted during the CG iterations every time `self.model` gets updated (which happens on the `fields` calls). The new behaviour got introduced on this property.

```
@property
    def deleteTheseOnModelUpdate(self):
        toDelete = super().deleteTheseOnModelUpdate
        if self._Jmatrix is not None:
            toDelete = toDelete + ["_Jmatrix"]
        if self.gtgdiag is not None:
            toDelete = toDelete + ["gtgdiag"]
        return toDelete
```

This is likely something we don't want, or at least change the workflow such that `self.model` only gets triggered at the end of a CG cycle, not during.

To be discussed with the group.

**Comment by jcapriot** [comment]
To be clear, the `deleteTheseOneModelUpdate` items only get deleted when the model is actually changed. It internally does an `np.allclose` check to see if it needs to be deleted. Therefore during the CG iterations the same model is repeatedly passed to the call and thus it never does get deleted.
