### ISSUE TITLE
normalization in gravity forward modeling

### ISSUE THREAD

**Issue by fabioca** [simpeg/simpeg#1092]
thank you for the nice code. I am testing teh tutorial on gravity modeling. Beside the mentioned confusion between the density contrast and the sign of the anomaly, I noticed that the anomaly is obtained by removing the mean. This is not correct in my opinion and may be another source of confusion. I would be nice to benchmark the tutorial results with other available open source code (as tesseroids , for gravity).
I checked todat a bit better: the gz values in the output file seems correct, but the colorscale in the figure of gravity tutorial, if modified with one prism (plot_1a_gravity_anomaly.py) is wrong.

**Comment by lheagy** [comment]
@dccowan: would you mind taking a look at the tutorial that @fabioca mentions here?

**Comment by jcapriot** [comment]
I am unsure what exactly you're referring to by saying we are removing the mean value. In geophysics, we often process our gravity data in such a way that we are looking for a density contrast and not an absolute density. The example code uses a density contrast model. It is also valid for an absolute density value, if that's what you wanted to work with.
