### ISSUE TITLE
No module named 'SimPEG.Utils'

### ISSUE THREAD

**Issue by Shreya695** [simpeg/simpeg#1101]
i am not able to load a p extension file with simpeg. It says No module named 'SimPEG.Utils'. Please resolve my issue. Thank you in advance. Below is the code that I am using
A= open('C:\\Users\\anup\\Astic-2020-JointInversion-master\\Petrophysics\\gmm_density_HK.p','rb')
clf = pickle.load(A)
n = clf.n_components

**Comment by thast** [comment]
Answered in discourse here: https://simpeg.discourse.group/t/loading-petrophysical-file/360
