### ISSUE TITLE
QuadTree depth

### ISSUE THREAD

**Issue by vahid13421** [simpeg/simpeg#1106]
Hello every body
I am working on gravity forward simulation by making a quadtree mesh and the assigning Z to each cell.
But in SimPEG 0.17.0 in 'simulation3DIntegral"  every time I get the error "Nonetype" because the quad tree does not have "hz.min()"
I tried to assign hz attribute but it does not work.
I appreciate the answers to this problem.
Thanks a lot
Vahid E.Ardestani

**Comment by domfournier** [comment]
Hi @vahid13421 
The team has added a class specific for quadtree. Take a look at the unit test here: https://github.com/simpeg/simpeg/blob/main/tests/pf/test_pf_quadtree_inversion_linear.py

**Comment by vahid13421** [comment]
Thanks a lot

**Comment by vahid13421** [comment]
Dear Dom
I am working on the code you addressed. Just in code, we should import
"gravity.SimulationEquivalentSourceLayer".
This module does not exist in SimPEG 0.17.0.
Please guide me on how to be able to have access to it.
Thanks a lot.
Best regards

**Comment by jcapriot** [comment]
This simulation is now included in the most recent release `0.18.0`. Previously it was only available from the latest development on `main`.

**Comment by vahid13421** [comment]
Thanks a lot.
