### ISSUE TITLE
Remove plotting method in favor of discretize implementation

### ISSUE THREAD

**Issue by domfournier** [simpeg/simpeg#1110]
https://github.com/simpeg/simpeg/blob/d6651d893acdb66195c0b4f02e766424a8b529c2/examples/03-magnetics/plot_inv_mag_MVI_Sparse_TreeMesh.py#L128

**Comment by santisoler** [comment]
The `plotVectorSectionsOctree` function was removed in 0d9fee8880f4f68acfd19a67ec9166ed47fa4f1e. I think we could close this issue then. Is that ok @domfournier?

For now I'm removing it from the milestones for v0.23.0 since there's nothing urgent to fix here.

**Comment by domfournier** [comment]
Yep
