### ISSUE TITLE
Assigning norms fails in regularization.Sparse for numpy.ndarray of `int`

### ISSUE THREAD

**Issue by dccowan** [simpeg/simpeg#1116]
I updated my SimPEG validations in accordance with the improvements to the regularization classes. I had two sparse-norm inversions for potential field data where all inversion parameters were the same. The only difference was:

- One assigned the norms using `reg.norms = np.r_[0.0, 1.0, 1.0, 1.0]`, which is a numpy ndarray of float
- One assigned the norms using `reg.norms = np.r_[0, 1, 1, 1]`, which is a numpy ndarray of int

In the latter case, the `get_lp_weights` method will fail on ln 90 since self.norms returns a single numerical value and not a numpy array. I can see others assigning the norms in a similar manner and getting the same error.

**Comment by jcapriot** [comment]
What's causing the issue here is that `np.r_[0, 1, 1, 1]` creates an array with `dtype=np.int64` which is not an instance of `int`. Ideally what needs to happen is that the incoming values are converted to a float.
