### ISSUE TITLE
Active Cells names

### ISSUE THREAD

**Issue by jcapriot** [simpeg/simpeg#1121]
We need to standardize the name we use to refer to active cell index arrays throughout SimPEG. In some areas it is referred to as `ind_active`, in other `actInd`, and some newer ones as `active_cells`.

I would favor switching all of them to `active_cells`.

**Comment by thibaut-kobold** [comment]
`active_cells` sounds good to me.

**Comment by santisoler** [comment]
Now we have `active_cells` in VRM and potential field simulations, and in maps.  The missing places are:

* the `spectral_ip_mappings` function,
* the `drapeTopotoLoc` function.

Which I don't think they are widely used.
