### ISSUE TITLE
run magnetic example in fresh simpeg

### ISSUE THREAD

**Issue by kashkoulimohammad** [simpeg/simpeg#1127]
Dear all,

I installed a fresh simpeg and ran a forward simulation of the total magnetic intensity data example.
The faced this error:
`(simpegnew) C:\Users\Mohammad\Desktop>python plot_2a_magnetics_induced.py
C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\discretize\utils\code_utils.py:182: FutureWarning: TensorMesh.vectorNx has been deprecated, please use TensorMesh.nodes_x. It will be removed in version 1.0.0 of discretize.
  warnings.warn(message, Warning)
C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\discretize\utils\code_utils.py:182: FutureWarning: TensorMesh.vectorNy has been deprecated, please use TensorMesh.nodes_y. It will be removed in version 1.0.0 of discretize.
  warnings.warn(message, Warning)
C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\discretize\utils\code_utils.py:182: FutureWarning: TensorMesh.vectorCCx has been deprecated, please use TensorMesh.cell_centers_x. It will be removed in version 1.0.0 of discretize.
  warnings.warn(message, Warning)
C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\discretize\utils\code_utils.py:182: FutureWarning: TensorMesh.vectorCCy has been deprecated, please use TensorMesh.cell_centers_y. It will be removed in version 1.0.0 of discretize.
  warnings.warn(message, Warning)
C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\discretize\base\base_regular_mesh.py:1049: FutureWarning: nCz has been deprecated, please access as mesh.shape_cells[2]
  warnings.warn(
Traceback (most recent call last):
  File "plot_2a_magnetics_induced.py", line 172, in <module>
    simulation = magnetics.simulation.Simulation3DIntegral(
  File "C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\properties\base\base.py", line 280, in __call__
    obj.__init__(*args, **kwargs)
  File "C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\SimPEG\potential_fields\magnetics\simulation.py", line 34, in __init__
    super().__init__(mesh, **kwargs)
  File "C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\SimPEG\potential_fields\base.py", line 32, in __init__
    LinearSimulation.__init__(self, mesh, **kwargs)
  File "C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\SimPEG\simulation.py", line 496, in __init__
    super(LinearSimulation, self).__init__(mesh=mesh, **kwargs)
  File "C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\SimPEG\simulation.py", line 215, in __init__
    super(BaseSimulation, self).__init__(**kwargs)
  File "C:\Users\Mohammad\anaconda3\envs\simpegnew\lib\site-packages\properties\base\base.py", line 314, in __init__
    raise AttributeError(
AttributeError: Keyword input 'ind_active' is not a known  property or attribute of Simulation3DIntegral`
How can I fixed it?

**Comment by jcapriot** [comment]
It would appear that your installed version of SimPEG is behind that which is necessary for the script you ran. If you update SimPEG to the latest version, or one that matches your script, it should work

**Comment by kashkoulimohammad** [comment]
I installed the last version from conda.🤔

**Comment by nwilliams-kobold** [comment]
What version of simpeg is shown if you enter `conda list simpeg`? It should be 0.18.1.
Have you tried getting the latest version of the script from github: https://github.com/simpeg/simpeg/blob/main/tutorials/04-magnetics/plot_2a_magnetics_induced.py?

**Comment by lheagy** [comment]
I will close as there hasn't been activity here for a while. Please feel free to re-open if there are lingering questions
