### ISSUE TITLE
Minor pip issue

### ISSUE THREAD

**Issue by colinrr** [simpeg/simpeg#115]
Hey Rowan, long time no see! Just tried installing SimPEG with pip to MacOSX - the source tar that comes up is SimPEG-0.1.3.tar.gz. The setup.py spits out an error at line 53 - no files matching "interputils_cython.pyx". It seems the file in the actual tar is "interputils_cython.c". 

Not sure if I could have somehow gotten an out of date install file, but if not it might be worth the quick update. I was able to install via git instead.

**Comment by rowanc1** [comment]
Hello sir! It looks like the setup.py isn't configured quite right to handle the cython, I will have to look into this, there are backups in pure python for the interp utils regardless, so hopefully you can ply around with the lib a bit? let me know if you want any pointers on examples, notebooks, etc., we are still a bit light on those..!

**Comment by bsmithyman** [comment]
I can maybe have a look too. Should have some time tomorrow if you’re not on it first.

**Comment by rowanc1** [comment]
See #116
