### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by appproximate** [simpeg/simpeg#116]
I'm using Anaconda distribution on Windows 10, when running the command "pip install SimPEG", I received "ValueError: 'SimPEG/Utils/interputils_cython.pyx' doesn't match any files". 

How can I resolve this error?

**Comment by rowanc1** [comment]
For now, the best bet is to install via source:

```
git clone http://github.com/simpeg/simpeg.git
cd simpeg
python setup.py build_ext --inplace
# add SimPEG to your python path
```

Even if the last step does not work, the package will still work, the cython is only for faster interpolation, which has a packup written in pure python.

We will fix pip in the next few weeks.

**Comment by bsmithyman** [comment]
Is this as simple as adding Cython to the required dependencies in the `setup.py` file? Something like this:

    install_requires = ['numpy>=1.7',
                        'scipy>=0.13',
                        'Cython'
                       ],

Not sure what version number to require, though. Although, if the original issue is happening on Windows under Anaconda, presumably Cython is installed by default, right?

**Comment by bsmithyman** [comment]
Ah, I stand corrected; the issue is that the .tar.gz file on PyPI actually contains a .c file, unlike the Git master. Instead of calling `cythonize`, we can do this with vanilla distutils and avoid the extra dependency. Here's the fix for that version, which is then no longer dependent on having Cython installed:
````
#!/usr/bin/env python
"""SimPEG: Simulation and Parameter Estimation in Geophysics

SimPEG is a python package for simulation and gradient based
parameter estimation in the context of geophysical applications.
"""

from distutils.core import setup
from setuptools import find_packages
from setuptools.extension import Extension
import numpy as np

CLASSIFIERS = [
'Development Status :: 4 - Beta',
'Intended Audience :: Developers',
'Intended Audience :: Science/Research',
'License :: OSI Approved :: MIT License',
'Programming Language :: Python',
'Topic :: Scientific/Engineering',
'Topic :: Scientific/Engineering :: Mathematics',
'Topic :: Scientific/Engineering :: Physics',
'Operating System :: Microsoft :: Windows',
'Operating System :: POSIX',
'Operating System :: Unix',
'Operating System :: MacOS',
'Natural Language :: English',
]

import os, os.path

with open("README.rst") as f:
    LONG_DESCRIPTION = ''.join(f.readlines())

setup(
    name = "SimPEG",
    version = "0.1.3",
    packages = find_packages(),
    install_requires = ['numpy>=1.7',
                        'scipy>=0.13'
                       ],
    author = "Rowan Cockett",
    author_email = "rowan@3ptscience.com",
    description = "SimPEG: Simulation and Parameter Estimation in Geophysics",
    long_description = LONG_DESCRIPTION,
    license = "MIT",
    keywords = "geophysics inverse problem",
    url = "http://simpeg.xyz/",
    download_url = "http://github.com/simpeg/simpeg",
    classifiers=CLASSIFIERS,
    platforms = ["Windows", "Linux", "Solaris", "Mac OS-X", "Unix"],
    use_2to3 = False,
    include_dirs=[np.get_include()],
    ext_modules = [Extension('interputils_cython', sources=['SimPEG/Utils/interputils_cython.c'])]
)
````

In the Git master version, which does contain the file `interputils_cython.pyx`, we should add a dependency on Cython so that the install works on systems without Cython already installed.

**Comment by rowanc1** [comment]
This should now be fixed. Use: v0.1.9
