### ISSUE TITLE
Multiprocessing crash on Windows

### ISSUE THREAD

**Issue by domfournier** [simpeg/simpeg#1169]
Issue introduced on #1135
Running any of the potential fields examples/tutorials on Windows causes a pretty bad crash

![image](https://user-images.githubusercontent.com/55204635/214723290-2cbbc8e1-c1c8-403d-ace7-93e52562d3fc.png)

A fix is needed in high priority.

**Comment by thibaut-kobold** [comment]
`multiprocessing` has been an issue with some cloud platform as well that use parallelization at another level. Making it optional would be ideal in our case (basically choose between 1: no parallelization; 2: multiprocessing parallelization; 3: dask parallelization)

**Comment by jcapriot** [comment]
I think we can just only do multiprocessing if number of threads is None or higher than 1.

but still very curious why it causes these issues.

**Comment by domfournier** [comment]
Has to do with the way child processes are spawned on Windows...

https://www.pythonforthelab.com/blog/differences-between-multiprocessing-windows-and-linux/

https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

**Comment by thibaut-kobold** [comment]
@jcapriot : we use `dask` to parallelize multiple simulations or inversions. That higher level of `dask` is conflicting with `multiprocessing`, even at the worker level, so "do multiprocessing if number of threads is None or higher than 1" would not work for us. Our solution has been to have `from SimPEG import dask` our default (so effectively completely avoiding any `multiprocessing` implementation).

I don't have a error log now but that is why I would advocate as having multiprocessing has an option (even if `multiprocessing` is the default, I am fine with that)

**Comment by jcapriot** [comment]
@thibaut-kobold, that is a separate (but related) issue to the one Dom detailed.

**Comment by thibaut-kobold** [comment]
yep, just wanted to give you the big picture.

related: even sklearn warns about multiprocessing: https://scikit-learn.org/stable/faq.html#why-do-i-sometime-get-a-crash-freeze-with-n-jobs-1-under-osx-or-linux

**Comment by jcapriot** [comment]
looks like for this to work properly on windows, the call to `freeze_support` needs to be guarded by a
```
if __name__ == '__main__':
    freeze_support()
    eval_main_script_function()
    ...
```

This is odd enough behavior that I think it's best to default to single thread (no multiprocessing) Then only use multiprocessing when setting n_threads on the normal simulation class.

**Comment by domfournier** [comment]
I am cool with that.

**Comment by domfournier** [comment]
I will point out though that removing `processes=self.n_processes` from inside the `Pool()` works, and just use all cores. So maybe it's something specific to the `processes` argument?

**Comment by jcapriot** [comment]
Were you explicitly setting the `n_processes` property?

**Comment by domfournier** [comment]
Nevermind, I take it back - still crashes. Somehow pycharm fixed it on the second run. Just tested from a command line and the crash happens everytime...

**Comment by jcapriot** [comment]
Does it crash when the tests are run with pytest?

**Comment by domfournier** [comment]
It does not, which makes sense since every test file has
![image](https://user-images.githubusercontent.com/55204635/214734269-a2422d64-3642-45b1-ab48-2d92b95d1ce9.png)

**Comment by jcapriot** [comment]
Just to double check, are you running the test scripts like `pytest test_script.py`

**Comment by jcapriot** [comment]
Started this at #1170. Basically I think we should probably default to `1` on Windows only. Or update the tutorials and examples to have a check for it?

**Comment by domfournier** [comment]
Yes, I ran it from pytest.

Other option is that we protect the entry point of every example and tutorial files. Generally good practice anyway...

**Comment by jcapriot** [comment]
For the tutorials and examples, we'll just have to check how the formatting works with the sphinx-gallery extension conversion from .py to the .rst/.ipynb formats.

**Comment by clberube** [comment]
For what it's worth, the same crash and warnings happen when running any potential fields simulation with the M1 Pro chip on macOS 13.0 (Ventura). Calling `gravity.simulation.Simulation3DIntegral().dpred()` triggers the crash. 
What is most troubling is that the entire script will loop infinitely after executing that line. Traceback attached.

So that issue is probably not limited to Windows. 

Cheers,
Charles

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/charles/opt/miniconda3/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/charles/opt/miniconda3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/charles/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/charles/Repos/glq2200/scripts/make-co2-data.py", line 179, in <module>
    dpred = simulation.dpred(model)
  File "/Users/charles/opt/miniconda3/lib/python3.9/site-packages/SimPEG/simulation.py", line 515, in dpred
    return self.fields(self.model)
  File "/Users/charles/opt/miniconda3/lib/python3.9/site-packages/SimPEG/potential_fields/gravity/simulation.py", line 38, in fields
    fields = mkvc(self.linear_operator())
  File "/Users/charles/opt/miniconda3/lib/python3.9/site-packages/SimPEG/potential_fields/base.py", line 170, in linear_operator
    with multiprocessing.pool.Pool() as pool:
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/charles/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by jcapriot** [comment]
The issue is related to how multiprocessing creates new processes on Windows and MacOS. https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods Shows that Windows and MacOS both use the `spawn` method, which re-imports the main module of your script. Therefor if you haven't guarded you executable code with

```
if __name__ == '__main__':
    ...
```
as the warning above suggests as a fix, you will likely create infinite processes, as each time script is imported, more and more processes are created. The fix essentially only runs your code when in the main processes.

We decided to switch the default of the potential fields simulations to be single threaded due to this behavior being unexpected by unfamiliar python users, the documentation then will describe the proper way of using potential fields simulations with multiprocessing enabled #1186.
