### ISSUE TITLE
eval2Deriv in Tikhonov Regularization

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#117]
@sgkang I think that the eval2deriv has not been implemented for this class? Can you confirm..?

**Comment by sgkang** [comment]
@rowanc1 In Tiknov, we are inheriting eval2deriv in baseregularization class. And I think that is correct so that we do not need to write a eval2deriv for Tiknov.

**Comment by lheagy** [comment]
Is this resolved?
