### ISSUE TITLE
Initial Beta Estimator

### ISSUE THREAD

**Issue by dccowan** [simpeg/simpeg#1172]
This work is currently being carried out on the 

In directives, we would like to have:
- An option to set the starting beta manually
- Several options to estimate a good starting beta (power iteration, max derivative, Rayleigh quotient)

Right now, we have the BetaEstimation_ByEig class which only estimates based on power iteration. And the input parameters aren't exactly "SimPEG'-y. Since the input parameters for each of the estimator methods are difference, suggest having a class for each; e.g. *InitialBetaPowerIteration*, *InitialBetaMaxDerivative* and *InitialBetaRayleightQuotient* .

Thoughts?

**Comment by jcapriot** [comment]
I believe we settled this on #1173
