### ISSUE TITLE
SimPEG not running under MS windows 10

### ISSUE THREAD

**Issue by aminkhalil** [simpeg/simpeg#1185]
I am trying to run SimPEG under windows. In running the 1a plot gravity example, the import step keep giving me valueError. The details of the error comes from mismatch between c++ array size and Pyobject array size. I created new environment and installed everything from scratch. The error is the same. I installed latest version of VC studio run time. The error is the same. What I didn't do is reinstalling SimPEG after installing VC runtime

**Comment by jcapriot** [comment]
This is due to a different version of numpy being used to compile extension module compared to the numpy version that is in your environment. We recommend installing through `conda` to ensure that built package dependencies are properly handled.

**Comment by aminkhalil** [comment]
Dear Joseph,
I created new environment and used conda to create everything from scratch.
I guess the problem in discretize. I will try to compile it from source. I
am sorry for late reply. I am sorry also the issue is closed.
Best regards

في الخميس، ٢ مارس ٢٠٢٣ ٢:٣٥ ص Joseph Capriotti ***@***.***>
كتب:
