### ISSUE TITLE
How to Load ERT Data 2D with SimPEG

### ISSUE THREAD

**Issue by kafahabibullah1453** [simpeg/simpeg#1187]
Excuse me. This is My Data, And I Want to load this data with SimPEG. How to load dan Run this Data with SimPEG?

Line 3
5.00
1
135
1
0
7.500 5.000 25.953
12.500 5.000 21.388
17.500 5.000 24.271
22.500 5.000 20.700
27.500 5.000 23.528
32.500 5.000 16.644
37.500 5.000 22.429
42.500 5.000 17.247
47.500 5.000 22.082
52.500 5.000 22.612
57.500 5.000 22.551
62.500 5.000 23.626
67.500 5.000 22.192
72.500 5.000 18.738
77.500 5.000 17.175
82.500 5.000 17.186
87.500 5.000 16.150
92.500 5.000 21.381
97.500 5.000 14.417
102.500 5.000 15.231
107.500 5.000 17.034
112.500 5.000 16.715
117.500 5.000 16.326
122.500 5.000 16.134
127.500 5.000 15.873
132.500 5.000 16.054
137.500 5.000 16.892
15.000 10.000 32.539
20.000 10.000 34.671
25.000 10.000 34.340
30.000 10.000 31.659
35.000 10.000 29.921
40.000 10.000 30.499
45.000 10.000 33.274
50.000 10.000 36.368
55.000 10.000 35.432
60.000 10.000 35.473
65.000 10.000 36.425
70.000 10.000 32.875
75.000 10.000 28.551
80.000 10.000 27.134
85.000 10.000 28.713
90.000 10.000 33.241
95.000 10.000 30.130
100.000 10.000 22.358
105.000 10.000 25.060
110.000 10.000 29.630
115.000 10.000 27.438
120.000 10.000 25.058
125.000 10.000 26.280
130.000 10.000 28.029
22.500 15.000 50.707
27.500 15.000 46.008
32.500 15.000 44.648
37.500 15.000 40.983
42.500 15.000 45.120
47.500 15.000 46.966
52.500 15.000 50.744
57.500 15.000 50.704
62.500 15.000 50.823
67.500 15.000 47.655
72.500 15.000 41.752
77.500 15.000 38.950
82.500 15.000 40.621
87.500 15.000 47.075
92.500 15.000 45.220
97.500 15.000 39.883
102.500 15.000 35.203
107.500 15.000 37.283
112.500 15.000 38.946
117.500 15.000 39.485
122.500 15.000 38.219
30.000 20.000 56.475
35.000 20.000 52.128
40.000 20.000 52.079
45.000 20.000 56.338
50.000 20.000 59.175
55.000 20.000 65.185
60.000 20.000 65.751
65.000 20.000 58.005
70.000 20.000 54.528
75.000 20.000 50.733
80.000 20.000 49.257
85.000 20.000 54.346
90.000 20.000 53.878
95.000 20.000 52.586
100.000 20.000 52.184
105.000 20.000 46.160
110.000 20.000 45.999
115.000 20.000 47.880
37.500 25.000 63.774
42.500 25.000 64.606
47.500 25.000 69.438
52.500 25.000 72.883
57.500 25.000 74.461
62.500 25.000 72.160
67.500 25.000 68.182
72.500 25.000 64.029
77.500 25.000 60.773
82.500 25.000 61.943
87.500 25.000 60.453
92.500 25.000 59.597
97.500 25.000 61.592
102.500 25.000 62.025
107.500 25.000 56.300
45.000 30.000 76.710
50.000 30.000 78.330
55.000 30.000 81.686
60.000 30.000 82.785
65.000 30.000 79.251
70.000 30.000 75.623
75.000 30.000 74.222
80.000 30.000 73.165
85.000 30.000 67.406
90.000 30.000 64.587
95.000 30.000 66.544
100.000 30.000 69.382
52.500 35.000 89.413
57.500 35.000 88.093
62.500 35.000 88.034
67.500 35.000 85.235
72.500 35.000 83.253
77.500 35.000 84.448
82.500 35.000 78.688
87.500 35.000 71.444
92.500 35.000 71.176
60.000 40.000 92.777
65.000 40.000 92.777
70.000 40.000 91.644
75.000 40.000 91.746
80.000 40.000 87.786
85.000 40.000 81.188
67.500 45.000 98.049
72.500 45.000 98.779
77.500 45.000 94.726
0
0
0
0

**Comment by jcapriot** [comment]
@kafahabibullah1453 Thank you for using SimPEG. I would recommend getting in touch with us on either [discourse](https://simpeg.discourse.group/), or [slack](slack.simpeg.xyz) if you want to ask questions about how to use simpeg. We are
more than happy to interact there with specific questions.

You might want to also include details about the data file you're reading in, as it is, there is very little metadata that tells us what even the different columns are. Again, please reach out on slack/discourse and include these details.
