### ISSUE TITLE
Zero and Identity classes

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#119]
To make derivatives easier to read!

**Comment by lheagy** [comment]
We need to be able to treat them as matrices too so that 

```
        Z = Zero()
        s = np.random.rand(5,1)
        q = Z*s
        assert q.shape == s.shape
        assert np.all(q == np.zeros_like(s))
```

passes

**Comment by rowanc1** [comment]
You need the shape property? It does multiply matrices but the shape
property does not persist.

Where do you need shape of a zero?
R

**Comment by rowanc1** [comment]
We could init zeros and ones with a shape? Rather than inferring one from
what it multiplies, which is ambiguous. When are we comparing arrays to
zero?

**Comment by lheagy** [comment]
There are some error checks in the Survey class :   

If you checkout the ZeroIdentity branch of simpegem and run test_FDEM.py
 
File "/Users/lindseyjh/git/python_symlinks/SimPEG/Survey.py", line 175, in __setitem__
    assert isinstance(value, np.ndarray), 'value must by ndarray'
AssertionError: value must by ndarray

We can probably work around this or give the zeros and ones with a shape. Worth some thought...

**Comment by rowanc1** [comment]
@lheagy is this merged in, can we close this issue?

**Comment by lheagy** [comment]
yep!
