### ISSUE TITLE
when I  executing  plot_3_tree_models.py， an error occurs

### ISSUE THREAD

**Issue by MsBruce** [simpeg/simpeg#1265]
![7](https://github.com/simpeg/simpeg/assets/19356568/85f4ff12-05a1-439c-aa08-6d10345d0a72)

**Comment by MsBruce** [comment]
who can help me?

**Comment by domfournier** [comment]
Hi MsBruce,

Apologies for the late reply. 

The function call should have worked from simpeg 0.20

![image](https://github.com/simpeg/simpeg/assets/55204635/f545a816-3618-4797-8c42-45335649f3aa)

Can you check your local version?
