### ISSUE TITLE
DOC: section titles are overlapping and banner for "edit on github" seems broken

### ISSUE THREAD

**Issue by sgkang** [simpeg/simpeg#1266]
### Issue with current documentation:

- section titles are overlapping
- section titles are overlapping and banner for "edit on github" seems broken

![image](https://github.com/simpeg/simpeg/assets/6054371/a019fa5d-adfa-4089-aa6d-1df12d01573e)

**Comment by jcapriot** [comment]
This is already solved on main, the published docs will be fixed on the next release.
