### ISSUE TITLE
ENH: Improve how random states are handled in directives

### ISSUE THREAD

**Issue by santisoler** [simpeg/simpeg#1290]
### Proposed new feature or change:

Raised by @lheagy in #1286, we should improve how random states (random seeds) are handled in directives, specially in the beta estimator directives. We should take the opportunity to move from the legacy Numpy's RandomState (using the `numpy.random.seed()` and `numpy.random.randn()` functions) to the new Numpy's [random number generators](https://numpy.org/doc/1.26/reference/random/index.html#module-numpy.random).

**Comment by jcapriot** [comment]
Can I change this to say... "improve how random states are handled" ... everywhere? Essentially I think we need to allow everything that generators random numbers to take an `int` or a [`numpy.random.Generator`](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator)

**Comment by santisoler** [comment]
Sure! Changing on tests (#1289) might be tricky, but at some we should do it.

**Comment by jcapriot** [comment]
The issue comes up (and causes many headaches) often enough in tests that we should probably prioritize it.
