### ISSUE TITLE
ENH: Don't accept `weights` as arrays in regularizations

### ISSUE THREAD

**Issue by santisoler** [simpeg/simpeg#1325]
### Proposed new feature or change:

> [!TIP]
> **Good first issue**
> I think this a good issue for anyone willing to make their first contribution to SimPEG. If you want to tackle this, feel free to comment below expressing your will. We can always help you to sort out obstacles you might encounter in the process!

Following the conversation that @domfournier and I had in #1320, we should not accept `weights` as an array when initializing regularizations.

This would mean that the `weights` should only be a `dict` or `None`, while passing an array should raise an error. Currently, passing an array defines the private `_weights` attribute as a dictionary with a single key-value pair, where the value is the passed array and the key is `"user_weights":

https://github.com/simpeg/simpeg/blob/e3cd6ed869d5e49ab817b45f1fec037ac638a68f/SimPEG/regularization/base.py#L108-L111

## What's needed to be done

We should remove the inner `if` statement in the previous snippet, so we keep only:

```python
if weights is not None:
    self.set_weights(**weights)
```

Moreover, we could probably raise an error in case the user passed a `weights` of a type different that `None` or a `dict`. This is not strictly needed since an error should raise after passing such argument to the `self.set_weights` method or after trying to unpack the `weights` with `**weights`. But maybe we could add it to raise this error with a more verbose message.

Finally, we should update a few tests and examples that were still passing `weights` as an array. Here's a list of some of them, but not a comprehensive one:

https://github.com/simpeg/simpeg/blob/e3cd6ed869d5e49ab817b45f1fec037ac638a68f/examples/08-vrm/plot_inv_vrm_eq.py#L199

https://github.com/simpeg/simpeg/blob/e3cd6ed869d5e49ab817b45f1fec037ac638a68f/tests/base/test_regularization.py#L282-L286

https://github.com/simpeg/simpeg/blob/e3cd6ed869d5e49ab817b45f1fec037ac638a68f/tests/base/test_regularization.py#L320-L322

**Comment by domfournier** [comment]
Great. I can take this on since I made your life harder ;)

**Comment by winnerer123** [comment]
Hi! Thanks @santisoler guide me on this issue. I will start to learn from here.

**Comment by santisoler** [comment]
Thanks @winnerer123 for willing to collaborate.

@domfournier would it be fine if we let @winnerer123 tackle this issue? She's eager to collaborate more in SimPEG and I think this issue is a good start to get used to the GitHub workflow.

**Comment by domfournier** [comment]
Oh yes, 100%. I will be happy to review @winnerer123

**Comment by winnerer123** [comment]
It appears to be a very detailed issue. I just want to confirm whether the following lines of code should also be modified, as this wasn't specified in the original issue description. [https://github.com/simpeg/simpeg/blob/e3cd6ed869d5e49ab817b45f1fec037ac638a68f/SimPEG/regularization/base.py#L1669-L1672](url)

**Comment by santisoler** [comment]
Nice catch @winnerer123! Yes, those lines should also be changed since `WeightedLeastSquares`'s constructor (the `__init__()` method) will broadcast the passed `weights` to all regularization objects within it.

**Comment by YingHuuu** [comment]
Thanks!  I've made the changes within my understanding. The files involved are listed below：
```
#	modified:   SimPEG/regularization/base.py
#	modified:   examples/01-maps/plot_sumMap.py
#	modified:   examples/08-vrm/plot_inv_vrm_eq.py
#	modified:   examples/10-pgi/plot_inv_1_PGI_Linear_1D_joint_WithRelationships.py
#	modified:   tests/base/test_regularization.py
#	modified:   tests/em/vrm/test_vrminv.py
```
If I've missed anything or made an error, please let me know.

**Comment by santisoler** [comment]
Thanks @YingHuuu! I'll take a look at the PR you opened and provide some feedback shortly.
