### ISSUE TITLE
Unintended behaviour of `SimPEG.utils.coterminal`?

### ISSUE THREAD

**Issue by santisoler** [simpeg/simpeg#1333]
## Question

If we pass angles equal to $-\pi$ or $\pi$ we'll get $\pi$ or $-\pi$, respectively. This means that the function will return floats with different signs for this pair of coterminal angles ($-\pi$ and $\pi$ are coterminal angles).

For example:

```python
import numpy as np
from SimPEG.utils import coterminal

angles = np.array([-np.pi, np.pi])
print(coterminal(angles))
```
```
[ 3.14159265 -3.14159265]
```

This may cause issues when trying to regularize such angles: if one cell has a vector with angle $-\pi$, and the next one has an angle of $\pi$, then a smoothness regularization on angles will introduce a penalty (because the difference between these two floats is non-zero), while it shouldn't because there's no change in angles between the two cells.

**Is this the intended behaviour?**

## Idea

Wouldn't be better if the function returns angles in the interval $(-\pi, \pi]$ ?
In that case, passing $-\pi$ and $\pi$ would return the same value for both of them. Therefore it should have the following behaviour for the previous example:

```python
import numpy as np
from SimPEG.utils import coterminal

angles = np.array([-np.pi, np.pi])
print(coterminal(angles))
```
```
[ 3.14159265 3.14159265]
```

## If we decide to go forward with this

If we want to change the behaviour of this function I think we should:

1. Modify the implementation of `SimPEG.utils.coterminal` accordingly.
2. Improve the docstrings to reflect the new change. Probably the $\gamma$ angle could be defined as belonging to $(-\pi, \pi]$.
3. Add test functions that check the function under these circumstances:
    - Passing $-\pi$, $\pi$, $3\pi$, $-3\pi$ should return the same angle: $\pi$
    - Are angles within the interval not being modified?
    - Are angles outisde the interval being correctly brought to that interval?

**Comment by santisoler** [comment]
cc @domfournier

**Comment by domfournier** [comment]
Hmm ok clearly the sign flip is not good. The idea of this function is to always return the complementary angle, exactly for the reason you've mentioned (i.e. two angles that are close to each other but in different quadrants). Coterminal is called after computing the gradient (normalized difference) between the angle values. But yea, the negative is no good. We should fix it directly on #1299

**Comment by jcapriot** [comment]
Nice little catch, Fortunately I don't think it was causing any issues in the way that we were using it, as we calculated co-terminal angles AFTER doing a difference (not before) so the sign flip wouldn't have mattered.

**Comment by domfournier** [comment]
But it actually does, just by visual inspection of the example/03-magnetic/plot_inv_mag_MVI_Sparse_TreeMesh

**Comment by jcapriot** [comment]
That improvement just seems odd to me...
for reference here are the three methods that we've been talking about:
![image](https://github.com/simpeg/simpeg/assets/16258927/36468753-c78b-447f-b9e2-178b8f291f5b)

**Comment by jcapriot** [comment]
The "modulus" is the most correct way of doing this, the current method will over-do angle differences larger than $2\pi$, but that shouldn't happen with how the inversion will reset angles larger than that. The proposed method is incorrect for angles beyond $\pi$.

**Comment by jcapriot** [comment]
Also, scary behavior here is that the `coterminal` calculation actually modifies it's argument in-place.

**Comment by domfournier** [comment]
Agree on the modulus, although angle > pi would never happen in the inversion since we always reproject on [-pi, pi].

**Comment by jcapriot** [comment]
The angles themselves are always projected onto the interval [-$\pi,\pi$], but it’s certainly possible the difference of two angles would then be on the interval of $[-2\pi,2\pi]$

**Comment by domfournier** [comment]
True
