### ISSUE TITLE
MAINT: Rename Spontaneous Potential module to Self Potential 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#1408]
I propose that we rename the `spontaneous_potential` module to `self_potential`. Although both names are used to indicate the same phenomenon, "Self Potential" is used more broadly to describe the geophysical survey (spontaneous potential is used primarily in the context of well logging). 

If we look at formative references on the topic, for example [Revil and Jardani](https://www.google.ca/books/edition/The_Self_Potential_Method/HzTdAEJdRysC?hl=en&gbpv=1&printsec=frontcover) and [Telford](https://books.google.ca/books?redir_esc=y&id=oRP5fZYjhXMC&q=self+potential#v=snippet&q=self%20potential&f=false), they also refer to Self Potential 

Since this is a relatively recent addition to SimPEG, making the change sooner than later shouldn't be too painful, so I have put this as a candidate for the 0.22 milestone

**Comment by lheagy** [comment]
cc @sgkang: I would be curious to get your thoughts on this as you were the first to implement it in SimPEG!

**Comment by craigmillernz** [comment]
I agree that "self potential" is the more common usage - in volcanology at least.

**Comment by jcapriot** [comment]
I have no real preference either way, but my original thought in #1211 was that since the word `self` has its own importance in Python, it would be fine to stick to `spontaneous`

**Comment by lheagy** [comment]
Thanks for sharing the initial motivation Joe, I can see the motivation with `self`. Here, I would still advocate that we prioritize following the geophysics community and go with the more common name of `self_potential`, as it is the description most used in the literature we are connected with. 

(and as a side note, I don't find `spontaneous` as fitting of a description, when you look at the definition, there is an emphasis on something being "sudden" which may or may not be the case when talking about the potentials being generated)
