### ISSUE TITLE
BUG: Pole-pole DCR survey

### ISSUE THREAD

**Issue by anna1963** [simpeg/simpeg#1432]
### Describe the issue:

I'm trying to build a pole-pole borehole 2.5D DCR survey. And I found that survey_type is always "dipole-dipole" even if I used dc.receivers.Pole() to build the receiver object.

If I set survey.survey_type = 'pole-pole' and store the data object into data.obs using write_dcip2d_ubc, and then load the data object using read_dcip2d_ubc. The data_obj.survey.survey_type is always 'dipole-dipole'.

### Reproducible code example:

```python
start_depth = 2.
T_x = -7.
R_x = 7.
station_separation = 1.0
num_e_per_well = 32

source_list = []
m_loc_R = []

#The M locations in the receriver well (R well)
for k in range(num_e_per_well):
  m_loc_R.append([R_x, -1*(start_depth+station_separation*(num_e_per_well-k-1))])

for i in range(num_e_per_well):
  a_loc = np.array([T_x, -1*(start_depth+station_separation*(num_e_per_well-i-1))])
  m_loc = m_loc_R.copy()
  for j in range(num_e_per_well):
    if j!=i:
      m_loc.append([T_x,-1*(start_depth+station_separation*(num_e_per_well-j-1))])
  receivers = dc.receivers.Pole(locations=np.array(m_loc))
  source = dc.sources.Pole(
        location=a_loc,
        receiver_list=[receivers]
    )
  source_list.append(source)

survey = dc.Survey(source_list=source_list)

print(survey.survey_type)
#Return 'dipole-dipole'

survey.survey_type = 'pole-pole'

print(survey.survey_type)
#Return 'pole-pole'

data_obj = data.Data(survey, dobs=dobs, standard_deviation=std)
fname = dir_path + "/dc_data.obs"
write_dcip2d_ubc(fname, data_obj, "volt", "dobs")

print(survey.survey_type)
#Return 'pole-pole'

data_filename =  dir_path + "/dc_data.obs"
dc_data = read_dcip2d_ubc(data_filename, "volt", "general")
survey = dc_data.survey

print(survey.survey_type)
#Return 'dipole-dipole'
```

### Error message:

```shell
N/A
```

### Runtime information:

The issue occurs in 0.19 and 0.21.1

### Context for the issue:

Both survey.survey_type = 'pole-pole' and survey.survey_type = 'dipole-dipole' give the same sythnetic measurements when using dc.receivers.Pole and dc.sources.Pole to build the source_list, so I think the survey type of the survey object doesn't affect the forward simulation part.

**Comment by jcapriot** [comment]
Yep, the `survey_type` argument doesn’t have any bearing on the simulation! It’s a leftover of some old conventions.

**Comment by santisoler** [comment]
Should we also remove the `survey_type` in the spectral IP survey class?

https://github.com/simpeg/simpeg/blob/c12f51efe1afb52ad9cf6ffe1e357b85c7a51c0e/simpeg/electromagnetics/static/spectral_induced_polarization/survey.py#L17-L18

**Comment by jcapriot** [comment]
Yeah, it doesn't actually do anything.
