### ISSUE TITLE
BUG: small typo in 0.21.0 release notes

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#1433]
### Describe the issue:

It looks like the rst for the link pointing to the choclo docs didn't quite render properly
![image](https://github.com/simpeg/simpeg/assets/6361812/dbdbabf7-6e84-4586-b3a8-2cb49f129b11)

### Reproducible code example:

```python
No issue in code, just in docs but this section is required by the issue template (maybe should be optional??)
```

### Runtime information:

simpeg 0.20.0

**Comment by santisoler** [comment]
Nice catch! Thanks @lheagy!
