### ISSUE TITLE
DOC: Update API reference to use `simpeg` instead of `SimPEG`?

### ISSUE THREAD

**Issue by santisoler** [simpeg/simpeg#1437]
### Issue with current documentation:

After #1430 was merged, we deprecated the `SimPEG` package in favor for its pep8 compliant name: `simpeg`.

I noticed that we haven't applied any changes to the API reference, and `SimPEG` is still being used there. See for example: https://github.com/simpeg/simpeg/tree/main/docs/content/api

### Idea or request for content:

Shall we update the API reference to use `simpeg` instead?

**Comment by santisoler** [comment]
cc @jcapriot

**Comment by jcapriot** [comment]
Yeah, should change them all to be `simpeg` (and make sure we update the `automodule` calls in them too.
