### ISSUE TITLE
Full Anisotropy

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#146]
_From @lheagy on June 19, 2015 18:41_

At the moment, MeSigmaIDeriv, MfRhoDeriv, MfRhoDeriv will not take fully anisotropic media - this actually needs to be taken care of inside of getFaceInnerProductDeriv and getEdgeInnerProductDeriv within simpeg, but I am creating the issue here too so it is documented that the fully anisotropic inversion won't be working yet

_Copied from original issue: simpeg/simpegem#22_

**Comment by lheagy** [comment]
This requires simpeg/discretize#52 to be addressed (inner products with invMat=True)

**Comment by jcapriot** [comment]
#1237 Should implement most of these. Unfortunately I don't believe we will be able to support Inverse matrix derivatives on these types of meshes due to a solver being required (and also the actual `A` matrix would be a dense matrix in these cases.)
