### ISSUE TITLE
General testing framework for problems.

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#15]
This should test derivatives of all parts of your problem. Makes writing and testing code easier for research applications.

---------------------------------------
- Bitbucket: https://bitbucket.org/rcockett/simpeg/issue/13
- Originally Reported By: [ ](http://bitbucket.org/rowanc1)
- Originally Created At: 2013-10-25T00:20:37.324

**Comment by lheagy** [comment]
can we close this?

**Comment by rowanc1** [comment]
yeah
