### ISSUE TITLE
MNT: Pass a `random_seed` to `check_derivative` in tests

### ISSUE THREAD

**Issue by santisoler** [simpeg/simpeg#1546]
**Description of the maintenance task**

Quite a bunch of tests rely on `discretize`'s function `check_derivative` to assert the derivative of a given callable. In https://github.com/simpeg/discretize/pull/360 the `random_seed` argument was added to the function.

After we get a new release of discretize that includes this new feature, we should update the tests here in SimPEG and ensure that they all pass a `random_seed` when calling the function. This way we will ensure that tests run under the same conditions every time they are run.

**Comment by jcapriot** [comment]
Fixed in #1558 and #1560
