### ISSUE TITLE
Fictitious Source Test for Fields

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#156]
_From @lheagy on August 7, 2015 15:14_

In test_FDEM_forward.py, I have added a fictitious source test. Right now, I only compare the fluxes (which pass), but comparing the fields fails... I think it has to do with the way I am calculating the error (lines 398- 400) because in 2 cases, the fields are actually calculated from a flux. 

If you change "testType" in line 16 to 'Field', it will test against the fields. 

Any ideas? Possibly something to do with aveE2CCV??

(only on dev branch at the moment) 

_Copied from original issue: simpeg/simpegem#32_

**Comment by lheagy** [comment]
Testing has significantly improved on the EM portion of the code since publishing the EM paper (#622)
