### ISSUE TITLE
Source from wire path

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#157]
_From @lheagy on September 13, 2015 20:27_

be able to provide an open or closed wirepath and generate src term

_Copied from original issue: simpeg/simpegem#33_

**Comment by grosenkj** [comment]
This would be very useful.

@sgkang Can you help implementing this one?

**Comment by sgkang** [comment]
@grosenkj  Sure. At the moment, I could make wire path defined on the edges, so EB formulation is fine. But, for HJ formulation needs some thoughts. This is on my radar, but it just depends how fast we want to have this capability.

**Comment by lheagy** [comment]
@sgkang: you mentioned that you have been working on this. Do you have it on a branch somewhere? I have some code that does h-j formulation and needs to be generalized a bit, but isn't far off: https://github.com/lheagy/casingResearch/blob/master/casingSimulations/sources.py

**Comment by sgkang** [comment]
@lheagy That code only works for E-B formulation. We can expand for H-J formulation. It is currently in em/linesource branch

**Comment by lheagy** [comment]
this is related to #767. I will close this in favour of #767.
