### ISSUE TITLE
Src integration

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#158]
_From @lheagy on October 3, 2015 21:23_

Adapted rhs and source terms so it is clear where we are performing integration on the source vectors. For the E-B formulation, we integrate s_e, for the H-J formulation, we integrate s_m. See docs in FDEM.py. 

_Copied from original issue: simpeg/simpegem/pull/34_

**Comment by rowanc1** [comment]
_From @lheagy on October 3, 2015 21:24_

@sgkang : can you have a look when you have some time??

**Comment by rowanc1** [comment]
_From @sgkang on October 4, 2015 23:4_

Hi @lheagy 

That looks good to me on most cases. And now it's more explicit and clear. 
But, I just think about implementation of Christoph's line current code. 
In that case, this functions outputs Me*js, which integrated currents. 
Thus, we do not have to multiply Me again for this case. Probably, we can put an option ... for this.
Think about this, and we can get together next week.

**Comment by rowanc1** [comment]
_From @lheagy on October 5, 2015 16:1_

Thanks Seogi! I moved the integration so that it takes place inside of the definition of the source (instead of in the problem). This should make it easier to trigger on / off (I also realized it is also important to be able to turn off for primary-secondary approaches).

**Comment by lheagy** [comment]
the remaining tasks of adding a line source are discussed in #157
