### ISSUE TITLE
pymatsolver on travis

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#162]
to speed up solves on travis

**Comment by bsmithyman** [comment]
This would be great, and it's also essentially the environment my JupyterHub container runs, so I'd be happy to help. I've had mixed luck getting it to work on Linux, though.

**Comment by bsmithyman** [comment]
Regarding this: I'm able to compile on my Ubuntu-based infrastructure, which is roughly what Travis is running, but by default it's trying to link in the MPI version of MUMPS. Do we have an idea as to which packages should (or should not) be installed to make sure that the serial MUMPS version is linked when building pymatsolver.MumpsSolver?

**Comment by lheagy** [comment]
@grosenkj figured a lot of this out a couple months ago to get serial mumps working, he may be able to give us a hand!?
