### ISSUE TITLE
Renaming smoothModel in the Tikhonov regularization.

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#168]
This is very confusing name for using to control the use of m_ref in the smoothness weights.
Can this be change to mrefInWsmooth or something more descriptive of that this flag intended use.

**Comment by sgkang** [comment]
True. That was mostly following UBC terminology. We need to put some documentation about that as well. I like mrefInWsmooth

**Comment by lheagy** [comment]
This one got me again today! is everyone agreed on mrefInSmooth ? we can add this regularization changes in pr #254

**Comment by grosenkj** [comment]
I agree, I like mrefInSmooth. Thanks for addressing this.
