### ISSUE TITLE
use CNAME support to put docs only on docs.simpeg.xyz

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#180]
So that it is not both on rtd and docs.simpeg.xyz

http://read-the-docs.readthedocs.org/en/latest/alternate_domains.html#cname-support

**Comment by rowanc1** [comment]
This is actually already what we are doing! There doesn't seem to be a way to automatically redirect from simpeg.rtfd.org to docs.simpeg.xyz.

There is a possibility of doing this on the javascript side of things, but I am not sure if it is a good idea. Both of them show up in google currently (which could be annoying, but isn't that bad as they are exactly the same...?).

**Comment by bsmithyman** [comment]
There is a way to do this with HTML that doesn't use JavaScript. I'm just not sure if it's possible to add meta tags on rtfd.org pages.
```html
<meta http-equiv="refresh" content="0; url=http://docs.simpeg.xyz" />
```

**Comment by rowanc1** [comment]
I think that this should only be included on the RTFD site, meaning a
conditional on the domain name (so still JavaScript?). We could
investigate, but I am not sure how big a deal this is...? @lheagy can you
explain?

**Comment by bsmithyman** [comment]
Yeah, fair enough. I'm not much of a JavaScript programmer, but something like a conditional on `window.location.href` should work. Alternatively, you could do something like the following at the top of the page:
```html
<div class="hiddenOnXYZ">
  To see these documents directly on the SimPEG site,
  <a href="http://docs.simpeg.xyz">click here</a>.
</div>
```
then, put the following in the supplemental CSS for the .xyz site:
```css
.hiddenOnXYZ {
    display: none
}
```

**Comment by lheagy** [comment]
I don't know if we can play the same game with rtd, but for my personal site, I use githubio, and I set up an A record (https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/). Then it automatically redirects from the github.io version to the one I purchased (it is a bit touchy though... it worked when I first set it up, and now seem not to)

**Comment by rowanc1** [comment]
We can put this on the main page?
```
if(window.location.hostname.indexOf('readthedocs') !== -1){
    window.location = 'http://docs.simpeg.xyz';
}
```

**Comment by bsmithyman** [comment]
@rowanc1 that works if I plug it into the JavaScript console while sitting on the page. So yeah, I think it functions fine.
