### ISSUE TITLE
Include data uncertainties in survey.Data

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#184]
It would be beneficial to be able to store uncertainties within the data class. This would make it easier to maintain the uncertainties and ensure that they match the data. 

Maybe have 
```python
data.uncert[src,rx]
```

**Comment by lheagy** [comment]
and would make it easier to assign custom uncertainties depending on src / rx characteristics

**Comment by lheagy** [comment]
uncertainty could be a class:
properties: std, floor
method: eval

**Comment by grosenkj** [comment]
Moved to issue #202
