### ISSUE TITLE
SimPEG import error

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#185]
I updated to the current version of master. 

```python
import SimPEG 
```
Fails with an error
```python
ImportError: No module named TreeUtils
```
Looking at the code, I found TreeUtils.pyx. Quick googling and I found that .pyx are Cython related files. I ran 
```python
import pyximport
pyximport.install()
```
and import SimPEG works without an ImportError. 

The additional Cython import should be added to the SimPEG code base.

**Comment by rowanc1** [comment]
There is a pull request for this. That will fix the no import symptoms. But you should really be building the extensions ahead of time:

```
python setup.py build_ext --inplace
```

**Comment by grosenkj** [comment]
Imports without problems after building the extensions.
