### ISSUE TITLE
Regularization and Mappings

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#188]
- Base regularization should not require a mesh. If we want to regularize a parameterized model, then the concept of a mesh may not make sense (ie. regularizing a circle map... which is overdetermined, so you don't need to, but same idea)

- need to be able to regularize only on the active model (including derivatives). We could build a mesh mapping? (ie. sub-sample the operators using the indices of the active cells) 

- also call is something different in regularization? (it is confusing that it performs a different role in the forward model than the regularization)

**Comment by bsmithyman** [comment]
Might be useful to apply #189; this is necessary to have mappings when the model space is not on cell centres.

**Comment by lheagy** [comment]
Active models have been taken care of in #254. On further thought, I am fine with BaseRegularization taking a mesh, it will in the vast majority of cases... if we want a meshless reg, we can write that as a separate class. Any objections if I close this?

**Comment by lheagy** [comment]
This will close with #277
