### ISSUE TITLE
Merging DC, PF, and MT

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#195]
@fourndo, @sgkang, @grosenkj, @lheagy I would like to merge the repositories for DC, PF, and MT into the base SimPEG branch next week. I am planning to do some of this with @fourndo on Monday afternoon, with regard to PF and getting some examples and data in the repository.

I will be rearranging some of the documentation to focus more on the applications and examples rather than underlying framework code.

Updates:
 - SimPEG now works with a PIP install
 - We have new examples: http://docs.simpeg.xyz/en/latest/api_Examples.html

**Comment by grosenkj** [comment]
@rowanc1 I like this idea. I have done a bit of work on the the MT side of things. Next week should work fine for me. When would you like to tackle this?

**Comment by rowanc1** [comment]
MT is merged into mt/dev!

**Comment by rowanc1** [comment]
#211 will merge this into dev. Then we can test the things out, and push to master and update pip.

**Comment by lheagy** [comment]
DC and MT were merged in #265, PF to come!?

**Comment by rowanc1** [comment]
Closing in favour of #275.
