### ISSUE TITLE
Regularization & Topography

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#199]
Talking with @fourndo today about adding a new regularization type that does not depend on the cell size, just is a +/- 1 stencil, that is the same size as the number of cells. Fwd difference and bwd difference right at the end, this would mean that it is square, and we can zero out the rows that are air cells quite easily.

This works better than some of the active maps that we have at the moment, where there are errors in the deriv due to the inactive cell additions.

@lheagy any suggestions on the naming for this?

**Comment by lheagy** [comment]
We started working on the active cell regularization issue a bit before christmas on the ActiveCellReg branch (PR #191) by using a projection matrix to pull out only the active cells. This still uses cell sizes though. For a +/- 1 stencil maybe "SimpleDiff" or "SimpleStencil" ("UniformStencil"?). I sort of like "SimpleStencil"

Will this be a separate type of regularization? or just a kwarg?

**Comment by rowanc1** [comment]
This is started in #254.

**Comment by lheagy** [comment]
This will close with #289

**Comment by lheagy** [comment]
This closed with #289
