### ISSUE TITLE
Using the DataClass

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#202]
We should be more about the data class.

```
from SimPEG import DC
dobs = DC.DCData.fromFile('myData.dat')
survey = dobs.survey
dobs.plotSection()
dobs.std[5] = notTrustWorthy
```

The Std should live with the data specifically (not the survey). The plotting functions for the data should be associated with the data class.

**Comment by lheagy** [comment]
also `dobs.eps` or `dobs.floor` and maybe `dobs.flag` (ie the flag would be `notTrustWorth` and `std` a number

**Comment by grosenkj** [comment]
@lheagy, I like your idea. The idea of having the `notTrustWorth` flag could come in handy. It could be an independent flag or be addressed by setting `std` to ``NaN` or `False` to indicate it's untrustworthyness. I could vote either way, but at the end of the day it won't matter how it will be implemented but keeping things consistent will be nice.

**Comment by rowanc1** [comment]
Data is created by:

```python
d = Data(survey, v=vectorData, std=stdVector)
# You can access the data by source and receiver pairs:
assert isinstance(d[Src,Rx], np.ndarray)
# it will also have a std property
d.std[Src, Rx]
# which is really just another data object
d.floor # is the epsilon value used to not go crazy in the regularization.
#for any of these you can call the 
Utils.mkvc(d)
#to get back to a vector.
```

```python
dobs[Src,Rx] == np.ndarray
dobs.std[Src, Rx] == np.ndarray
dobs.floor[Src, Rx] == np.ndarray
```

**Comment by lheagy** [comment]
Wd should not be making assumptions about the noise model - it should ask the data class what the uncertainties are and simply do `Wd = 1/data.uncertainty`

Instead of calling the uncertainty percentage `std` (which is protected by numpy and generally confusing) how about having uncertainty as a simple class that is then attached to the data class
(Base uncertainty class) 
- `percentage` (or maybe `standard_deviation`) 
- `floor` 
- `eval` : `return self.standard_deviation * np.absolute(data) + self.floor`

both `percentage` and `floor` have default values 

(I don't really like `percentage`, maybe `standard_deviation` is better)

**Comment by grosenkj** [comment]
Very similar to issue #184.

I support this change, I be nice to have better access to the uncertainties via the `Data` class.

**Comment by lheagy** [comment]
This is closely related to the changes being made in #562. I have sketched out a first pass implementation below. It lives on the `ref/simulation` branch at the moment. Some important changes:
- `dobs` is a vector attached to the object (maybe we make it immutable?). This is the anchor point and is the true data, as a vector. Around it, we build functionality for accessing the data in a reasonable manner 
- the `_dataDict` no longer stores the data, it stores the indices in dobs associated with the source, receiver pair
- `standard_deviation` and `floor` are properties of the Data class (and will be removed from the survey) 
- we should be able to create data objects for simulations which don't have the concept of a source / receiver (eg. the linear problem) - in which case, all you really use is `dobs`, and the uncertainties

@rowanc1, @grosenkj: I am curious to hear your thoughts  

```python
import properties
from SimPEG.NewSurvey import BaseSurvey


class Data(properties.HasProperties):
    """
    Fancy data storage by Src and Rx
    """

    dobs = properties.Array(
        "observed data",
        shape=('*',),
        required=True
    )

    standard_deviation = properties.Float(
        "standard deviation of the data",
        min=0.0
    )

    noise_floor = properties.Float(
        "noise floor of the data",
        min=0.0
    )

    # TODO: stick a validator on this so that you either set noise floor and standard deviation or uncertainty. or maybe this is just a gettable `@property`. 
    uncertainty = properties.Array(
        "data uncertainties",
        shape=('*',)
    )

    survey = properties.Instance(
        "a SimPEG survey object",
        BaseSurvey
    )

    uid = properties.Uuid("unique ID for the data")

    _data_dict = properties.Instance(
        "data dictionary so data can be accessed by [src, rx]. "
        "This stores the indicies in the data vector corresponding "
        "to each source receiver pair",
        dict,
    )

    def __init__(self, **kwargs):
        super(Data, self).__init__(**kwargs)
            
    @properties.observer('survey')
    def _create_data_dict(self, change):
        survey = change['value']
        self._dataDict = {}
        
        # create an empty dict associated with each source
        for src in survey.srcList:
            self._dataDict[src] = {}
        
        # loop over sources and find the associated data indices
        indBot, indTop = 0, 0
        for src in self.survey.srcList:
            for rx in src.rxList:
                indTop += rx.nD
                self[src, rx] = np.arange(indBot, indTop)
                indBot += rx.nD     

    @property
    def nD(self):
        return len(dobs)

    def _ensureCorrectKey(self, key):
        if type(key) is tuplsee:
            if len(key) is not 2:
                raise KeyError('Key must be [Src, Rx]')
            if key[0] not in self.survey.srcList:
                raise KeyError('Src Key must be a source in the survey.')
            if key[1] not in key[0].rxList:
                raise KeyError('Rx Key must be a receiver for the source.')
            return key
        
        # TODO: I think this can go
        elif isinstance(key, self.survey.srcPair):
            if key not in self.survey.srcList:
                raise KeyError('Key must be a source in the survey.')
            return key, None
        
        else:
            raise KeyError('Key must be [Src] or [Src,Rx]')

    def __getitem__(self, key):
        src, rx = self._ensureCorrectKey(key)
        if rx is not None:
            if rx not in self._dataDict[src]:
                raise Exception('Data for receiver has not yet been set.')
            return self.dobs[self._dataDict[src][rx]]
#             return self._dataDict[src][rx]

        return np.concatenate([self.obs[self._dataDict[src, rx]] for rx in src.rxList])
```

**Comment by grosenkj** [comment]
I like these changes. I think that the old `Survey` was to broad in scope, specially when used with `Data` classes. 

My main comment regarding the above sketch are on the `standard_deviation`, `floor` and `uncertainties`. I am all for them being included but I think that all should be a array of the same length as dobs. That is how approached it in #515, where I implemented the `standard_deviation` and `floor` as `BaseData` properties in the `Data`. This way everything slices with the same `[src, rx]` pairs, which makes plotting and interacting with the `standard_deviation` and `floor` easier. I am not sure if the `BaseData` route is the way to go, but being able to index the `d_observed`, `standard_deviation`, `floor` and `uncertainty` in the same manner is important.

As well, I  think that explicitly having to declare/set how the uncertainties are calculated is important. They are such a critical part of the inversion, it that should be enforced in the code. I would support requiring them to be set by the user and have `data.validate()` fail they are not. 

Look forward to discussing this further.

**Comment by lheagy** [comment]
Thanks @grosenkj, I have since updated this on #672. You can input a scalar for the standard deviation and noise floor, and these will be cast to arrays of the same size as the number of data.

**Comment by lheagy** [comment]
In relation to the simulation refactor broadly outlined in #562, I have been playing with ideas for re-factoring the data class. 

## Constraints
The data class should keep track of:
- the observed data `dobs`, 
- the percent error `standard_deviation` 
- and a floor `noise_floor`. 

it should also 
- know how to compute the `uncertainty` based on the standard deviation and noise floor
- be able to set and get the datum and uncertainty based on the source and receiver

## Initial implementation
Originally, we had some fancy indexing which let you index into a `data` object to get a datum by source and receiver. You would instantiate a `Data` object by providing a survey and a vector of observed data. The class then had a `__getitem__` method which could accept sources and receivers and return you a datum. 

```
# set data
data[source, receiver] = x
```

**Challenges**
- there is no simple solution for also setting and getting `standard_deviation` and `noise_floor` (there is only one `__getitem__` on the class
- we need to easily be able to change between setting and getting data / uncertainties by survey parameters and treating `dobs`, `standard_deviation`, and `noise_floor`, as simple numpy-vectors
- for a new user: this is not particularly pythonic and is a bit magical 

## Suggested implementation
I suggest we simplify the data class and:
- remove the `__getitem__` behaviour in favour of a method `indices_by_source_receiver()` (or something like that), that will return the indices (or slice) that can be used to index into a numpy array
- that `dobs`, `standard_deviation` and `noise_floor` that are simply numpy arrays

So a sketch like

```python
class Data(properties.HasProperties):

    dobs = properties.Array("observed data")
    standard_deviation = properties.Array( "standard deviation of the data")
    noise_floor = properties.Array("noise floor of the data")
    survey = properties.Instance("a SimPEG survey object", BaseSurvey)
    _uid = properties.Uuid("unique ID for the data")

    def __init__(self, survey=None, dobs=None, **kwargs):
        # instantiate the class

    @property
    def uncertainty(self):
        # compute uncertainty from dobs, standard_deviation, noise_floor

    @property
    def _data_dict(self):
        # dictionary that is used to look up an index based on sources / receivers

    def indices_by_source_receiver(self, sources, receivers):
        # use the data dict to look up the indices, return a slice
```

So for example, to set a datum by sources/receivers
```
# set data
inds = data.indices_by_survey(source, receiver)
data.dobs[inds] = x
```

**Pros**
- simplifies the `Data` class code
- likely more transparent to the user
- (can maintain backwards compatibility for now)

**Cons**
- one more line of code that the user has to write
- will change throughout forward problem implementations (which we are refactoring anyways)

**Comment by rowanc1** [comment]
Thanks for the writeup @lheagy, very clear. Also thanks for the discussion in the Python channel in https://slack.simpeg.com with @fwkoch - always really interesting to see what magic we _could_ do.

However, I really like the reduction of magic in this proposed implementation. I think the extra line that the user has to type ends up making the whole piece a lot more transparent.

Probably there would be some validation that looks to the `survey.num_data` to ensure that the arrays are the correct length!

**Comment by micmitch** [comment]
Agreed. Changes proposed in this sketch sound good to me!

**Comment by lheagy** [comment]
I have a first pass implementation here: https://github.com/simpeg/simpeg/pull/786/files#diff-355ed1cae865dcda48f9c49eb8406160

**Comment by lheagy** [comment]
The implementation I have currently working on the `simulation` branch still keeps the functionality of treating the data object like an array that can be indexed by source receiver, but also stores the data as a vector `dobs` so that it is a bit more transparent. As I was looking through the code that runs simulations, being able to assign and sort data by source receiver is pretty core functionality, so rather than remove it, we now have dual use. Does that seem reasonable to folks?

**Comment by lheagy** [comment]
We should look into using xarray for the data (rather than our own source / receiver indexing dictionary)

**Comment by lheagy** [comment]
This will close with #786.
