### ISSUE TITLE
Analytic solution for a sphere in a halfspace in a plane wave field.

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#207]
It would be great to have an analytic solution fro a sphere in a half space in a plane wave fields in SimPEG.

**Comment by grosenkj** [comment]
Would nice to get this going...

**Comment by lheagy** [comment]
@grosenkj, I think this is more within the scope of [geoana](https://github.com/simpeg/geoana). Do you want to open up an issue over there?

**Comment by lheagy** [comment]
This issue was moved to simpeg/geoana#7
