### ISSUE TITLE
Identitymap requires mesh?

### ISSUE THREAD

**Issue by sgkang** [simpeg/simpeg#210]
While I was playing with Global problem, I recognized that my model is log conductivity under the topography. And I am populating that to submesh as a full conductivity (both subsurface and air). 

For a global problem,  I need some mapping by construction, but current IdentityMap does not allow me to do that. I ended up inheriting IdentitiyMap (see below), and generate my own. Philosophically, I prefer Identitymap without mesh. What do you guys think? @rowanc1 @lheagy @grosenkj
`
class IdentityMapXXX(Maps.IdentityMap):
    nCactive = None
    def __init__(self, mesh, **kwargs):
        Maps.IdentityMap.__init__(self, mesh, **kwargs)
    
    @property
    def nP(self):
        """
            :rtype: int
            :return: number of parameters in the model
        """
        if self.nCactive is None:
            raise Exception('Set nCactive')            
        return self.nCactive

    @property
    def shape(self):
        """
            The default shape is (mesh.nC, nP).

            :rtype: (int,int)
            :return: shape of the operator as a tuple
        """
        return (self.nP, self.nP)
`

**Comment by rowanc1** [comment]
This is going to be addressed in Pull request #191.

There are still a few concerns before we pull that in. But it is very close.

Do you want to test that branch out?

**Comment by sgkang** [comment]
Thanks @rowanc1 sure. I may merge that branch to Global, and test it.
