### ISSUE TITLE
Waveform in BaseTimeProblem?

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#215]
I do not think that this should be in the base class. Where is this used?

![image](https://cloud.githubusercontent.com/assets/913249/12666740/44c43094-c5f8-11e5-8e61-60ac90934581.png)

**Comment by sgkang** [comment]
This is for TEM problem. I haven't thought about flow problem.
Sounds good to move this to BaseTDEM problem then.


2016-01-28 19:50 GMT-08:00 Rowan Cockett <notifications@github.com>:

**Comment by rowanc1** [comment]
See #216
