### ISSUE TITLE
Including Data?

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#219]
I have been looking at @fourndo's work on the PF repo, there is a lot of data included there. I think that including this in the base simpeg repo might be a good idea. I know that scikit learn has sample data sets that they include to get people up and going in their repos, but it is not included in the initial installation of the library (i.e. through pip).

Perhaps we can do something similar? Might also be worth looking into `git lfs`?

**Comment by fourndo** [comment]
For both research and applied work, I think we should just build up the library as we get new data format. I have implemented the IO for dc 2d too, so I can add to it.

**Comment by lheagy** [comment]
that would be nice. We will need to put some docs in place, and make it easy to specify different licensing to the data sets

**Comment by lheagy** [comment]
I think we have resolved this by starting the [simpeg-research org](https://github.com/simpeg-research) and the [geoscixyz-data org](https://github.com/geoscixyz-data)
