### ISSUE TITLE
Problem with MeshIO update

### ISSUE THREAD

**Issue by fourndo** [simpeg/simpeg#220]
Getting this new error message when trying to load a UBC tensor mesh:

**  File "\SimPEG\simpeg\SimPEG\Mesh\MeshIO.py", line 46, in readUBC
    tensMsh = TensorMesh([h1,h2,h3],x0)
TypeError: object() takes no parameters**

What's up with that?

**Comment by rowanc1** [comment]
You are probably accessing through MeshIO directly, it is designed to work
as a mixin through the TensorMesh class.

TensorMesh.readUBC

Does that work?

**Comment by fourndo** [comment]
Yep got it. Thanks a lot.
