### ISSUE TITLE
testing on docs

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#221]
we can add the doc build to the travis testing
- [ ] test html build
- [ ] test pdf build
- [ ] test links (check that any sites we point to actually exist)

**Comment by lheagy** [comment]
The testing is on the docs branch. It looks like we have let a number of things go un-checked for a while, so some cleanup will be needed

**Comment by rowanc1** [comment]
Good call on the testing.

**Comment by lheagy** [comment]
This is being taken care of on #324

**Comment by lheagy** [comment]
This closed with #324
