### ISSUE TITLE
Branch Naming Convention

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#230]
Can we name the branches with descriptive names rather than the (initial) author of the branch?

```python
feat/optimization # optimization feature
bug/optBounds # fixes a bug in the optimization bounds
example/dcresistivity # new dc resistivity example
mesh/octree_interpolation # mesh updates for octree interpolation
docs/reorg # reorganize the docs
```

Thoughts?
@fourndo @sgkang @lheagy @micmitch 

I think this would be helpful especially with the number of branches currently!

**Comment by lheagy** [comment]
agreed! also specifics to forward problems as well
```
em/...
mt/...
dc/...
```

**Comment by fourndo** [comment]
ok will implement that looking forward. Probably a good idea to segment the feature into individual branches. Can I still keep a personal development branch?

**Comment by rowanc1** [comment]
`personal/dom`? :)
I am fine with that, and we can always branch off of that to create something that will eventually merge into the base etc.

**Comment by lheagy** [comment]
what do we want to call clean-up / housekeeping branches?
`cleanup/utils` ?

**Comment by rowanc1** [comment]
"ref/utils" for refactor?
