### ISSUE TITLE
Creative Commons the SimPEG Docs?

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#237]
Should we replace the copyright footer in the SimPEG docs with a CC-BY-4.0 license statement? 
https://creativecommons.org/licenses/by/4.0/

**Comment by lheagy** [comment]
same on the website??

**Comment by lheagy** [comment]
thoughts @rowanc1 ?

**Comment by rowanc1** [comment]
I have no problem with this. Do you know how to override the footer etc. in sphinx?

**Comment by lheagy** [comment]
yep, we did it for em: https://github.com/ubcgif/em/blob/master/_templates/layout.html

**Comment by lheagy** [comment]
This closed with #468
