### ISSUE TITLE
2D DCIP

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#248]
We should have a 2D code that allows for point sources by using digital transforms

**Comment by bsmithyman** [comment]
You’re hoping to do interpolated 2D point sources? I can help with that; at least on Cartesian grids, the Zephyr implementation is middlingly sophisticated. I think the Kaiser-windowed sinc function method makes sense for other grids too.

**Comment by lheagy** [comment]
Hey Brendan, that would be great! I think the approach typically applied for the DC problem is a cosine transform in space (we are dealing with a diffusion equation), but I am sure there are a lot of overlaps

**Comment by lheagy** [comment]
Done in #304 and #277
