### ISSUE TITLE
eqLocs --> formulation

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#258]
@sgkang and I were chatting yesterday and think that instead of doing `problem._eqlocs` is `EF` or `FE` (which is actually arbitrary and depends on whether you write Faraday's law or Ampere's law first) we do `problem._formulation` is `EB` or `HJ`. Thoughts?

**Comment by sgkang** [comment]
I prefer EB and HJ. More physical, since it is based upon what is flux and fields or which one is continuous on normal or tangential direction, hence I vote for `problem._formulation`

**Comment by rowanc1** [comment]
I like that.

**Comment by lheagy** [comment]
This closed with #261 and #265
