### ISSUE TITLE
travis & pymatsolver

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#259]
There seem to be issues importing the MumpsSolver on travis. For example, on the DCIP branch, we tried having "from pymatsolver import MumpsSolver" in the header and it errored. (https://travis-ci.org/simpeg/simpeg/jobs/113731790). It looks like when compiling the MumpsSolver there are some packages that cannot be found.  
<img width="883" alt="job 1066 4 - simpeg simpeg - travis ci 2016-03-04 11-33-04" src="https://cloud.githubusercontent.com/assets/6361812/13538028/03b32332-e1fd-11e5-8c26-2182dd7b7988.png">

**Comment by bsmithyman** [comment]
I've been running into the same problem on some of our systems (CentOS 7). And yet, it worked okay on Ubuntu in my JupyterHub container. So, I think we might need to figure out what Travis is running, and/or try to make a deployable serial MUMPS package (ugh).

**Comment by lheagy** [comment]
Yeah... we had it working last week, they must have updated some things

**Comment by rowanc1** [comment]
The version of scipy got updated to 0.17.0: this breaks things. :(

In the conda install if you add `scipy=0.16.1` this fixes the build for now. I will investigate further, I am not sure if this is in scipy or conda.

`ImportError (/root/miniconda/bin/../lib/libgfortran.so.3: version 'GFORTRAN_1.4' not found`

This will need to be added to the [.travis.yml](https://github.com/simpeg/simpeg/blob/dev/.travis.yml#L38)

**Comment by rowanc1** [comment]
I believe this is a bug in conda gfortran: ContinuumIO/anaconda-issues#686

**Comment by lheagy** [comment]
this seems to be working now? @rowanc1
