### ISSUE TITLE
DC cleanup 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#260]
These follow the code review comments in #236. Some of these are questions and may just be me not understanding the implementation, so please correct this if some of these are my confusion and not issues! 
- [x] clean out old commented-out code 
- [x] SurveyDC.eval should call rx.eval
- [x] Mass Matrix cleanup (these should be in a BaseDCIP: both DC and IP call them) 
  - [x] mass matricies should call getFaceInnerProduct, getEdgeInnerProduct ? 
  - [x] naming convention for mass matrices : MeSigma or MfSigma
  - [x] naming convention for mass matrix derivs: MeSigmaDeriv, MfSigmaDeriv
- [x] Ainv.clean() in fields, Jvec, Jtvec (for DC and IP) 
- [ ] Jvec in IP calls "forward" for computing the sensitivity: this is a bit confusing... the code from "forward" can just be put in Jvec? 
- [x] getActiveinffromTopo can be moved from DCIPUtils to meshUtils?

**Comment by sgkang** [comment]
Most of things are handled about this issue except for the IP one. 
See #650 if you still need clarification @lheagy.
