### ISSUE TITLE
Potential Fields

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#275]
We should bring: [simpegPF](https://github.com/simpeg/simpegpf) onto a dev/potentialfields branch! 
@rowanc1 , @fourndo

**Comment by fourndo** [comment]
Probably need another review session on this. I am a bit swamped this week, but was hoping to get back to it over the weekend.

**Comment by lheagy** [comment]
Fair enough, we can take care of this next week. Good luck with things!

**Comment by rowanc1** [comment]
I can meet over the weekend and sit down with you on this, if you would
like. I should also have some time to clean up and pull in some of the PRs.
-R
