### ISSUE TITLE
Zero and Identity Utils

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#284]
These are super touchy and don't and are susceptible to breaking with numpy and scipy updates because we are over-writing ufuncs and they don't behave the same if you multiply on the left or right (or add), for instance. I suggest we either init these with a size or convert them to sparse vectors / arrays on the fly when we mult or add to them. Thoughts @rowanc1?

**Comment by rowanc1** [comment]
Has this been fixed @lheagy?

**Comment by lheagy** [comment]
ah, yes this was fixed in #447
