### ISSUE TITLE
Boundary Conditions

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#286]
@sgkang and I were chatting about boundary conditions. Currently we allow two boundary conditions to be set on each boundary, which is likely confusing and potentially dangerous. 

Suggestion: in the a general case for a 2D problem something like: (@sgkang feel free to edit this!) 

```
BClist = [('mixed', {'alpha': 0.5, 'beta': 0.5, 'sigma':1}), 'neumann', 'dirichlet', ('neumann',10) ]
Problem(mesh, mapping, BC= BClist) 
```

![thumb_img_0375_1024](https://cloud.githubusercontent.com/assets/6361812/14329413/17de29e4-fbf0-11e5-90b5-c76df87d8f70.jpg)

**Comment by rowanc1** [comment]
It we are going to a complicated list, I would suggest a BC class instead
that can be supplied.

**Comment by lheagy** [comment]
Ah, that is nice, but in the simplest case still provide a list? (I doubt that the full functionality would be used all that often).

**Comment by grosenkj** [comment]
I like the idea of a BC class, it will make things cleaner and more extendable.

**Comment by rowanc1** [comment]
I would say, if the arg is not a BC class, just instantiate one. Either way, this should be handled in the BC property on the mesh.

**Comment by rowanc1** [comment]
The current BC implementation allows you to specify only the differences in the BCs on the mesh, so you never have to specify them if they are all the same.

`N == [N,N,N] == [[N,N], [N,N],[N,N]]`

**Comment by rowanc1** [comment]
#531 is a duplicate of this issue.

**Comment by rowanc1** [comment]
We should have a look at the implementation in pysit.

http://pysit.readthedocs.io/en/stable/api/pysit.core.mesh.StructuredNeumann.html#pysit.core.mesh.StructuredNeumann

**Comment by rowanc1** [comment]
This issue was moved to simpeg/discretize#20
