### ISSUE TITLE
Laplacian operator in DiffOperators

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#29]
add it

---
- Bitbucket: https://bitbucket.org/rcockett/simpeg/issue/27
- Originally Reported By: [ ](http://bitbucket.org/rowanc1)
- Originally Created At: 2013-11-06T19:27:56.081

**Comment by lheagy** [comment]
we have nodal laplacian. close this?

**Comment by rowanc1** [comment]
this should be there for a regular mesh
not a tensor mesh.

**Comment by rowanc1** [comment]
This issue was moved to simpeg/discretize#18
