### ISSUE TITLE
import of osr, gdal on MT import

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#290]
On master, right now `osr` and `gdal` are imported with MT, can we only import these if necessary?
<img width="503" alt="mt" src="https://cloud.githubusercontent.com/assets/6361812/14343619/137ba2b6-fc57-11e5-962f-ce7d38a7549b.png">

**Comment by grosenkj** [comment]
Done, fixed in branch mt/iss290. 

Moved the import into the projection function, so it should happen up on the function call.

**Comment by grosenkj** [comment]
Made a pull request #291.
