### ISSUE TITLE
Requirements of pymatsolver when importing Example

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#292]
Requirements of pymatsolver when importing Example: would it work for the online binders of em_example? @lheagy @rowanc1 

![screenshot 2016-04-07 12 54 07](https://cloud.githubusercontent.com/assets/13682747/14364932/0679c1b0-fcc0-11e5-85b7-d45079008f26.png)

**Comment by lheagy** [comment]
good catch! the EM_FDEM_SusEffects will not work as is on a binder (@sgkang). The import of Mumps needs to be changed in EM_FDEM_SusEffects.py. 
```
try:
    from pymatsolver import MumpsSolver
    SOLVER = MumpsSolver
except ImportError, e:
    SOLVER = SolverLU
```
and in the code `MumpsSolver` --> `SOLVER`

**Comment by lheagy** [comment]
@sgkang : could you help out here?

**Comment by rowanc1** [comment]
This seems to be fixed:

https://github.com/simpeg/simpeg/blob/ex/em_susc_effects/SimPEG/Examples/EM_FDEM_SusEffects.py#L62
