### ISSUE TITLE
Ainv.clean()

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#300]
We don't need to clean the factors for each forward, Jvec, Jtvec (it would be a 3x speedup if we can use the same factors for each)

**Comment by lheagy** [comment]
![invproblem py simpeg 2016-05-30 15-19-28](https://cloud.githubusercontent.com/assets/6361812/15659119/4c7e6326-267a-11e6-874b-50673ffda53c.png)

**Comment by grosenkj** [comment]
I second this. It would make a huge difference for speed when using a direct solver.
