### ISSUE TITLE
SimPEG.properties

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#314]
`SimPEG.properties`: Simple geometric items can be classes with properties that are handy, and methods that do things like coordinate rotations 
- [ ] `Vector`: base property
  - stored properties:
    - `vector`
  - computed properties: 
    - `normal` : unit vector along the the orientation of the line
    - `inclination` : inclination of the normal
    - `declination` : declination of the normal
  - methods:
    - `rotate2coordinate(self, XYZ)` : rotate a grid to align with the normal (not sure about this name)
    - `plot` : plot the property
- [ ] `Point(Vector)`: point in space
- [ ] `LineSegment(Vector)`: a line with orientation that matters (ie orientation of a dipole) 
  - additional computed properties: 
    - `length` : magnitude of the vector 
    - `endpoints` : endpoints of the vector
- [ ] `Plane(Vector)`: a 2D plane 
  - additional computed: 
    - `strike`
    - `dip`
  - methods:
    - `project2plane(self,XYZ,V)`: project values defined in space to this plane
- [ ] `Parallelogram(Plane)`
  - additional properties 
    - `OUV`
  - computed properties
    - `endpoints`
    - `area`
- [ ] `Rectangle(Parallelogram)` : a rectangle
  - additional properties 
    - `OUV`
    - computed properties
    - `endpoints` : 4 corners of the plane
    - `area`
- [ ] `Loop(Plane)`: a 2D loop
  - additional stored properties:
    - `radius`
  - computed properties: 
    - `diameter`
    - `circumference` 
    - `area`

**Comment by rowanc1** [comment]
Vector is just [x,y,z]
Line is [vector, vector], first `endpoint` of a vector is implied to be the origin.
Plane should be [vector, vector] as well, `point` and `normal`, strike, dip etc can be inferred.
Perhaps we have a Parallelogram? which has corners? in this case I would recommend the origin and the edges as vectors [O, U, V] which traces out a finite parallelogram.

For all of these we should note the basic properties and the ones that are convenience. so as not to store redundant and possibly contradictory information.

**Comment by lheagy** [comment]
- a vector should be able to have length, and arbitrary origin (a dipole is a vector-like object) meaning it could be defined by two points. I would call the description you have above as a `unitVector` or `normal` which only contains directional information, is implied to be at the origin and has unit length. 
- agreed that strike, dip, etc can be inferred - Things like `x0`, `normal` (and possibly extent info) should be stored - the rest can be computed on the fly
- parallelograms could be handy, as would rectangles

**Comment by rowanc1** [comment]
Is this it's own library?

**Comment by grosenkj** [comment]
This might be better in it's own library. 

I would also say we should have 
- [ ] `Vertex/Point(BaseProperty)` - an point of xyz coordinates.

- [ ] `Line(BaseProperty)` - made out of 2 points
   - properties
      -`pt1` and `pt2`
   - calculated 
      - `length` 
      - `normal` - will be 
   - methods
       - `toVector` - converts line to a vector 

- [ ] `Triangle(BaseProperty)`  a triangle, made from 3 `Vertex` or 2 `Vector`'s of length. 

We should look into the naming as well, have `Circle` which has radius, etc and loop to be `Loop` to be a polygon with >3 pts that are connected in order. 

I think leveraging other libraries, `shapely`, `vtk` or similar would be a good way approach this. That would also open up having operations, like union, intersection, etc available.

**Comment by rowanc1** [comment]
We should likely use traitlets. This will allow for interaction with the ipython interactive widgets. Additionally there is http://propertiespy.readthedocs.io which will have a similar intent.

**Comment by rowanc1** [comment]
This is handled in #517 and by the new `properties` library.
