### ISSUE TITLE
Plotting on meshes

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#330]
@thast is visualizing inversion results on SimPEG meshes and has a couple requests
- [ ] `showPadding = False` we should be able to detect where cell sizes change (for tensor at least) and only plot the core region of the mesh (default can be true) - this is important when showing inversion results (there is no data support in the padding). Sometimes you do want to show larger axes to compare lines that are offset but geo-referenced
- [ ] `mesh.plotCountours` same as plotimage - but do contours (or countouf) instead

**Comment by thast** [comment]
![npmask](https://cloud.githubusercontent.com/assets/13682747/15759238/d85134f6-28c2-11e6-858f-cb05b6c553e0.png)

**Comment by thast** [comment]
masking can be use to remove the padding (as long as you know where to cut):
mask0 = np.ma.masked_where(np.logical_or(meshlist[0].gridCC[:,0]<641000,meshlist[0].gridCC[:,0]>644000),np.random.rand(len(modelDClist_work[0])))

**Comment by rowanc1** [comment]
This issue was moved to simpeg/discretize#15
