### ISSUE TITLE
FDEM name space code and implementation questions/review

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#334]
Review question of FDEM code from refactoring of NSEM code.

**Comment by grosenkj** [comment]
In 'BaseRx'

![image](https://cloud.githubusercontent.com/assets/6052367/15945190/044fd69c-2e46-11e6-8ca4-abcf15fe4156.png)

**Comment by lheagy** [comment]
yep, absolutely that should be `f`

**Comment by grosenkj** [comment]
In `FieldsFDEM`
![image](https://cloud.githubusercontent.com/assets/6052367/15945463/892209ac-2e47-11e6-857b-81743a4cc7d4.png)

Could be ...
`
def _GLoc(self, fieldType):
     return self.aliasFields[fieldType][1]
`
since things are already defined there.

**Comment by grosenkj** [comment]
In `FieldsFDEM`

![image](https://cloud.githubusercontent.com/assets/6052367/15945607/383d7c32-2e48-11e6-9f8e-174efc9c1750.png)
