### ISSUE TITLE
Use of `du_dm_v` in `FieldsFDEM` methods

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#335]
`du_dm_v` should just be `v`.

**Comment by lheagy** [comment]
not in all cases. We pass `du_dm_v` to `df_du` so that we get `df_du * du_dm_v` by chain rule

**Comment by grosenkj** [comment]
I see that now. So for methods that only take one input, `du_dm_v ` should become v?

**Comment by grosenkj** [comment]
I am just referring to the name of the input to the methods, like `_?Deriv_u`. I think the input to `*_u` functions should be called `v` not `du_dm_v` since it is just a vector to multiple with (as described in the help string). However, in `_*Deriv` the vector given to `_?Deriv_u` is `du_dm_v`. I hope this explains my point better. 

This isn't a big deal and I believe there is a reason for this in the math but I am not there yet.
