### ISSUE TITLE
_GLoc estimation

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#336]
In `FieldsFDEM` classes all have a method

``` python
    def _GLoc(self, fieldType):
        if fieldType == 'e':
            return 'E'
        elif fieldType == 'b':
            return 'F'
        elif (fieldType == 'h') or (fieldType == 'j'):
            return 'CCV'
        else:
            raise Exception('Field type must be e, b, h, j')
```

Could be changed to 

``` python
def _GLoc(self, fieldType):
     return self.aliasFields[fieldType][1]
```

and moved to the base `Fields`

**Comment by lheagy** [comment]
There is a distinction between EB, HJ formulations and where things live, but: 
Agreed that we could use 
```python 
def _GLoc(self, fieldType):
     return self.aliasFields[fieldType][1]
```
instead though.

**Comment by lheagy** [comment]
I am closing this as there hasn't been discussion in a long time. Please feel free to re-open if you have further comments to add.
