### ISSUE TITLE
Memory issues in TDEM problem

### ISSUE THREAD

**Issue by sgkang** [simpeg/simpeg#352]
Not exactly sure at the moment, but I think there is similar memory issue
that we have faced years ago. 

Note: my fwd problem takes 22% of ubc cluster, but inversion fails with memory issue. 
          I guess we need three fields needs to be stored so about 66% is supposed to be used.

**Comment by lheagy** [comment]
Which formulation are you using? an on which branch? we should not be storing the fields on the refactored tdem code. Only the b formulation has really been tested. E formulation is not working yet (it is only first order Jvec). Waveforms also have not been tested yet.

**Comment by sgkang** [comment]
I am testing B formulation, and em/ref/tdem branch. I guess above reference seems suspicious to me because knownFields have four fields e,b,h,j, which possibly initialize all of them.

**Comment by rowanc1** [comment]
![image](https://cloud.githubusercontent.com/assets/913249/16421168/50b0a5be-3d11-11e6-821d-c4d683715f08.png)

These only get init-ed if they are used in the derivs. E.g. if you have all types of receivers.

**Comment by sgkang** [comment]
Okay, then that may not be issue.

**Comment by sgkang** [comment]
Profiling time domain EM
![image](https://cloud.githubusercontent.com/assets/6054371/16436241/0e68b472-3d51-11e6-990d-267e41b7d3e6.png)

**Comment by sgkang** [comment]
Profiling frequency domain EM
![image](https://cloud.githubusercontent.com/assets/6054371/16436322/ca7c6082-3d51-11e6-8031-c03390902069.png)

**Comment by sgkang** [comment]
![image](https://cloud.githubusercontent.com/assets/6054371/17448333/94466696-5b08-11e6-8923-13d80d74db6b.png)

Fixed. See #381
