### ISSUE TITLE
Remove Meshing --> Package

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#360]
We should remove all meshing functionality from SimPEG. This has matured and can be a stand-alone package.

![image](https://cloud.githubusercontent.com/assets/913249/16897486/c59fbce6-4b78-11e6-9a78-80a5989466b6.png)

**Comment by rowanc1** [comment]
I will be trying to get to this before the end of the month.

See https://github.com/simpeg/simpeg/milestone/4

**Comment by rowanc1** [comment]
@lheagy @leouieda I have made the first passing version of this in the `discretize` repo. There are a bunch of utils that need to be killed, and I will do a bit more clean up before I put it on master.

**Comment by leouieda** [comment]
@rowanc1 nice! I saw the post on twitter. There a lot of simpeg logos and refereces on the docs as well that would need to be updated. The tutorials and gallery are great!

**Comment by rowanc1** [comment]
Yeah, the docs need an overhaul. I will focus on this in feb when writing up more of the theory and cleaning up some more utilities, examples etc. It would be really interesting to hear where you think your meshing algorithms/utilities fit in here!

**Comment by leouieda** [comment]
I'll need to read the docs more carefuly and try to finally understand this finite volume business first :)

**Comment by rowanc1** [comment]
This has been completed!
