### ISSUE TITLE
Examples auto-doc bug

### ISSUE THREAD

**Issue by fourndo** [simpeg/simpeg#375]
Error executing the __init__.py in examples.
 
Most likely a windows path thing.
Please help...

![autobuild_example_message](https://cloud.githubusercontent.com/assets/2406426/17345758/7d183844-58bc-11e6-9e97-bf519fc95204.PNG)

**Comment by rowanc1** [comment]
Yeah. Need to use an os.path.sep

**Comment by rowanc1** [comment]
I think this has been fixed.
