### ISSUE TITLE
Utils.surface2ind_topo does not work on Cell Center (which is the default)

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#376]
.\SimPEG\SimPEG\Utils\modelutils.py -> surface2ind_topo

Function that return active model from a mesh and a topogphy (x,y,z).
works fine if the kwargs "N" is given.
By default it is "CC" and then the indexing array is only the size of nCx_nCz instead of nCx_nCy*nCz

![errorsimpegtopo](https://cloud.githubusercontent.com/assets/13682747/17347255/b18608f2-58c3-11e6-8f8d-adf333f3f286.png)

**Comment by lheagy** [comment]
@thast: could you write a simple test / example on a small(ish) 3D mesh to demonstrate the failure? perhaps using a sinusoidal function as an example? there are some relatively simple tests in the test_utils.py that you could check out, along with some explanations here: http://simpegtutorials.readthedocs.io/en/latest/content/practices.html#testing

**Comment by thast** [comment]
@lheagy : can do, yes! (but not today unfortunately)

**Comment by lheagy** [comment]
@thast: is this still an issue? If so, could you create a small example that demonstrates it?

**Comment by thast** [comment]
Taking care of it in #599
