### ISSUE TITLE
MT import naming collision

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#393]
See quantified code: https://www.quantifiedcode.com/app/project/933aa3decf444538aa432c8817169b6d/snapshot?groups=code_patterns%3AkJ13jArn%3Af0

![image](https://cloud.githubusercontent.com/assets/6361812/17652639/a45106c4-6236-11e6-84b5-f0f2a602296c.png)

**Comment by grosenkj** [comment]
This is fixed in pull request #423
