### ISSUE TITLE
Better Communication

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#408]
After the BIRS2016 conference one of the big takeaways is that we need to be more communicative about our development roadmap, what projects are actively under development, and papers that are being worked on at the moment.

To that end, I suggest we make better use of:
- [ ] Github Milestones
- [ ] Github Wiki?
- [x] Signup for the slack channel @lheagy 
- [x] More frequent updates to the website/blog? should we use medium?
- [ ] Improve the docs - under construction signs and sketches at implementations
- [x] live stream dev meetings (youtube channel)
- [x] auto update PIP
- [x] Google groups?
- [x] Mailing list with major updates?

The next stage of SimPEG's growth is to engage a much wider community. I am very curious to here what does and does not work for people please let us know!

**Comment by rowanc1** [comment]
See most of the links here:
http://docs.simpeg.xyz/index.html#links

Google groups still needs to be added:
https://groups.google.com/forum/#!forum/simpeg

**Comment by lheagy** [comment]
We can follow this up at the meeting next week. I am not sure if using Milestones at the stage we are currently at will really be all that beneficial. Similarly, I don't know what we would use the wiki for (I am hesitant to fragment our docs or anything like that...) 

Related, we need to post some links on the docs and on the simpeg website (related, simpeg/website#13, simpeg/website#14)  
- [ ] google group on docs
- [ ] blog link on docs

**Comment by lheagy** [comment]
I am closing this as there hasn't been discussion in a long time. Please feel free to re-open if you have ideas on how to improve communication!
