### ISSUE TITLE
Organization of Analytics

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#412]
Questions:

1) Are these their own repository? `from geoana.em.tdem import MagDipoleWholespace`
2) Can we make these classes?
3) These should be easy to interact with in the jupyter environment?

Possible interaction:

``` python
mdw = MagDipoleWholespace()
mdw.location = [0,0,0]
mdw.orientation = 'up'
print(mdw.orientation)  # [1,0,0]
mdw.moment = 50.
mdw.sigma = 1e-2

ex = mdw.e_x(xyz_locations, **kwargs_that_set_anything)
mdw.plot()

mdw.plot_fields()
mdw.plot_ex()  # etc!

mdw.interact()  # shows a widget!
```

We also want to be able to interact with the SimPEG mesh, library structure will need to take this into account.

I would suggest using the traitlets library. Please see some of the extensions that we have made for this in 3ptscience/steno3dpy#49.

Also see #315.

Organization of these can get the development to scale out of UBC, and as a standalone repo we do not have to wait for them to get to master before they can start being used in EM geosci and other places.

Other thoughts?

**Comment by micmitch** [comment]
Don't really have a clear idea of your vision here. Will talk with folks about it when they are back in town.

**Comment by rowanc1** [comment]
cf #314

**Comment by lheagy** [comment]
We have made a start on this in #699 and simpeg/geoana#9 for dipole and loop sources in EM.

**Comment by lheagy** [comment]
Closing this in favour of writing more specific issues on analytics
