### ISSUE TITLE
Simpeg install on Windows 7 pro failing

### ISSUE THREAD

**Issue by hal98x** [simpeg/simpeg#413]
Hello I have Anaconda Python 2.7.12 on Window 7 64 pro.  I have attempted to install Simpeg by first pip and from cloning the the github repo and using python setup.py install. Here is the last little bit of output from installing from source

SimPEG/Utils/interputils_cython.c(1545) : warning C4244: '=' : conversion from '
npy_intp' to 'int', possible loss of data
SimPEG/Utils/interputils_cython.c(1792) : warning C4244: '=' : conversion from '
__pyx_t_5numpy_float64_t' to 'float', possible loss of data
SimPEG/Utils/interputils_cython.c(1816) : warning C4244: '=' : conversion from '
double' to 'float', possible loss of data
SimPEG/Utils/interputils_cython.c(1840) : warning C4244: '=' : conversion from '
double' to 'float', possible loss of data
SimPEG/Utils/interputils_cython.c(2050) : warning C4244: '=' : conversion from '
npy_intp' to 'int', possible loss of data
SimPEG/Utils/interputils_cython.c(2487) : warning C4244: '=' : conversion from '
npy_intp' to 'int', possible loss of data
SimPEG/Utils/interputils_cython.c(3188) : warning C4244: '=' : conversion from '
npy_intp' to 'int', possible loss of data
C:\Users\mwallace\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\
9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\mwallac
e\AppData\Local\Continuum\Anaconda2\envs\geophysics2\libs /LIBPATH:C:\Users\mwal
lace\AppData\Local\Continuum\Anaconda2\envs\geophysics2\PCbuild\amd64 /LIBPATH:C
:\Users\mwallace\AppData\Local\Continuum\Anaconda2\envs\geophysics2\PC\VS9.0\amd
64 /EXPORT:initSimPEG/Utils/interputils_cython build\temp.win-amd64-2.7\Release\
SimPEG/Utils/interputils_cython.obj /OUT:build\lib.win-amd64-2.7\SimPEG\Utils\in
terputils_cython.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\SimPEG/Utils\inter
putils_cython.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\SimPEG/Utils\in
terputils_cython.pyd.manifest
LINK : error LNK2001: unresolved external symbol initSimPEG/Utils/interputils_cy
thon
build\temp.win-amd64-2.7\Release\SimPEG/Utils\interputils_cython.lib : fatal err
or LNK1120: 1 unresolved externals
error: command 'C:\\Users\\mwallace\\AppData\\Local\\Programs\\Common\\Microsoft
\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status
1120

I uninstalled and reinstalled Visual C for Python compiler just to make sure it was functioning properly. 

Sincerely, 

Michael Wallace

**Comment by hal98x** [comment]
I thought anaconda installed cython automatically. Once I installed cython with conda. Simpeg installed easily from source.

**Comment by lheagy** [comment]
Glad to hear it! We can make note of that is the setup for SimPEG
