### ISSUE TITLE
Distribution through conda-forge

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#414]
conda-forge would give us more control and input on setting up the necessary environment for SimPEG to work! This will be particularly useful for compatibility with solvers. 

conda-forge/fatiando-feedstock#1 has some tips for getting started

**Comment by rowanc1** [comment]
cc @leouieda for help :)

**Comment by leouieda** [comment]
@lheagy @rowanc1 let me know if you need anything

You can start here actually: https://github.com/conda-forge/staged-recipes

You'll need to fork that repo, modify their example `meta.yml` file (you can see the one from the fatiando build for an example) and make a PR. 

From your travis ci config, it looks like you need a lot of system libs and pyMKL. Is that required by simpeg itself or by pymatsolver? Also, can you run simpeg without it? If not, I'd suggest getting pymatsolver packaged first, then going for simpeg and putting it as a dependency.

**Comment by lheagy** [comment]
I have forked staged-recipes here: https://github.com/simpeg/staged-recipes. I think we will need to resolve #432 with respect to issues running setup.py on windows before we can get the recipe staged

**Comment by prisae** [comment]
Closing, as SimPEG is available through `conda-forge` since v0.12.0, and discretize since v0.4.10.
