### ISSUE TITLE
locations as classes? 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#424]
in particular for for sources and receivers 
- uid
- know how to make projections (when the survey is paired with a problem) 
  These can then be shared by multiple receivers (eg. real bx, imag bx in the same locs can use the same projection matrix)

**Comment by rowanc1** [comment]
Not quite sure of the implementation that you ave in mind here. Might be overkill from a class point of view? Each vector or each source/rx?

**Comment by lheagy** [comment]
might be a bit of overkill as a class, (or trait??) 

but basically, the biggest benefit would be recognizing that two types of receivers might share locations. For example, if I do a multi-frequency survey, with 10 frequencies, collecting bx_real, and bx_imag, we currently would build the projection matrix 20 times every time we get predicted data (for each freq x 2 for two different data types) even though the interpolation matrix never changes.

**Comment by rowanc1** [comment]
I see. This is somewhat done between shared receivers between sources, but could be done also between receivers.

**Comment by rowanc1** [comment]
This could be helped by `properties` with the vector math functions, which are classes.

**Comment by lheagy** [comment]
Locations will be properties in #786

**Comment by lheagy** [comment]
I am going to close this - the properties class takes care of a lot of these ideas
