### ISSUE TITLE
PropMaps

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#444]
Overview video here:
https://youtu.be/VtFC7jQVWaM?t=5m55s

In the current implementation of `PropMap` there are a few things that are wrong:
# Bugs in the current idea
1. It does not pickle, leading to a bunch of problems when saving objects. cc @grosenkj 
2. The idea of projections/slicing are separated from the mappings  `pm.sigmaProj` this should just be a map.
3. There are not dynamic defaults, so overriding `mu` in `FDEM` is not possible without creating a new `PropMap`. cc @sgkang 
4. It is not easily extensible by children and new classes, and the pattern is to overwrite.
5. It assumes that all of the model properties are in a single class e.g. the `Problem` and this does not allow for inverting for things like source height/waveform. cc @lheagy 
6. The `PropModel` (`curModel`) is created dynamically (pickling is hard) with all model properties on it. This means that again that models can not be distributed throughout the code.
7. There is a lot of magic happening (and clearly it is not very good magic). cc @bsmithyman :)
# Some constraints:
- want to work with either reciprocal property sigma/rho - some version of linking
- want to choose the inversion models that are active - the ones that have maps?
- understandable
# Sketch at the implementation

``` python
import properties
import .props
from SimPEG import Maps, Problem
from scipy.constants import mu_0

class Problem3D_e(Problem.BaseProblem):

    sigmaMap = props.Mapping("sigma mapping", defaultInvProp=True)
    sigma = props.PhysicalProperty("sigma", default=None, mapping=sigmaMap)

    rhoMap = props.Mapping("rho mapping")
    rho = props.PhysicalProperty("rho", default=None, mapping=rhoMap)

    props.link((sigma, rho), Maps.ReciprocalMap)

    muMap = props.Mapping("mu mapping")
    mu = props.PhysicalProperty("mu", default=mu_0, mapping=muMap)

    # etc.
```

Here the properties are directly on the problem rather than being on a `PropMap`. The defaults can be set through the physical property directly, which is again a property of the class. The physical property would have a bit of a **wrapper** that would supply some `scope` (just referring to the wrapping function, which may have some metadata) for the function, and would end up looking a bit like:

``` python
@property
def sigma(self):
    # the scope would be set in `properties.model.PhysicalProperty`
    if scope.default is not None:
        return scope.default
    mapping = getattr(self, scope.mapping.name)
    return mapping * self.model

@sigma.setter
def sigma(self, value):
    # clear the mapping, you are setting the default sigma
    setattr(self, scope.mapping.name, None)
    self._sigma = value
```

Here the `model` is just a vector on the containing class. The `PropMap` implementation had easy access to both the `Proj`ection (slicing into the model) as well as the `Deriv`, which were properties of the class. The slicing is a bit more involved, but the derivative would be straightforward:

``` python
if self.sigmaMap is None:
    return Utils.Zero()

sigmaDeriv = self.sigmaMap.deriv(self.model)
```

The knowledge that you are inverting for `sigma` would be stored by knowing that you have an active mapping, i.e. you are connected to the model. This could potentially be shown to you in a `problem.summary()` or something. There would have to be a bit of magic to read through to the linked reciprocal maps, but that shouldn't be too bad.

The slicing is a separate concern, and is about setting up the wiring to go from an array to a whole bunch of subsets that are linked through short/fat sparse matrices (e.g. slice an identity horizontally to get two physical properties). These are just `Maps` but it would be nice to name bits and pieces of models for easy of use. Something like:

``` python
wires = Utils.Wires([
    ('sigma', mesh.nCz),
    ('mu_casing', 1),
])

assert isinstance(wires.sigma, Maps.WireMap)
assert wires.nP == mesh.nCz + 1

named_model = wires * model

named_model.sigma == model[:mesh.nCz]
named_model.mu_casing = model[-1]

prob.sigmaMap = Maps.SurjectVertical1D(mesh) * wires.sigma
```
# Summary

This would only have to be done if you are inverting for two properties, but it would allow you to hook up multiple classes (e.g. `Src` and `Problem`) to the same inversion model. I think that the use of it is a bit more clear.

Disadvantages:
- slightly harder to get at derivatives
- slightly harder to get at the projection (e.g. last map in the `sigmaMap`)

Feedback? I would propose http://propertiespy.readthedocs.io to handle a lot of the validation.

**Comment by rowanc1** [comment]
I have implemented most of these features on `em/propmaps` branch. The code is tested, but not yet integrated. I have not created `wires` yet.

The implementation (from the outside) looks like this:

```python
class ReciprocalMapping(Props.BaseSimPEG):

    sigma, sigmaMap, sigmaDeriv = Props.Invertible(
        "Electrical conductivity (S/m)"
    )

    rho = Props.PhysicalProperty(
        "Electrical resistivity (Ohm m)"
    )

    Props.Reciprocal(sigma, rho)
```

Pretty simple. It handles all of the nullifying of various things due to the linking of both prop-map and four/three/two way rprop-(rmap)-prop-(map). This means you are always reading through to the last set property.

**Comment by grosenkj** [comment]
I like this. To honest, I never understood what happen in `PropMaps` it just did. I support a clearer definition of the `Properties` and their `Mappings`.

**Comment by rowanc1** [comment]
Note: Adding `Props.py` will replace `PropMaps.py` and `Models.py`. The model wraps a `numpy.ndarray` and a `SimPEG.Map`.

The new code would expect the `model` to just be a numpy array. There is some comparisons that we do to not rerun the fields, these would also need to be checked (I think this should be fine though!).

**Comment by rowanc1** [comment]
The entire FDEM code base is now working locally.

Note that this means that we can work with `Problem`s in the forward sense, just specifying default `PhysicalProperty`s so in those cases `dpred` and `fields` should not take models.

**Comment by rowanc1** [comment]
The wires have been implemented in 7f2b3ce9cccff4e5c5334fddddfc4889736ba7d0

**Comment by sgkang** [comment]
Cool. This is much clear and explicit (which is good) than previous propmap. 
Also, I like the ideas of `Utils.Wires`, which will allow us to input multiple physical properties. 
I'll checkout `em/propmaps` branch, then will try to make corresponding changes in TDEM and Static

**Comment by rowanc1** [comment]
This is now working across all tests in FDEM, TDEM, NSEM, Richards, DC, IP, Grav, Mag. 

... You know, most of the geophysics ...

I am quite happy to say that having tests is the most awesome thing ever, there is no way that I could have done that without the amazing tests that y'all have written.

I also put a bit of effort into making the code PEP8 compliant, so the PR is going to be a bit messy.


![image](https://cloud.githubusercontent.com/assets/913249/19102178/4e8fd468-8a8b-11e6-9d68-e87b2d3e5109.png)

**Comment by rowanc1** [comment]
TODO:
- [ ] `problem.validate()`, meaning `sigma.assert_valid()`
- [ ] backwards compatible mapping property
- [ ] better error messages on fields and dpred statements when no model is given.
- [ ] depreciation warnings by making examples run as is
- [ ] properties `v0.2.0` release
- [ ] review

**Comment by rowanc1** [comment]
There is now a validate function on the problem, however, I have not put much effort into it yet.

There is some more documentation here:
3ptscience/properties#45
