### ISSUE TITLE
Improve speed of travis tests

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#459]
- [x] don't run all 3/2 python tests on all commits?
- [ ] split out mesh code to another repository #360 
- [ ] only run docs build on 2.7?

**Comment by lheagy** [comment]
perhaps docs builds only on 3? (keep moving forward!)

**Comment by lheagy** [comment]
closing this as it was resolved (at least in part) by removing test-runs on python 2.7 in #758
