### ISSUE TITLE
rx.projComp should be rx.orientation

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#465]
This is confusing

![image](https://cloud.githubusercontent.com/assets/6361812/19016983/1d628024-87df-11e6-8960-eefca9dc9418.png)

**Comment by rowanc1** [comment]
![image](https://cloud.githubusercontent.com/assets/913249/21528264/2e55559a-cce6-11e6-921e-6447fd9d4ae1.png)

**Comment by lheagy** [comment]
right now, we are using "orientation" for `x`, `y`, `z` and still using `component` for `real` `imag`. I think this is working okay. Feel free to re-open if you would like to continue the discussion.
