### ISSUE TITLE
BaseMagMap --> ChiMap

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#472]
This allows you to work with `Chi` instead of `mu`?

Can we rename this to `ChiMap`?

**Comment by rowanc1** [comment]
Thoughts @fourndo?

**Comment by fourndo** [comment]
yea ChiMap makes sense. we can do it here for sure. I guess I got confused with the example you posted on #471. What is Props doing?

**Comment by fourndo** [comment]
ok I think I kind of get it. Would be great to have a tour though. Lots of calls I don't understand.

**Comment by rowanc1** [comment]
This will be done in #517.
