### ISSUE TITLE
documentation for maps

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#476]
The documentation for maps is currently buried under Utilities. 
- [x] Maps should be at the top level for the docs. 
- [x] all of the api should be documented (only select maps are built right now) 

![image](https://cloud.githubusercontent.com/assets/6361812/19662314/d1cf67fc-99eb-11e6-9465-940c6d145ecc.png)

**Comment by rowanc1** [comment]
Excellent point.

**Comment by lheagy** [comment]
This closed with #483, #488
