### ISSUE TITLE
mesh.domain

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#484]
Often, it is handy to check the extent of a mesh (eg. when making sure it is large enough wrt skin-depths). Right now, I would go through each dimension and print the min and max cell center. Perhaps we can accomplish this through a `mesh.domain`

```
@property
domain(self):
    if mesh.dim == 3 # same idea for 1D, 2D 
    return np.array(
        [self.vectorCCx.min(), self.vectorCCy.min(), self.vectorCCz.min()], 
        [self.vectorCCx.max(), self.vectorCCy.max(), self.vectorCCz.max()]
    )
```

thoughts?

**Comment by rowanc1** [comment]
This issue was moved to simpeg/discretize#14
