### ISSUE TITLE
Concave Areas not calculated properly in LOM

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#5]
area calculation (i.e. 'volume' in 2D) is not correct if the cell is concave.

Currently averaging the four parallelograms, and I think this works out to give the area of the convex hull of the cell.

Need to write test cases and explore this issue.

---
- Bitbucket: https://bitbucket.org/rcockett/simpeg/issue/3
- Originally Reported By: [ ](http://bitbucket.org/rowanc1)
- Originally Created At: 2013-08-01T17:33:02.126

**Comment by lheagy** [comment]
@rowanc1 : is this still an issue?

**Comment by rowanc1** [comment]
I believe so yes.

**Comment by rowanc1** [comment]
This issue was moved to simpeg/discretize#17
