### ISSUE TITLE
List of Publications

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#500]
Should get these on the examples page!

See also #482

**Comment by lheagy** [comment]
I quite like the PyGimli page with references: https://www.pygimli.org/publist.html

**Comment by lheagy** [comment]
Making a table in rst: 

```
.. list-table::
   :header-rows: 1

   * - **1- Input Data**
     - **Object and data fields selection**
```

**Comment by lheagy** [comment]
Where do folks think we should do this? Is it best suited in the [SimPEG docs](http://docs.simpeg.xyz/)? or maybe on the main [SimPEG webpage](https://simpeg.xyz/)? 

I am inclined to suggest we put it on the simpeg.xyz and then have a link in the docs that points there. This way, folks who only use discretize, geoana, or one piece of the ecosystem can still post there. Thoughts?

**Comment by lheagy** [comment]
I will close this in favour of moving the discussion over to simpeg/community#11
