### ISSUE TITLE
need simple cellGrad for regularization on TreeMesh 

### ISSUE THREAD

**Issue by micmitch** [simpeg/simpeg#504]
TreeMesh does not inherit the functions in DiffOperators.py this currently limits us to the use of BaseRegularization which does not use any derivative terms for model smoothness. Hopefully we can use the faceDiv operator that we have to create a simple gradient operator for use in the regularization. Just not sure where this should be built or where to start from.

**Comment by rowanc1** [comment]
This issue was moved to simpeg/discretize#16
