### ISSUE TITLE
Straight Ray Tomography Example

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#528]
Because.

**Comment by rowanc1** [comment]
@lheagy I have pushed the initial start of a straight ray tomography example.

I think some of the code can move into the main codebase? And needs some testing.

I think this could be helpful to show a joint inversion using the combo objectives that you are currently developing. Let me know if you need more help with this. Perhaps a PR onto your branch?

**Comment by lheagy** [comment]
@rowanc1 : which branch did you push this on?

**Comment by rowanc1** [comment]
dev

**Comment by lheagy** [comment]
This will be addressed in #511

**Comment by lheagy** [comment]
This is now on dev with #511
