### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#544]
The docs say that we should install Python 2.7. This should be changed to 3!

**Comment by lheagy** [comment]
👍  We should also consider combining the "Getting started" that is currently in the tutorials

**Comment by rowanc1** [comment]
@lheagy do you have a plan on how we keep `tutorials` and `simpeg` docs separate?

**Comment by lheagy** [comment]
This is not entirely clear at the moment, but I think that they should have distinct purposes:

`simpeg` docs examples: each example demonstrates how to accomplish a task within SimPEG. I would love to see the addition of a `Purpose` at the top of each example - what are we going to accomplish in this example? The target audience for these types of examples I would say is people who are familiar with the field and with running numerical simulations, but are new to SimPEG

`tutorials`: these contain much more background information and theory. The `stories` are work through a problem and explain underlying concepts (eg.  http://tutorials.simpeg.xyz/content/stories/TKC_DC_story.html). The intent of the other pages (Pixels and their neighbours, ...) each explain a fundamental concept of inversions. We might want to consider moving the `tutorials` to http://inversion.geosci.xyz. 

There are some points of overlap that should be addressed:
- Getting started: http://tutorials.simpeg.xyz/content/gettingstarted.html
- practices: http://tutorials.simpeg.xyz/content/practices.html 
Both of these I think may be better suited in the SimPEG docs. I would be happy to move them over.

**Comment by rowanc1** [comment]
I like the `inversion.geosci.xyz` idea. There is quite a lot of content that we could also pull from the SimPEG paper (CC-BY 👍). I will add a `purpose` to the examples and get people to look over them.

I agree with moving the `Getting started` and `Practices` over. I can tackle that to start with.

**Comment by lheagy** [comment]
Yeah, I think `inversion.geosci.xyz` clarifies the scope of that body of work and how it is distinct from the SimPEG docs. Perfect, let me know when you are done and I can transfer the tutorial repo to `geoscixyz/inversion`

**Comment by rowanc1** [comment]
Talking through this with @lheagy @dougoldenburg and @sgkang we were thinking `computation` rather than `inversion`. We have started a first pass here:

https://github.com/geoscixyz/computation

**Comment by lheagy** [comment]
This closed with #595
