### ISSUE TITLE
Gallery of Examples

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#554]
We could move to a gallery of examples, upgrading a few of them as we go. By default this means that they are a bit harder to interact with from the package (i.e. they are more part of the docs than the code). But I think we can get away with that by doing a make script etc.

Things:
- Better visibility on examples
- Can download them individually as `.ipynb` or as `.py`
- Captures output
- Need to copy from package to docs
- Would like to introduce properties into some of the examples to help document them.
- Need to think about how to show examples from sub packages.

![image](https://cloud.githubusercontent.com/assets/913249/23589734/e3ff82c0-018f-11e7-9356-bb5c31db3f5d.png)

**Comment by lheagy** [comment]
I think this would be great! The main way of interacting with an example (at least my take) is to tinker with the code. Just importing an example and watching it run doesn’t teach much other that “this is possible”
 
Also, there are some cool plug-ins for building these types of examples from a notebook (something to think about)
- http://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html 
- http://nbsphinx.readthedocs.io/en/0.2.13/

**Comment by rowanc1** [comment]
A PR for this should also address #553 #544 #491

I will do a first pass and see what people think

**Comment by rowanc1** [comment]
Some progress:

![image](https://cloud.githubusercontent.com/assets/913249/23591697/d729631e-01b1-11e7-835e-21354c239817.png)

**Comment by rowanc1** [comment]
I also brought in the notebooks from the `notebooks` repo. Not really sure if this is the best way to do that.

![image](https://cloud.githubusercontent.com/assets/913249/23592610/db1e4228-01c0-11e7-9cb4-4f6cc91ce8f1.png)

**Comment by lheagy** [comment]
The dev-docs are not currently deploying. We likely need to update what is uploaded to google app engine. https://travis-ci.org/simpeg/simpeg/jobs/209059459

![image](https://cloud.githubusercontent.com/assets/6361812/23726279/8c9de03c-0408-11e7-931b-c166fca4e920.png)

**Comment by lheagy** [comment]
I am hoping #563 resolves this

**Comment by lheagy** [comment]
It looks like there is now a conflict with python 3.6 and deploying gae. https://travis-ci.org/simpeg/simpeg/jobs/210143591
![image](https://cloud.githubusercontent.com/assets/6361812/23833135/d1ed2bea-06fe-11e7-8a37-ef20cc40eebb.png)

**Comment by lheagy** [comment]
closed with #570, #557 
http://docs.simpeg.xyz/content/examples/index.html
