### ISSUE TITLE
Gravity Docs

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#556]
Could we add a `Gravity` section to the documentation? With api and brief explanation, etc.

@fourndo do you think you could give this a first pass?

**Comment by rowanc1** [comment]
There is a lot of documentation here on Mag:
http://computation.geosci.xyz/case-studies/PF/Linear_Problem_Mag.html

You probably have something hanging around for Grav @fourndo?!

**Comment by fourndo** [comment]
Oh wow, that's old. Yea for sure. Maybe for your christmas present...

**Comment by lheagy** [comment]
Lots improved with the docs work by @dccowan in #786! I will close this for now in favour of opening new issues for any more specific comments / suggestions of the Gravity docs.
