### ISSUE TITLE
Add CONTRIBUTING.rst

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#558]
![image](https://cloud.githubusercontent.com/assets/913249/23597428/05290448-01f0-11e7-8a54-9c991d6ee7d8.png)

For example:
https://github.com/simpeg/attribution/blob/master/CONTRIBUTING.rst

Needs a bit of editing though. Would like to put more info on where to ask questions as well.
Google groups, slack etc.

**Comment by lheagy** [comment]
resolved in #657
