### ISSUE TITLE
the problem with "Problem"

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#562]
I had a chat with @dougoldenburg today and he brought to light some of the confusion introduced by the term `Problem` in the framework, in particular when first introducing the SimPEG framework to new community members, which is perhaps indication of a more systemic issue. 
![image](https://cloud.githubusercontent.com/assets/6361812/23820542/accfe65c-05cf-11e7-8756-d84b39f5f2b4.png)

## Points of confusion
- often a first association with the word "Problem" is the thing you are trying to solve: the application, the reason you are considering inversion in the first place. 
- "Problem" is over-used already. "Forward Problem", "Inverse Problem"
- even in the paper, we use "problem" to mean two different things \cite{SimPEGpaper}

![image](https://cloud.githubusercontent.com/assets/6361812/23820586/8d41ce30-05d0-11e7-9f40-a0da0341be2e.png)

## Potential Alternatives
- `Physics`
- `GoverningEquations`
- `PartialDifferentialEquations`
- `PDE`
- `Equations`

In looking at the current `Problem.py` and considering the construction of a forward simulation, I am (first pass!) partial to `Equations`.
- `BaseProblem` --> `BaseEquations`
- `BaseTimeProblem` --> `BaseTimeEquations`
- perhaps `Problem.py` --> `GoverningEquations.py`

Then in a module, if we consider EM
- `BaseEMequations`
- `BaseFDEMequations`
- `Maxwell3D_e(BaseFDEMequations)` 

```
from SimPEG.EM import FDEM
equations = FDEM.Maxwell3D_e(mesh)
survey = FDEM.Survey(srcList)
equations.pair(survey)  # or fwdSim = simulation(equations, survey) down the road
```

I look forward to hearing thoughts!

**Comment by lheagy** [comment]
Flipping through some presentations as well
![image](https://cloud.githubusercontent.com/assets/6361812/23837758/897ac16e-074a-11e7-8b6a-31242234efdb.png)

**Comment by fourndo** [comment]
I actually like Physics better. Makes it pretty obvious of what is supposed to be in there.
Don't like PDE, too specific.

**Comment by micmitch** [comment]
My preference would be for either Physics, but Equations would also be fine.

**Comment by lheagy** [comment]
Thanks @fourndo, @micmitch. That is fair - physics is a good descriptor. I am wondering if the structure is something along the lines of `Physics` inherits `BaseEquations` (or `BaseTimeEquations`). For example 
```
class BaseFDEM(BaseEquations):
   ...

class Maxwell_e(BaseFDEM):
   ...
```

So in terms of namespace
```
from SimPEG.EM import FDEM
physics = FDEM.Maxwell_e(mesh)
survey = FDEM.Survey(srcList)
physics.pair(survey) 
```

**Comment by lheagy** [comment]
Thoughts from a conversation with @dougoldenburg

![image](https://cloud.githubusercontent.com/assets/6361812/24819565/f1870174-1b99-11e7-8428-19d85078f4b8.png)

**Comment by lheagy** [comment]
![image](https://cloud.githubusercontent.com/assets/6361812/24922379/ed424220-1ea2-11e7-8c94-84f1a215b5e3.png)

**Comment by grosenkj** [comment]
I agree with @lheagy  last comment. 
Further, I think that the `Survey` class carries a too much weight in the current framework. For example, having to declare observed data for in inversion in `survey.dobs` instead of having it in set in `DataMisfit` or somewhere more appropriate confuses me at times. This is more relevant when using `Data` class which has `survey` as an input, but when one wants to use the data object as observed data one has to do `obs_data.survey.dobs = mkvc(obs_data)`. 

Having a dedicated `Simulation` class would clarify some of this and having it return a `Data` class would be my vote. I would also like to suggest looking at the namespace since `survey.dpred` and `inversionProblem.dpred` are a method and a `numpy.array` property, respectively. I understand how they are connected but that is not reflected in the namespace. Maybe it be worth implementing methods with prefix 

```python
sim = SimPEG.Simulation(physics, survey)
sim.eval_fields(m)
sim.calc_dpred(m)
```
to address this. I think a wider implementation of `properties` would help with this. As a disclaimer, I reference to current master branch so this does not reflect any changes that might have been done in `Combo` objective functions or elsewhere. 

In terms of a new name for `Problem`, I like `Physics`. It references nicely the Geophysics in SimPEG and is descriptive of the purpose of the class.

My 2 cents.

**Comment by rowanc1** [comment]
If we go with an extra `Simulation` class this would remove the `pair` function (which made an initial parallel implementation I did with @bsmithyman difficult, as I recall) as well as add some ambiguity about where to put the functions `calc_jvec`, `calc_fields`, `calc_dpred` etc. (maybe some better introduction of pep8 here? and standards of `calc`ulating things?).

It would probably help out with `simulation.validate()` which could do a whole lot of things to try and catch errors before running a simulation or inversion.

Something weird about the introduction of multi-parameter inversions is that you actually need not even have a `model`. All parameters could be set directly and there are no mappings at all! Making the higher-level interface for fields/data etc be empty calls; i.e. `calc_fields()`.

Another thing that is bugging me right now is if the simulation object is "stateful", that is, does it have a `simulation.model` or are those stored somewhere else? Maybe in a slightly more generic cache than we have right now on the inversion object - which does `warm_starts` so as to skip some steps in the initiation of an inversion. This could also be a better way of doing `deleteTheseOnModelUpdate` by just saying `physics.cache.set(model, 'MfSigma', MfSigma)` and `physics.cache.clear()`. The cache could have it's own settings on it for how long to remember things. This is implemented in a bunch of places including the receivers, fields and timemesh etc. If there were some better standards around this, than we could call `simulation.cache.clear()` to do a hard reset on everything.

This is a slightly bigger discussion obviously, and a bit undirected. Wanted to get my thoughts down somewhere though.

**Comment by lheagy** [comment]
I have been giving this some more thought, especially working with setting up some of the [casing simulations](https://github.com/lheagy/casingSimulations), as well as working with @prisae on plugging [empymod](https://github.com/empymod/empymod) into SimPEG. I agree that we should scrap the distinction between the `Problem` and the `Survey` in favour of a `ForwardSimulation` (or `Simulation`) which takes case of the entire simulation. In this case, the `ForwardSimulation` takes a mesh, mapping, and source / receiver list (we also need to generalize this a bit so that there is less duplication for surveys where the same receivers are being used by multiple sources, but we can discuss that separately)

Some motivating factors for removing this disctinction
- when thinking about setting up a simulation, `survey` and `problem` parameter choices are interwoven; eg. when designing a mesh in an EM problem, you need to think about skin depth / diffusion distance
- to plug in another package, they already provide a full simulation, it is really unnatural to then make arbitrary distinctions about which inputs we classify as `survey` vs `problem`
- for linear problems, there is often no distinction between fields and dpred
- serializing and deserializing a single object is less confusing than dealing with two and having to pair them
- eventually we might want to invert for survey parameters, and we should be able to interface with them in the same way we interface to physical properties

**Comment by lheagy** [comment]
Here is a sketch of an idea

```python

class PhysicsMixin(object):

    sigma, sigma_map, sigma_deriv = Props.Invertible(
        "an invertible physical property"
    )

    mu = Props.PhysicalProperty(
        "a non-invertible property",
        default=mu_0
    )

    mesh = properties.Instance(
        "the simulation mesh",
        discretize.BaseMesh
    )

    def MeSigma(self):
        # inner product matrices are on the physics Mixin 

    def fields(self, m):
        # compute the fields

    def dpred(self, m):
        # compute the predicted data

    def Jvec(self, m, v, f=None):
        # compute sensitivity times a vector

    def Jtvec(self, m, v, f=None):
        # compute the adjoint times a vector


class BaseSimulation(Props.HasModel):

    solver = properties.Instance(
        "the solver",
        pymatsolver.BaseSolver,  # or LU
        default = utils.Solver
    )

    solver_options = properties.Dictionary(
        "dictionary of solver options"
    )

    source_list = properties.List(
        "source list",
        properties.Instance(
            BaseSource
        )
    )

    def __init__(self, **kwargs):
        super(BaseSimulation, self).__init__(**kwargs)
```

Any Simulation class would then inherit both the BaseSimulation and a PhysicsMixin. 

From here, we can add some validation (eg make sure that the mesh is suitable for the physics - check skin-depth or similar) and build utilities (eg. create mesh from source parameters, etc). 

On the EM side of things, I would see a namespace along the lines of 

```python 
# imported as FDEM.Simulation
 
class BaseEMSimulation(BaseSimulation):
     # has mesh, source_list, solver, solveropts

class BaseEMMixin(BasePhysicsMixin):
     sigma, sigma_map, sigma_deriv = # ... and similar for all of the phys props and matrices

class Maxwell3DE(BasePhysicsMixin):
    # getA, RHS, etc for what is currently problem E

class Simulation3DE(BaseEMSimulation, Maxwell3DE):
    # performs functionality of Problem3D_e right now

```

**Comment by lheagy** [comment]
On further thought, I think the `Mixin` is overkill. We can just put that in the simulation

**Comment by lheagy** [comment]
Over in opengeophysics/objectivefunction#3, we are talking about removing the need to pass the fields around in the objective function (specifically, in the data misfit). In that case, we would need to stash the fields on the simulation. I think that is within scope of this refactor.

TODO:
- [ ] stash fields on simulation (clear on model update)
- [ ] remove need to pass around fields in objective functions

**Comment by prisae** [comment]
This is only loosely related to this issue. But I would very much appreciate your feedback.

I created an issue related to `Survey` and `Model` classes in a potential future version of `empymod`: https://github.com/empymod/empymod/issues/14.

I would highly appreciate any of your thoughts and ideas, specifically from you experience with `SimPEG`. One benefit could be that it would be easier to implement `empymod` into `SimPEG`, if I follow a similar set-up as `SimPEG`.
