### ISSUE TITLE
Common structure for examples

### ISSUE THREAD

**Issue by ahartikainen** [simpeg/simpeg#564]
All the examples should follow a common structure / workflow. All the steps should be explicit and the non-obvious variables have a comment. They should show what are the best practices with SimPEG.

Forward simulation examples can skip the inverse parts.

Inversion examples should have its data creation as a separate part with a better resolution mesh (offset to main mesh) to handle the inverse crime.

For example, each step in in following diagram should be addressed. 

[Inversion Workflow](http://docs.simpeg.xyz/_images/InversionWorkflow.png)
<img src="http://docs.simpeg.xyz/_images/InversionWorkflow.png" width="400">

TBD:

The main steps could be: 

`# Data input`
`# Mesh creation`
`# Forward simulation` / `# Forward model`
`# Inverse elements` / `# Inverse setup`
`# Inversion`

**Comment by rowanc1** [comment]
Thanks for the issue @ahartikainen, and calling out our examples. They are for sure a first pass.

We have been working on a few resources here:
https://github.com/geoscixyz/computation

It is early days on that repo, but something to keep an eye on. http://geosci.xyz is our stab at open access geoscience textbook like resources.

Fundamentals:
http://em.geosci.xyz/content/maxwell2_static/fields_from_grounded_sources_dcr/electrostatic_sphere.html

Case studies:
http://em.geosci.xyz/content/case_histories/mt_isa/index.html#mt-isa-index

Better examples in SimPEG or linked through to a reproducible textbook, especially ones that follow the framework diagram is for sure on the roadmap. If you have worked through any of the examples, and cleaned anything up: PRs are always welcome!

Thanks again for making this an explicit issue.

**Comment by fourndo** [comment]
@ahartikainen : I don't totally agree with the "inverse crime". The issue of a bad mesh that can't exactly make the true model is sort of an extra level of complications. We first need to have the best code possible in a best case scenario before we can tackle the harder problem. And we won't see all the OTHER issues, if on top of it the mesh is bad.
But I get the point. I think real data (case studies) are best to that kind of complication... my two cents.

**Comment by lheagy** [comment]
It took us a while to get moving in this direction, but with a huge(!) thanks to @dccowan, the tutorials section of the SimPEG docs are much more consistent with the merge of #786: http://docs.simpeg.xyz/. 

I will close this, but feel free to take a look and re-open if you have further suggestions!
