### ISSUE TITLE
Octree model sections

### ISSUE THREAD

**Issue by micmitch** [simpeg/simpeg#575]
I have set up a small problem for testing the regularization operators on an octree mesh using a DC problem. This small problem (~50,000 cells) inverts in about 10 min but it takes almost as long for it to generate a 3 panel plot of model sections. I'm assuming this has something to do with interpolation. Any thoughts on how we could potentially speed this up?

**Comment by lheagy** [comment]
Thanks @micmitch. I am going to close this issue here and move the conversation over to simpeg/discretize#45 as that is where the octree and associated visualization code lies
