### ISSUE TITLE
Survey unpickle issues

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#582]
I am trying to un-pickle a `Survey` object via `dill` and get this error:

![image](https://cloud.githubusercontent.com/assets/6052367/24984483/85ccdf78-1fa2-11e7-828e-5c34052d4ddd.png)

In debug mode, I can see that the object in the last error is a `SimPEG.EM.NSEM.SrcNSEM.Planewave_xy_1Dprimary` object.
I have test `pickle` and `cPickle` but they all give the same error. Any idea's what this might be?

(This applies to freshly pickled objects)

**Comment by lheagy** [comment]
This will be resolved with #786

**Comment by jcapriot** [comment]
In my testing this appears to no longer be an issue.
