### ISSUE TITLE
e from DC.Problem3D_CC 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#584]
## Problem 
The way the electric field, `e` is being calculated from `phi` in `DC.Problem3D_CC` is incorrect when we have cell size changes (in the below image, you can see where the cells start to extend). It is currently being calculated as 
```
-self.cellGrad*phiSolution
```
![image](https://cloud.githubusercontent.com/assets/6361812/25075717/a561f5a6-22ce-11e7-9b91-7aceb990efcd.png)
(and error plot)
![image](https://cloud.githubusercontent.com/assets/6361812/25075843/3b270ada-22d0-11e7-9d36-976c14a13e3e.png)

## Proposed Solution
I propose using 
```
n = int(self._aveF2CCV.shape[0] / self._nC)  # number of components
VI = utils.sdiag(1./np.kron(np.ones(n), prob3D.mesh.vol))   
return VI * (self._aveF2CCV * (self._MfRho * self._j(jSolution, srcList)))
```
(similar to the implementation in the FDEM problem), which produces fields that are more consistent with the analytic solution for a dipole
![image](https://cloud.githubusercontent.com/assets/6361812/25075721/afc7f040-22ce-11e7-8854-34df4e7c0f11.png)

(and here is the error plot)
![image](https://cloud.githubusercontent.com/assets/6361812/25075729/c44a95d6-22ce-11e7-9a6c-c6f801f7ea50.png)

cc @sgkang 
* Note: all colorbars are fixed to the same rage (1e-8 to 1e-1)

**Comment by sgkang** [comment]
Interesting. Agree with you. Implementation of `e` and `j` were visual purpose for DC case, but
did not we have that significant error. Can we substitute `VI * self._aveF2CCV` to `MfI`?

**Comment by lheagy** [comment]
Yes, we can use MfI instead - and we can update that in the EM code as well.

**Comment by lheagy** [comment]
I am currently updating this on the em cyl branch, which I am hoping to get cleaned up and into em dev by the end of the week. 

we can also update the em fields objects for consistency here too

**Comment by sgkang** [comment]
K. That sounds great to me. Do you want me to fix Static part?

**Comment by lheagy** [comment]
I have updated it on the `em/feat/3Dcyl`, but haven't pushed it yet, I will tag you in the pr once I have it ready :)

**Comment by sgkang** [comment]
That sounds great. Thx @lheagy !!

**Comment by sgkang** [comment]
Fixed. See #650
