### ISSUE TITLE
remote download default

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#596]
Right now, the remote download defaults to the current working directory. Do we want it here? or should it default to your Downloads folder?

cc @fourndo, @rowanc1

**Comment by lheagy** [comment]
or at the very least, we should have an option that allows you to specify that you want it going to your downloads folder so that we don't need to be doing this in scripts / notebooks (it is an intimidating way to start a tutorial!) 
```
basePath = os.path.sep.join(
    os.path.abspath(os.getenv('HOME')).split(
        os.path.sep
    )['Downloads']+['SimPEGtemp']
)
```

**Comment by fourndo** [comment]
I say go for it like you proposed
```remoteDownload(url, cloudfiles, downloads_folder=True)``

**Comment by lheagy** [comment]
cool, for naming of variables, does the following work for you? I think it is a little more standard
```
def remoteDownload(url, remoteFiles, path='.', directory='SimPEGtemp', rm_previous=False)
```

(where `rm_previous` is either `True` or `False` and if a directory with the specified name already exists and `rm_previous` is `True`, that directory will be deleted and then written over)

**Comment by ahartikainen** [comment]
(You can ignore this comment)

Why there needs to be a default path?

**Comment by lheagy** [comment]
@ahartikainen: we have changed it so that the default path is the local directory (we need to specify a place to download the file to)

**Comment by lheagy** [comment]
the default `folder` is not `.` (the current working directory). These changes were made in #598
