### ISSUE TITLE
Mapping derivative output is expected to be a matrix instead of a Matrix-Vector product

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#608]
Mapping derivative output is expected to be a matrix instead of a Matrix-Vector product.
This prevents us to implement linear functional mappings such as FFT, Wavelets, Direct Cosine Transform...

**Comment by rowanc1** [comment]
You could take a look at `LinearOperators` in scipy:
https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.sparse.linalg.LinearOperator.html

These should act exactly like spare matrices, but be able to do what you are looking for. Easy to implement as well!

**Comment by thast** [comment]
I am closing this as there hasn't been discussion in a long time. Please feel free to re-open if you have further comments to add.
