### ISSUE TITLE
namespace of objective function

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#609]
![image](https://user-images.githubusercontent.com/6361812/26852979-fe5a72c8-4ac4-11e7-967a-2e5af887a3bd.png)

**Comment by rowanc1** [comment]
Was the final decision `misfit.functions`? or `reg.functions`?

**Comment by lheagy** [comment]
@rowanc1, effectively both. We still have `reg`, `misfit`, (both inheriting from base combo objective function) each of those then has a `functions` property that just keeps track of the functions that make it up (previously we had that reg has objective functions, `reg.objfcts`, but really, at the end of the day the thing that we call an `objective_function` is really the statement of the inverse problem
