### ISSUE TITLE
Directives: more general SaveOutputDictEveryIteration 

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#610]
Directives.SaveOutputDictEveryIteration is broken right now and too specific to Tikonov Regularization.

@lheagy proposal for fixing it:
`
outDict['regularization'] = [fct(self.invProb.model) for fct in self.reg.functions]
outDict['alphas'] = self.reg.multipliers
`

**Comment by lheagy** [comment]
Currently, there are two directives that do almost the same thing: `SaveOutputEveryIteration` and `SaveOutputDictEveryIteration`. I suggest we consolidate these to one directive `SaveOutputEveryIteration` that has a `save_as="txt"`, or `save_as="dict"`. Thoughts @sgkang, @grosenkj, @thast ?

**Comment by thast** [comment]
Mentionned at the latest meeting @lheagy @fourndo
