### ISSUE TITLE
ref attribute missing for TextField

### ISSUE THREAD

**Issue by lobosan** [simpeg/simpeg#624]
Hi, I usually work with ref for all my jsx form elements instead of using id, because sometimes I might use the same id without knowing in different components which will cause problems, whereas ref has a local scope related to the component so it doesn't matter if I use the same ref in several components

Is there any way to include ref attribute for all input components?

**Comment by rowanc1** [comment]
I am not sure if this was posted on the correct github repo. Please comment/clarify if it was intended for SimPEG.

**Comment by lobosan** [comment]
Yeah sorry about that, not sure what happened hehe
