### ISSUE TITLE
Bug in creating and/or plotting Tree meshes

### ISSUE THREAD

**Issue by dccowan** [simpeg/simpeg#632]
I have noticed that the x0 position in Tree mesh objects is not respected. As a result, some of the following occurs:

- You can create a tree mesh object where x0 isn't the origin. However when you want to plotGrid(), it ALWAYS plots with x0=(0,0,0). This is strange given that you can use meshObj.x0 to verify that the bottom southwest corner is not at the origin.
- If you want to refine the mesh using meshObj.refine(), it doesn't take into account the x0 position.
- When you want to create a model, it DOES take into account the x0 position. Which means the model looks right, but gets shifted over when you plot it.

I have a feeling that this is a pretty easy fix. I just don't know where to find the specific lines of code.

**Comment by lheagy** [comment]
Thanks @dccowan, do you have an example you provide that reproduces this bug?

**Comment by dccowan** [comment]
#########################
# EXAMPLE PYTHON CODE

from SimPEG import Mesh
import numpy as np
import matplotlib.pyplot as plt

bcs = 1. # Base (smallest) cell size
nbc = 4096 # Number of base cells 
hbx = bcs*np.ones(nbc) # Set cell widths for base mesh
hbz = bcs*np.ones(nbc)

# SET MESH DOMAIN
# Smallest cell width is _____ and the domain is as wide as _____ of those cells.

meshObj = Mesh.TreeMesh([hbx,hbz],'CC')

# Refine all cells to a minimum factor of 3
meshObj.refine(3)

def refinefcn(cell):
    xyz = cell.center
    dist = ((xyz - [2048.,1800.])**2).sum()**0.5
    if dist < 1150.:
        return 5
    return 3

meshObj.refine(refinefcn)
   
def refinefcn(cell):
    xyz = cell.center
    if (xyz[0] > 2048-300.) & (xyz[0] < 2048+300.) & (xyz[1] > 2048-600.) & (xyz[1] < 2048+100.):
        return 7
    return 3

meshObj.refine(refinefcn)

sig_air = 1e-8
sig_hs = 1e-3
sig_block = 1e0
    
mod = sig_air*np.ones(meshObj.nC)
mod[meshObj.gridCC[:,1]<0.] = sig_hs
mod[(meshObj.gridCC[:,1]<0.) & 
    (meshObj.gridCC[:,1]>-500.) &
    (meshObj.gridCC[:,0]<1000.) &
    (meshObj.gridCC[:,0]>-1000.)] = sig_block


fig1 = plt.figure(figsize=(10,8))
Ax1 = fig1.add_axes([0,0,1,1])
meshObj.plotGrid()
meshObj.plotImage(np.log10(mod))

**Comment by lheagy** [comment]
@rowanc1: would you be able to take a look at this?

**Comment by lheagy** [comment]
This issue was moved to simpeg/discretize#71
