### ISSUE TITLE
add .ipynb to gitignore

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#634]
we should add .ipynb to the gitignore - notebooks are out-of-scope for this repo. In the past we have had some notebooks be committed which adds a large volume of code to the log that is later removed

**Comment by SauravMaheshkar** [comment]
@lheagy isn't `*.ipynb` already present in the `.gitignore` file ? viz.

https://github.com/simpeg/simpeg/blob/dd4b904d8cf707b320e3a4391357458b8bd28472/.gitignore#L71

**Comment by jcapriot** [comment]
We still have a decent amount of old bug reports that should be closed, thanks for catching this.

**Comment by lheagy** [comment]
Thanks both!!
