### ISSUE TITLE
install simpeg in windows error: failed building wheel for discretize

### ISSUE THREAD

**Issue by jiajiasun** [simpeg/simpeg#639]
I was trying to install SimPEG on my new windows 10 machine using pip install simpeg, and got an error message that reads 'failed building wheel for discretize'. 

Anyone has any idea about what might have gone wrong here?

BTW1, I was able to install python, numpy, scipy, scikit-learn, matplotlib without any trouble.
BTW2, yesterday I ran into a similar error message when I was installing obspy that reads 'failed building wheel for obspy'.

Maybe something wrong with my wheel? But I did install wheel successfully by pip install wheel.

**Comment by fourndo** [comment]
Hi Jiajia!
Glad to have you on board.
Very most likely because of the c++ library. I think if you go higher in the installation prompt you should see a warning about visual c++

https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads

Has to do with c-compiled code to speedup python.
Let me know how that works for you.

**Comment by jiajiasun** [comment]
Hi

**Comment by jiajiasun** [comment]
Hi @fourndo !
SimPEG is great! I plan to use that in my class here at UH. Thank you for answering my question!

I installed the latest Microsoft Visual C++ redistributable following the link you provided, restarted my computer and re-installed SimPEG, still got the same error message ...

It is unlikely that my problem had to do with visual c++, the reason being that I got my computer about 3 days ago and I installed the 2018 Intel Parallel Studio XE (with everything that could be possibly installed). I also installed the latest Microsoft Visual Studio Professional 2017.

Maybe I should go buy a Mac ...

**Comment by jiajiasun** [comment]
I think I just accidentally closed something :) My first time posting in GitHub.

**Comment by jcapriot** [comment]
Jiajia, can you try installing the discretize package on its own and posting the error on that packages github page?

**Comment by lheagy** [comment]
Hi @jiajiasun, Glad you are planning to use SimPEG in your course! 

We are working on simplifying the installation steps for windows (@sgkang has been looking into getting discretize on conda-forge simpeg/discretize#69), but at the moment windows can still be a bit tricky.  

How do you have python installed? did you use anaconda? https://www.anaconda.com/download/

**Comment by jiajiasun** [comment]
@jcapriot Hi, Joe! Thanks for your reply! Yes, l will do that on Monday (computer sits in my office) and let you know how it goes.

**Comment by jiajiasun** [comment]
@lheagy Hi, Lindsey! Thanks for reply! I installed Python in a very simply way. I went to this webpage https://www.python.org/downloads/windows/ and downloaded windows x86-64 executable installer for Python 3.6.2 and simply followed the instructions in the wizard (basically, I just clicked a bunch of yes!).

Then, I installed numpy, scipy, scikit-learn and matplotlib by typing pip install numpy etc in a cmd window that ran as an administrator (because pip was already installed together with python 3.6)

**Comment by jiajiasun** [comment]
@fourndo @jcapriot @lheagy Interesting. I tried installing simpeg in my wife's laptop (mine was dead, so I was using hers for Python coding for a few weeks) that runs Windows 10, and I pulled it off! I did run into one minor problem related to visual c++, but it was easily solved by downloading Microsoft Visual c++ 2015 package). 

BTW, I installed python, numpy, scipy, etc on her laptop just two weeks ago the way I did on my desktop at school.

So, the problem might not be the discretize and the failure to build wheel for discretize.

I will re-install Python and everything else related on Monday after I go back to work. I am somehow confident that I will succeed. 

Thank you all for help! I will keep you posted.

**Comment by jiajiasun** [comment]
I think I know how to solve the problem.

Per @jcapriot 's advice, I tried installing discretize using the wheel file from https://pypi.python.org/pypi/discretize/, and got an error message saying that this wheel 'is not a supported wheel on this platform'. I guess it is because I am using Python 3.6 on my desktop whereas this wheel is intended for Python 2.7 users.

So, I guess if any of you could develop a wheel file for discretize that is compatible withPython 3.6, the problem will be solved.

On  a different note, I ran into the same error message "failed building a wheel for obspy " when I tried to install obspy on my desktop. Accidentally and luckily, I found the wheel for obspy on http://www.lfd.uci.edu/~gohlke/pythonlibs/.  I installed obspy wheel on its own before I pip install obspy. It worked! 

It appears to me that, the problem with my installing simpeg is the same as the problem I ran into with obspy. I successfully installed obspy by using its wheel (version cp36). It therefore seems to me that, upgrading wheel file for discretize to cp36 should also solve my problem with simpeg.

**Comment by lheagy** [comment]
@jiajiasun: any luck???

**Comment by jiajiasun** [comment]
@lheagy I will need to build a wheel package for discretize in Python 3.6. Still tryting to figure out how to do it. I am attending SEG now. Will look into this later.

**Comment by thast** [comment]
Another issue some of us had, that might be of some help here:
https://github.com/simpeg/discretize/issues/76

**Comment by thast** [comment]
Hi @jiajiasun, Solving the issue I posted above, I was able to reinstall SimPEG and discretize on Windows 10 Machine from scratch. I have created a .whl for discretize on Windows with Python 3.6. You can get it at the link below. Hope this will hep. Cheers.
https://www.dropbox.com/s/pvrbpxmay9ln52v/discretize-0.1.10b0-cp36-cp36m-win_amd64.whl?dl=0

**Comment by jiajiasun** [comment]
@thast I just installed the wheel package for discretize, as well as SimPEG, and it worked beautifully!!! You are awesome!! How did you do it? I was trying to figure that out.
@lheagy we probably need to put the wheel package (created by @thast) somewhere (that is more visible to people) so that others who run into the same problem in windows would have access to it.

**Comment by thast** [comment]
Awesome! Glad it works! Welcome on board!
To create a wheel file, once yo have cloned the repository, you can run (in the repository) the command line `python setup.py bdist_wheel`. I first had errors seemed associated with the compiler, but everything got solved once running the beta version of `properties` (but I still ended up using the `MinGW` compiler for it, but not sure if it did change anything at the end).
@lheagy: I think .whl files can also be distributed through PyPi and `pip`?

**Comment by lheagy** [comment]
Thanks @thast: yes, they can be distributed through pypi - we should be able to do that from appveyor automatically (runs the tests on windows)

**Comment by paoman86** [comment]
I was trying to install SimPEG after installing Anaconda3 but got the same error about building a wheel for discretize.
I installed the C++ libraries from the link suggested in the SimPEG page
I also follwoed solution proposed for discretize issue 69 and discretize 0.1.1 was installed correctly but when trying to properly install SimPEG it removed the 0.1.1 version to install the 0.3.8 version of discretize and get me to the same error (it follows)
Is there a way to solve this?
Thank you!!

Failed building wheel for discretize
  Running setup.py clean for discretize
Failed to build discretize
Installing collected packages: vectormath, utm, geoana, discretize, SimPEG
  Running setup.py install for discretize ... error
    Complete output from command C:\Users\musta\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\musta\\AppData\\Local\\Temp\\pip-install-3efammc2\\discretize\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\musta\AppData\Local\Temp\pip-record-wzi1ht_m\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "discretize.tree_ext" sources
    building extension "discretize.utils.interputils_cython" sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\discretize
    copying discretize\BaseMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\CurvilinearMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\CylMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\DiffOperators.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\InnerProducts.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\MeshIO.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\setup.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\TensorMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\Tests.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\TreeMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\View.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\__init__.py -> build\lib.win-amd64-3.7\discretize
    creating build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\codeutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\coordutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\curvutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\interputils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\io_utils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\matutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\meshutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\setup.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\__init__.py -> build\lib.win-amd64-3.7\discretize\utils
    creating build\lib.win-amd64-3.7\discretize\mixins
    copying discretize\mixins\vtkModule.py -> build\lib.win-amd64-3.7\discretize\mixins
    copying discretize\mixins\__init__.py -> build\lib.win-amd64-3.7\discretize\mixins
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'discretize.tree_ext' extension
    compiling C sources
    creating build\temp.win-amd64-3.7\Release\discretize
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\include -IC:\Users\musta\Anaconda3\include /EHsc /Tpdiscretize\tree_ext.cpp /Fobuild\temp.win-amd64-3.7\Release\discretize\tree_ext.obj /Zm1000
    error: Command "cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\include -IC:\Users\musta\Anaconda3\include /EHsc /Tpdiscretize\tree_ext.cpp /Fobuild\temp.win-amd64-3.7\Release\discretize\tree_ext.obj /Zm1000" failed with exit status 127


    ----------------------------------------
Command "C:\Users\musta\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\musta\\AppData\\Local\\Temp\\pip-install-3efammc2\\discretize\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\musta\AppData\Local\Temp\pip-record-wzi1ht_m\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\musta\AppData\Local\Temp\pip-install-3efammc2\discretize\

**Comment by fourndo** [comment]
@paoman86 : Can you try to re-install VS with the one provided in issue #750

**Comment by paoman86** [comment]
Thank you @fourndo for the help but still having an error concerning the fatal error C1083 ... 'io.h': No such file or directory:
...
Building wheels for collected packages: discretize
  Running setup.py bdist_wheel for discretize ... error
  Complete output from command C:\Users\musta\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\musta\\AppData\\Local\\Temp\\pip-install-hks4zigh\\discretize\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\musta\AppData\Local\Temp\pip-wheel-6urk9eg2 --python-tag cp37:
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "discretize.tree_ext" sources
  building extension "discretize.utils.interputils_cython" sources
  build_src: building npy-pkg config files
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\discretize
  copying discretize\BaseMesh.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\CurvilinearMesh.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\CylMesh.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\DiffOperators.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\InnerProducts.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\MeshIO.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\setup.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\TensorMesh.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\Tests.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\TreeMesh.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\View.py -> build\lib.win-amd64-3.7\discretize
  copying discretize\__init__.py -> build\lib.win-amd64-3.7\discretize
  creating build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\codeutils.py -> build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\coordutils.py -> build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\curvutils.py -> build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\interputils.py -> build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\io_utils.py -> build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\matutils.py -> build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\meshutils.py -> build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\setup.py -> build\lib.win-amd64-3.7\discretize\utils
  copying discretize\utils\__init__.py -> build\lib.win-amd64-3.7\discretize\utils
  creating build\lib.win-amd64-3.7\discretize\mixins
  copying discretize\mixins\vtkModule.py -> build\lib.win-amd64-3.7\discretize\mixins
  copying discretize\mixins\__init__.py -> build\lib.win-amd64-3.7\discretize\mixins
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  Missing compiler_cxx fix for MSVCCompiler
  customize MSVCCompiler using build_ext
  building 'discretize.tree_ext' extension
  compiling C sources
  creating build\temp.win-amd64-3.7\Release\discretize
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\include -IC:\Users\musta\Anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" /EHsc /Tpdiscretize\tree_ext.cpp /Fobuild\temp.win-amd64-3.7\Release\discretize\tree_ext.obj /Zm1000
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\include -IC:\Users\musta\Anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" /EHsc /Tpdiscretize\tree_ext.cpp /Fobuild\temp.win-amd64-3.7\Release\discretize\tree_ext.obj /Zm1000" failed with exit status 2
  tree_ext.cpp
  c:\users\musta\anaconda3\include\pyconfig.h(59): fatal error C1083: Non Š possibile aprire il file inclusione: 'io.h': No such file or directory

  ----------------------------------------
  Failed building wheel for discretize
  Running setup.py clean for discretize
Failed to build discretize
Installing collected packages: discretize
  Running setup.py install for discretize ... error
    Complete output from command C:\Users\musta\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\musta\\AppData\\Local\\Temp\\pip-install-hks4zigh\\discretize\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\musta\AppData\Local\Temp\pip-record-qfoezc0a\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "discretize.tree_ext" sources
    building extension "discretize.utils.interputils_cython" sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\discretize
    copying discretize\BaseMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\CurvilinearMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\CylMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\DiffOperators.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\InnerProducts.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\MeshIO.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\setup.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\TensorMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\Tests.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\TreeMesh.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\View.py -> build\lib.win-amd64-3.7\discretize
    copying discretize\__init__.py -> build\lib.win-amd64-3.7\discretize
    creating build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\codeutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\coordutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\curvutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\interputils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\io_utils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\matutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\meshutils.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\setup.py -> build\lib.win-amd64-3.7\discretize\utils
    copying discretize\utils\__init__.py -> build\lib.win-amd64-3.7\discretize\utils
    creating build\lib.win-amd64-3.7\discretize\mixins
    copying discretize\mixins\vtkModule.py -> build\lib.win-amd64-3.7\discretize\mixins
    copying discretize\mixins\__init__.py -> build\lib.win-amd64-3.7\discretize\mixins
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'discretize.tree_ext' extension
    compiling C sources
    creating build\temp.win-amd64-3.7\Release\discretize
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\include -IC:\Users\musta\Anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" /EHsc /Tpdiscretize\tree_ext.cpp /Fobuild\temp.win-amd64-3.7\Release\discretize\tree_ext.obj /Zm1000
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users\musta\Anaconda3\include -IC:\Users\musta\Anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" /EHsc /Tpdiscretize\tree_ext.cpp /Fobuild\temp.win-amd64-3.7\Release\discretize\tree_ext.obj /Zm1000" failed with exit status 2
    tree_ext.cpp
    c:\users\musta\anaconda3\include\pyconfig.h(59): fatal error C1083: Non Š possibile aprire il file inclusione: 'io.h': No such file or directory

    ----------------------------------------
Command "C:\Users\musta\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\musta\\AppData\\Local\\Temp\\pip-install-hks4zigh\\discretize\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\musta\AppData\Local\Temp\pip-record-qfoezc0a\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\musta\AppData\Local\Temp\pip-install-hks4zigh\discretize\

**Comment by fourndo** [comment]
Hmmm strange. Just tried to re-install here without issue.
Can you try to upgrade all your libraries
``conda update --all``

then try the install again

**Comment by fourndo** [comment]
And just to make sure, you've installed VS Community with the C++ module, yes?
![image](https://user-images.githubusercontent.com/2406426/51570740-c99b6000-1e54-11e9-9dfc-5ce23c164022.png)

**Comment by paoman86** [comment]
Finally I managed to install it correctly. Here the procedure that worked on my win10:
installed anaconda3
Installed the visual studio community 2017 set as from the previous screenshot
installed the Visual C++ libraries from
https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads
Thanks to @fourndo for the help

**Comment by fourndo** [comment]
Glad to hear. 
Welcome aboard.
