### ISSUE TITLE
PEP8 linter install for windows (add instructions to website)

### ISSUE THREAD

**Issue by dccowan** [simpeg/simpeg#643]
Instructions for installing and activating the pep8 linter for windows have been made. For this to work, you MUST have sublime text 3. The steps are as follows:

STEP 1: INSTALL SUBLIME LINTER 3
* Opem sublime text 3
* Open the Command Palette (cmd+shift+p on Mac OS X, ctrl+shift+p on Linux/Windows).
* Type 'install' and select 'Package Control: Install Package' from the Command Palette. There will be a pause of a few seconds while Package Control finds the available packages.
* When the list of available packages appears, type 'linter' and select 'SublimeLinter'. Note: The github repository name is “SublimeLinter3”, but the plugin name remains “SublimeLinter”.
* After a few seconds SublimeLinter will be installed and loaded. Depending on your setup, you may see some prompts from SublimeLinter. For more information on SublimeLinter’s startup actions, see Startup actions. You will see an install message.
* After reading the message, close Sublime Text 3

STEP 2: INSTALL PEP8 LINTER
* Open sublime text 3
* Open the Command Palette (cmd+shift+p on Mac OS X, ctrl+shift+p on Linux/Windows).
* Type 'install' and select 'Package Control: Install Package' from the Command Palette. There will be a pause of a few seconds while Package Control finds the available packages.
* When the list of available packages appears, type 'pep8' and select the appropriate option.
* After a few seconds pep8 linter will be installed and loaded. Depending on your setup, you may see some prompts from SublimeLinter. For more information on SublimeLinter’s startup actions, see Startup actions. You will see an install message.
* After reading the message, close Sublime Text 3

The next time you open a .py file in sublime text 3, the linter should be activated.

**Comment by lheagy** [comment]
Hi @dccowan, would you be willing to add this to the docs? It could be included in the ["Text Editors"](http://docs.simpeg.xyz/content/api_core/api_getting_started_developers.html#text-editors) section of the Getting Started for Developers. 

The docs are rst, just as is for em geosci and the gpg. The page you can edit is here: 

https://github.com/simpeg/simpeg/edit/master/docs/content/api_core/api_getting_started_developers.rst

**Comment by lheagy** [comment]
if you are willing to champion this, could you assign yourself to the issue?

**Comment by lheagy** [comment]
this closed with #644
