### ISSUE TITLE
DC examples 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#647]
Right now, we are a bit sparse on examples for DC. We have a 1D inversion, an analytic and a forward simulation. Having a 3D inversion would be very valuable to (a) show that SimPEG can do a 3D DC inversions, (b) demonstrate a more practical use of the code. There was interest at exploration '17 in using SimPEG to invert DC data, but if someone just looks at the docs, it isn't clear that this is even possible. 

@thast, @micmitch, and @sgkang mentioned that they have examples that they could contribute. To prevent repetition of work, would you guys mind giving a short description on what you are thinking?

**Comment by thast** [comment]
Already done, I have a two-cylinder example in 2D.
I am converting it right now to a 2-spheres examples in 3D.
This will come with an update to the `DCUtils.gen_DCIPsurvey()`, an utils that create my Dipole-Dipole survey.

**Comment by thast** [comment]
Just created a branch `example/dcip_inversions` for the purpose of this issue.

**Comment by thast** [comment]
#648
