### ISSUE TITLE
Storing sensitivity option for DC problem

### ISSUE THREAD

**Issue by sgkang** [simpeg/simpeg#653]
- [x] Implement `getJ` function (bascically similar to Jtvec)
- [x] Make sure it updates for each iteration
- [x] For both 3D and 2.5D problem

**Comment by sgkang** [comment]
![image](https://user-images.githubusercontent.com/6054371/33156089-20491c66-cfab-11e7-8d51-3f426582cd5e.png)
@micmitch  @fourndo Here's  a result with sensitivity weighting

**Comment by sgkang** [comment]
This will be closed when it merged to `master` branch

**Comment by fourndo** [comment]
Geez wow ok. This is getting a pretty stellar inverse algo man. 
Is it sparse too or something?

**Comment by fourndo** [comment]
Beauty, Tree is right at reach. We can re-group tomorrow.

![image](https://user-images.githubusercontent.com/2406426/33160737-9978d82e-cfd3-11e7-964d-5f3560bfbd29.png)

**Comment by lheagy** [comment]
@sgkang: can this issue be closed? it was addressed in #650??

**Comment by sgkang** [comment]
yes it's done deal.
