### ISSUE TITLE
Codacy improvements

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#662]
Here are some thoughts after the work on PR #650:

- Examples are not taken into account for the coverage. Maybe we have an opportunity here to use them as test as well (maybe by making each one a class with a `run()` function and then create a `test_examples.py`)

- Testing Plotting functions has proven challenging to test. Right now, most of them are not covered. 
  - Even without any `plt.show()` or `plt.tight_layout()`, or  with a function only acting on an `matplotlib.pyplot.axes` object, Tests were still failing on Travis (`No display variable`). 
  - Curious enough, this `No display variable` problem does not seem an issue when running the examp
  - The Pieces are there, but in most tests, we put an `if plotIt:` statement, and `plotIt` is set to `False` for all automatic tests.

What are people thought about it? @lheagy  @rowanc1  @sgkang

**Comment by prisae** [comment]
Matplotlib plots can be tested with `pytest` and the `-mpl`-flag. I don't know if there is a move planned once to `pytest` (`numpy` just did), but together with this one could start testing plots.

**Comment by prisae** [comment]
(This comment only indirect affects the coverage issue which @thast mentioned, but is more related to the used testing framework, not coverage framework.)

**Comment by lheagy** [comment]
Yeah... I have been looking at pr #698, and pytest does seem to be much more transparent.

**Comment by jcapriot** [comment]
I do not believe this is an issue anymore, we have switched to pytest, and we are able to plot matplotlib plots during the testing, (at the very least by first making an Agg backend for matplotlib).

Also the tutorials and examples are run now as tests which will collect coverage information.
