### ISSUE TITLE
SaveOutputEveryIteration Directive errors

### ISSUE THREAD

**Issue by micmitch** [simpeg/simpeg#663]
Can no longer use the SaveOutputEveryIteration directive on the the dcip/dev branch. I get the following error when calling this function using Tikhonov regularization on a treemesh.
```
SimPEG.InvProblem is setting bfgsH0 to the inverse of the eval2Deriv.
    ***Done using same Solver and solverOpts as the problem***
Use Tikhonov
SimPEG.SaveOutputEveryIteration will save your inversion progress as: '###-InversionModel-2017-12-20-12-06.txt'
SimPEG.SaveModelEveryIteration will save your models as: '###-InversionModel-2017-12-20-12-06.npy'
model has any nan: 0
============================ Inexact Gauss Newton ============================
  #     beta     phi_d     phi_m       f      |proj(x-g)-x|  LS    Comment   
-----------------------------------------------------------------------------
x0 has any nan: 0
   0  1.22e-01  1.64e+05  7.60e+01  1.64e+05    2.35e+05      0              
Traceback (most recent call last):
  File "InvScript.py", line 225, in <module>
    mopt = inv.run(m0)
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Utils/CounterUtils.py", line 99, in wrapper
    out = f(self, *args, **kwargs)
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Inversion.py", line 67, in run
    self.m = self.opt.minimize(self.invProb.evalFunction, self.invProb.model)
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Utils/CounterUtils.py", line 99, in wrapper
    out = f(self, *args, **kwargs)
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Optimization.py", line 291, in minimize
    self.doEndIteration(xt)
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Utils/CounterUtils.py", line 88, in wrapper
    out = f(self, *args, **kwargs)
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Utils/codeutils.py", line 144, in wrapper
    return f(self,*args,**kwargs)
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Optimization.py", line 564, in doEndIteration
    self.callback(xt)
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Inversion.py", line 73, in _optCallback
    self.directiveList.call('endIter')
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Directives.py", line 170, in call
    getattr(r, ruleType)()
  File "/tera_raid/mmitchel/Programs/simpeg/SimPEG/Directives.py", line 351, in endIter
    self.reg.objfcts[0](self.invProb.model) * self.reg.alpha_s
AttributeError: 'ComboObjectiveFunction' object has no attribute 'alpha_s'
```

**Comment by fourndo** [comment]
Makes sense since everything is combo now.
Will need to change the saved values as dictionaries.
@sgkang : I think you are the author of this. Are you ok with the change?

**Comment by thast** [comment]
I did play with this function on my branch. I will try my modifications Tuesday or Wednesday and submit it if it works.

**Comment by thast** [comment]
@micmitch : can you share your script?

**Comment by thast** [comment]
A possible workaround is to replace in the function `self.reg` by `self.invProb.reg` and everything is back to expected behavior.

@fourndo : can you enlighten me why here 
 `type(self.reg) = ObjectiveFunction.ComboObjectiveFunction`
 while 
`type(self.invProb.reg) = Regularization.Simple` (or `Regularization.Tikhonov`)

Not sure that I get why they should be different... (if they should) Thanks!

**Comment by fourndo** [comment]
The idea is to turn all the inversion blocks into ComboObjectives for the Directives, if it is not a Combo already. That way we can loop over lists everywhere, and won't need to check every time if it is a combo or not.

`self.reg` is a combo, so in your case, you can access the same object that is stored in `self.invProb.reg` by calling `for reg in self.reg.objfcts`. So the first (and only) element of the Combo is the regularization that you used in the `invProb`.  

Might sound over complicated in this case, since you only have one reg, but it makes the Directives a lot simpler when you start adding up multiple regularization together.

**Comment by thast** [comment]
@fourndo: I understand we want to be able to handle several regularizers. What I am less sure about, and not a big fan so far, is the discrepancy between the type of object when calling `*.reg`. 

Moreover, This also create inconsistency of interaction (as reported by @micmitch ) and naming convention. For example there is also now an inconsistency for the use of the term `objfcts`: in one case `sel.reg.objfcts` is a full regularization (`Simple` or `Tikhnov` object) while in the case `self.invProb.reg.objfcts` it calls the individual norms or portions ( `Small` or `SmoothDeriv` ...) . It seems we now define `objfcts` as a handle to always access the next subdivision, but I am not sure of the name anymore in this case.

So with my current understanding, Would not it be better then to also turn `invProb.reg` into a `ComboObjectiveFunction ` object then to ensure consistency when calling  a  `reg` object?

**Comment by fourndo** [comment]
Not sure about the combo invProb. In my mind there is only one inverse problems, but multiple components making it.
Why are you accessing the reg through the invProb anyway? Can't you just use self.reg?

**Comment by thast** [comment]
I totally agree with you @fourndo : one inverse problem with multiple components. 

My point is more that, even if it is only internal mechanics of `Directives` , if a same call inside a same problem, (`*.reg` here) gives different types of output between classes, then it can become cumbersome both for users and developers.

In short, what I'd like to see if that makes sense is:  **`(self.reg == self.invProb.reg) -> True`**

Maybe this is a conversation worth having at the next `simPEG` meeting?

Thanks a lot for all the explanations @fourndo :)

**Comment by fourndo** [comment]
@lheagy @thast Was thinking about it. Why don't we handle the whole Combo thing (misfit and reg) inside the invProblem instead  Like makes total sense since we are already doing tedious checks, like this one for fields
`if f is None:
            if isinstance(self.dmisfit, DataMisfit.BaseDataMisfit):
                f = self.dmisfit.prob.fields(m)
            elif isinstance(self.dmisfit, ObjectiveFunction.BaseObjectiveFunction):
                f = []
                for objfct in self.dmisfit.objfcts:
                    if hasattr(objfct, 'prob'):
                        f += [objfct.prob.fields(m)]
                    else:
                        f += []`

We could just convert all to combos directly in there. That way everything else is seeing it the same from the outside (Directives included).

**Comment by thast** [comment]
I like that. That would make more sense indeed I think to act directly on `invProb.reg` (and `misfit`). As I mentioned earlier,
>  [it might be]  be better then to also turn invProb.reg into a ComboObjectiveFunction 

Also, referring to your previous question @fourndo,
> Why are you accessing the reg through the invProb anyway? Can't you just use self.reg?

I think it is a more natural way (to me) to access the regularization through `invProb.reg` and not `Directives.reg` , as regularization is part of the inverse problem more than the directives. I do not actualy mind as long as both are consistent but I would vote for replacing `self.reg` by `self.invProb.reg` in `Directives`.

**Comment by lheagy** [comment]
@fourndo, @thast: thanks for thinking this through! I agree that having the invProb turn the datamisfit and regularization into combos is probably the cleanest for now. 

@thast: regarding the second comment by accessing the regularization through the invProb vs. the Directive - this is a bit of long-term thinking, so see what your thoughts are: 
 
Eventually, I think that we want directives to be tied to individual objective functions (eg. to be able to assign target misfit one to `phid_1` and target misfit 2 to `phid_2` and at the end of each iteration, we see which pieces have a stopping criteria and if the are all satisfied or not), so there might be some cases where it makes sense to be talking to `directive.dmisfit` or `directive.reg` as this might be different than the invProb

**Comment by jcapriot** [comment]
I believe the underlying bug here was fixed a while ago, as this is working in the more recent versions. However the discussion on how directives being tied to specific regularizations is still relevant.
