### ISSUE TITLE
Flipping the Z sign of electrode locations when reading or writing UBC DC data files

### ISSUE THREAD

**Issue by micmitch** [simpeg/simpeg#671]
All of my testing indicates that we should not be flipping the Z sign of electrode locations when reading or writing UBC DC data files. Although the UBC codes may be z positive down I believe that the electrode location data needs to be z positive up.

Seogi seems to have some tests which indicate we do need to flip the Z sign of electrode locations.

Seogi and I need to try and sort this out...

**Comment by lheagy** [comment]
@micmitch, @sgkang: is this still an issue? or has it been sorted out?

**Comment by lheagy** [comment]
It seems this has been resolved by @sgkang and @micmitch. Feel free to reopen if there are still lingering issues here.
