### ISSUE TITLE
Gravity: Laguna del Maule Bouguer Gravity Jupyter Notebook error message

### ISSUE THREAD

**Issue by Kapondo** [simpeg/simpeg#675]
Hi @lheagy _et al_

I have downloaded the Jupyter notebook: plot_laguna_del_maule_inversion.ipynb and I am failing to reproduce the results with the below error message:  
---------------------------------------------------------------------------
**ModuleNotFoundError**                       Traceback (most recent call last)
`<ipython-input-2-d7894da672b6> in <module>()`
     2 import shutil
     3 import tarfile
-> 4 import SimPEG.PF as PF
     5 from **SimPEG** import Maps, Regularization, Optimization, DataMisfit,  InvProblem, Directives, Inversion
     6 from SimPEG.Utils.io_utils import download

**ModuleNotFoundError**: No module named 'SimPEG'

Please may you help

**Comment by Kapondo** [comment]
Hi @lheagy _et al_

Sorry, wrong virtualenv, above. The actual error message is as shown below:

Done 100% ...forward operator completed!!

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-d7894da672b6> in <module>()
    239 
    240 if __name__ == '__main__':
**--> 241     run()**
    242     plt.show()

<ipython-input-2-d7894da672b6> in run(plotIt, cleanAfterRun)
    111 
    112     # Preconditioning refreshing for each IRLS iteration
**--> 113     update_Jacobi = Directives.Update_lin_PreCond()**
    114 
    115     # Create combined the L2 and Lp problem

**AttributeError: module 'SimPEG.Directives' has no attribute 'Update_lin_PreCond'**

Please help!

**Comment by lheagy** [comment]
Hi @Kapondo, please download the most recent version of the notebook: http://docs.simpeg.xyz/content/examples/04-grav/plot_laguna_del_maule_inversion.html#sphx-glr-content-examples-04-grav-plot-laguna-del-maule-inversion-py, we have replaces `Update_lin_PreCond` with `UpdatePreconditioner` and the most recent example should include those changes.

**Comment by lheagy** [comment]
to run the most recent one, please also make sure you are on `SimPEG 0.7.1`

**Comment by Kapondo** [comment]
@lheagy, thanks a million. Working perfectly now!

**Comment by Kapondo** [comment]
@lheagy _etal_, I am battling to upgrade to SimPEG 0.7.1. I tried using `pip install --upgrade SimPEG` but when I check on the version, it is still 0.7.0. I get the information that all SimPEG and related packages are up-to-date.
Is there another way of upgrading SimPEG that you can recommend.

Thank you

**Comment by lheagy** [comment]
Hi @Kapondo, thanks for catching this. SimPEG 0.7.1 had not been deployed to pypi. Now it is there, so if you run `pip install --upgrade SimPEG` that should now put you on 0.7.1. Sorry for the confusion!

**Comment by fourndo** [comment]
Let us know if you have more potential fields questions @Kapondo. 
We have a lot of tools hanging around that are currently not exposed in the official release:  joint inversion, homogeneous inversion, rotated norms, MVI, petrophysical constraints and so on. Will be our pleasure to share with you.

**Comment by lheagy** [comment]
@Kapondo: since SimPEG 0.7.1 is now on pypi, I am going to close this issue. Please re-open it if you are still running into problems.

**Comment by Kapondo** [comment]
Thanks @lheagy, you can close the case. Everything seems working fine for
now. Much appreciated.



Best Regards
--------------------------------------------------------------------------------------------------------------------------------------

*Tongesai Kapondo*

20 Camelot
176 Helen Road
Strathavon
Sandton
2196 Johannesburg

C +27 79 508 8233
T +27 11 783 0163

E t.kapondo@gmail.com
Skype: kapondot
LinkedIn: https://za.linkedin.com/in/t-kapondo-86360b55

--------------------------------------------------------------------------------------------------------------------------------------
*"A computer program is said to learn from experience E with respect to
some task T and some performance P, if its performance P on task T, as
measured by P, improves with experience E"*

Tom Mitchell, 1997
