### ISSUE TITLE
Objective function

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#686]
I think that the `L2ObjectiveFunction` does not calculate the second derivate correctly:

![image](https://user-images.githubusercontent.com/913249/38470468-be4b1136-3b20-11e8-977b-10bf2657ac32.png)

I think it should use the `W` not the `self.W` in the final line:

`return W.T * W`

**Comment by lheagy** [comment]
Agreed, the return should be `W.T * W`. We likely missed this because `deriv2` is usually passed a vector, and therefore we return at line 444. With this fix, a short test that ensures that `deriv2` returns the same thing with and without a vector would be benificial
