### ISSUE TITLE
displaying versions

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#697]
@prisae suggested including a util for printing the version the core packages in your environment for reproducing SimPEG simulations and inversions. 

![selection_001](https://user-images.githubusercontent.com/6361812/41080452-62769382-69db-11e8-9590-6ae690435f90.png)

![selection_002](https://user-images.githubusercontent.com/6361812/41080448-5fe4715c-69db-11e8-97fe-73bc225623eb.png)

**Required Packages**
- numpy
- scipy
- cython
- properties
- vectormath
- discretize
- pymatsolver

**Optional Packages**
- matplotlib
- ipython
- ipywidgets

**Comment by prisae** [comment]
Great, thanks @lheagy. I hope I get around it this weekend.
