### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#702]
After seeing @prisae's tests in #698, I think that we should explore using `pytest` over `unittest` to make our testing scripts simpler and more transparent. (https://docs.pytest.org/en/latest/) Numpy also recently made the transition. 

It is compatible with unittest out of the box, so a transition should not be too painful.

**Comment by lheagy** [comment]
This would also help with #662

**Comment by jcapriot** [comment]
With #956, testing is now done using pytest!
