### ISSUE TITLE
vrmfwd_tests failing

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#709]
@dccowan: the vrmfwd_tests is currently failing on master (https://travis-ci.org/simpeg/simpeg/builds/411825516). This might be related to the OcTree updates in discretize. Could you please take a look into this? I think you might have fixed this in #708, but if you could make a small, isolated pr with the fix onto master, we can get it in ASAP.

**Comment by dccowan** [comment]
I think this was fixed a while ago. I believe it was related to the naming of the get cell centres function.
