### ISSUE TITLE
Bug in Regularization Mesh

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#713]
https://github.com/simpeg/simpeg/blob/d715980cf0b529c6e5f24daf35996de9ede0189d/SimPEG/Regularization.py#L432

`self.mesh._cellGradyStencil` (and related) are now methods, thus the bug. It should be `self.mesh._cellGradyStencil()`

**Comment by lheagy** [comment]
@thast, are you on the most recent version of `discretize`? All cell grad stencils should be properties (not methods). This should have taken effect as of `discretize 0.2.0` https://github.com/simpeg/discretize/releases/tag/0.2.0

**Comment by thast** [comment]
Right, sorry I forgot to pull the latest... my bad!
