### ISSUE TITLE
Parametric block map

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#716]
Right now, the parametric block map uses multiplication of arctan functions to construct the parametrization. This is okay if a large slope is used on the arctan function is used, but if a more gradual (inversion friendly) slop is used, the block gets smeared out oddly
![image](https://user-images.githubusercontent.com/6361812/43995803-7f6c796c-9d6a-11e8-8842-f2c5da40a7d2.png)

Instead, we should use the equation for a rectangle, and approximate the infinity-norm with an ekblom norm (so it is differentiable) and has smoother transitions between edges

**Comment by sgkang** [comment]
@lheagy that seems weird. What was your slope constant? If you are fixing that slope as a high number, you may not get those smoothing.

**Comment by lheagy** [comment]
Yep, the slope is constant, but to get better convergence of the inversion, you don't want it to be too high (it line-searches like crazy). I am working on a different formulation that instead of multiplying the arctan functions, we define the rectangle using approximate infinity norms - then we can use a gentle slope and still have it look like a rectangle: 

![image](https://user-images.githubusercontent.com/6361812/44064600-cd76af22-9f1a-11e8-8433-913d9595252f.png)

**Comment by lheagy** [comment]
closed with #724
