### ISSUE TITLE
Install SimPEG on windows

### ISSUE THREAD

**Issue by jc-barreto** [simpeg/simpeg#719]
Hello,

I'm trying to install SimPEG, but I'm getting an error.
When I try through the prompt line, with the command pip install SimPEG, installs all the packages but when arrives in the discretize I get an error: 

![image](https://user-images.githubusercontent.com/42352209/44113468-11c59446-a000-11e8-9f12-20227cfb851e.png)

![image](https://user-images.githubusercontent.com/42352209/44113480-20ff768e-a000-11e8-9602-d630def62c59.png)

And when I try to run the setup.py file I have the same error:

![image](https://user-images.githubusercontent.com/42352209/44113815-3ba43df2-a001-11e8-99a3-9873999c30bb.png)

![image](https://user-images.githubusercontent.com/42352209/44113822-42702af6-a001-11e8-8896-2762095c9058.png)

I already installed the Microsoft Visual C++ 2008 from here https://www.microsoft.com/en-ca/download/details.aspx?id=29
But still getting the error...
Someone knows how I can fix this?

Thanks a lot

**Comment by lheagy** [comment]
Hi @jc-barreto, can you try installing the latest Visual C++ from here: https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads (should be 2017) and give it another try? 

Let us know how it goes! 

cc @fourndo

**Comment by fourndo** [comment]
@jc-barreto : I had users being more successful with the Build Tools, although it is a larger installation.

https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by jc-barreto** [comment]
Hello,
Thank you very much.
I think is done. The second tip, installing just the Build tools didn't work, so I installed all the Visual Studio 2017.

![image](https://user-images.githubusercontent.com/42352209/44207575-af4ab100-a155-11e8-9135-64df039d10ee.png)


Now I'm trying to run SimPEG to see if the installation was really successful, BUT I'm a layperson on this subject. I have tried to run the DC_inversio_2D_example from notebooks and I got an error, so I don't know if is because the installation wasn't successful or it is because I'm running the notebook wrong...

![image](https://user-images.githubusercontent.com/42352209/44207579-b671bf00-a155-11e8-8ff9-4b480de52417.png)


Some tip?

**Comment by fourndo** [comment]
@jc-barreto 👍 Ok great, thanks for letting us know about Visual Studio.

Can you try:

**pip install pymatsolver**

Then restart your kernel and run all

**Comment by jc-barreto** [comment]
Thanks.

I did that...
![image](https://user-images.githubusercontent.com/42352209/44218135-f09c8a00-a170-11e8-863a-6342c15467ba.png)


![image](https://user-images.githubusercontent.com/42352209/44217780-28ef9880-a170-11e8-8be2-0cc720a77792.png)

![image](https://user-images.githubusercontent.com/42352209/44218180-1033b280-a171-11e8-9055-913bd6740f3e.png)


But in my pymatsolver folder doesn't exist "PardisoSolver" I don't know why...

![image](https://user-images.githubusercontent.com/42352209/44218005-a915fe00-a170-11e8-9c6f-5d82a7c7fa8c.png)

**Comment by fourndo** [comment]
Same here
![image](https://user-images.githubusercontent.com/2406426/44220640-050e6180-a134-11e8-99be-fa86bc4afa35.png)


Hmmm not too sure. Let me dig into this...

**Comment by fourndo** [comment]
How about pyMKL, can you try a pip install?

**pip install pyMKL**

![image](https://user-images.githubusercontent.com/2406426/44220808-81a14000-a134-11e8-8c9c-5e097f27b97e.png)

**Comment by jc-barreto** [comment]
Yeah... I tried this before too =(

![image](https://user-images.githubusercontent.com/42352209/44220886-c1d5e200-a177-11e8-86ca-3676d8cb9cc8.png)

**Comment by jc-barreto** [comment]
I didn't install Python through anaconda, I already had installed when I installed anaconda, do you think this matter?

**Comment by lheagy** [comment]
Hi @jc-barreto: can you try `conda install mkl`? (mkl is distributed through conda and needs some of the conda libraries and I don't think the pip install can handle this) 

I just saw your updated message - installations and managing your environment will be much(!) easier if you use ananconda to install python (https://www.anaconda.com/download). Use python 3.6 and the windows install

**Comment by jc-barreto** [comment]
Hello,
I uninstalled python and anaconda, and then installed python through Anaconda. 
Now the example it's working. Thank you! =)

**Comment by lheagy** [comment]
Excellent, I am glad you are up and running @jc-barreto!!

**Comment by xtt790894620** [comment]
> Hello,
> Thank you very much.
> I think is done. The second tip, installing just the Build tools didn't work, so I installed all the Visual Studio 2017.
> 
> ![image](https://user-images.githubusercontent.com/42352209/44207575-af4ab100-a155-11e8-9135-64df039d10ee.png)
> 
> Now I'm trying to run SimPEG to see if the installation was really successful, BUT I'm a layperson on this subject. I have tried to run the DC_inversio_2D_example from notebooks and I got an error, so I don't know if is because the installation wasn't successful or it is because I'm running the notebook wrong...
> 
> ![image](https://user-images.githubusercontent.com/42352209/44207579-b671bf00-a155-11e8-8ff9-4b480de52417.png)
> 
> Some tip?
i have met the same troubl,how can i get through it?

**Comment by xtt790894620** [comment]
![image](https://user-images.githubusercontent.com/43670539/50830379-951ea300-1382-11e9-8dd0-45ce5d50661c.png)
![image](https://user-images.githubusercontent.com/43670539/50830383-99e35700-1382-11e9-9854-eaf6a00b0b97.png)

**Comment by fourndo** [comment]
@xtt790894620 Looks like VS is still giving you trouble indeed.
I am not sure which one you have downloaded and installed, but this one works on all PCs I seen so far:
[Visual Studio Community](https://visualstudio.microsoft.com/vs/community/)
![image](https://user-images.githubusercontent.com/2406426/50837675-12a9cb00-1311-11e9-8ec4-c875af2f4ada.png)

Make sure during the installation that you've selected the ```Desktop develpmoent with C++``` option.
