### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by prisae** [simpeg/simpeg#741]
This is just meant as a discussion. But something that probably would have to be decided before the release of `v1.0`.

What about changing the module name from `SimPEG` to `simpeg`?

- Pro's:
  - Following the convention of most packages, in that the package and module names are identical.
  - Following pep8 guidelines, in which packages and modules should have all-lowercase names.
  - Less confusing. At the moment what a potential user would do (and what happend to me at the beginning several times) is

    1. `pip install simpeg`
    2. Fire-up an IPython shell or a notebook
    3. `import simpeg`

    with the result that it throws an error stating that `simpeg` is not installed. One has then to check the documentation or the examples to find out that the module to import is called `SimPEG`, not `simpeg`.

- Con's:
  Maybe too late for a change, too many scripts and notebooks exist which import `SimPEG`.

Just thought I initiate once the discussion. Maybe it was discussed before, I don't know.

**Comment by lheagy** [comment]
I do agree that this would be a better name.

... but I am afraid of how painful it would be to change at this point. Is there an easy way to depreciate the name? (e.g. allow backwards compatibility for a time?). I don't really think so at the module level??

**Comment by prisae** [comment]
I also think it is not possible on module level, and therefore not very feasibly. I just thought it might be worth to have the discussion before `v1.0`. Because now you could at least still argue "it is not `v1.0` yet, so API changes have to be expected" :wink: 

Also in light that at some point there was discussion to make many of the variable names more pep8ish. So if this would result in a one-off, heavy backwards-incompatible release then it might be worth taking this into account as well.

**Comment by lheagy** [comment]
that is true, it could be lumped under a major refactor

**Comment by prisae** [comment]
I think there is a possibility to deliver a new `simpeg` package and at the same time a `SimPEG` package which will only print information about the name-change. The important bit would be the line 
```
    packages=['simpeg`, `SimPEG'],
```
in `setup.py`. Then, `pip install simpeg` or `pip install SimPEG` (`pip` is case-insensitive, I believe) would install both packages, `simpeg` and `SimPEG`. The directory `SimPEG` would then only contain a `__init__.py`-file. In there, we could put print-statements about all the changes. E.g.: `SimPEG->simpeg`, `EM->electromagnetics`, etc etc.

In this case, if someone does `import simpeg` all is good and as it used to be before with `SimPEG`. However, if someone does `import SimPEG`, it will print all the info we put into `__init__.py`.

Here an example with a fictitious `testme`/`TestMe`-package, install them via `python setup.py install`: 
[testme.zip](https://github.com/simpeg/simpeg/files/3329593/testme.zip)

And here a screenshot of it in action:
![IPython: home-dtr_001](https://user-images.githubusercontent.com/8020943/60173683-99932700-980f-11e9-9964-f089d1782c3c.png)

**Comment by lheagy** [comment]
Thanks for doing digging on this @prisae! If we can allow both imports, then I am all for bringing this in on #786

**Comment by prisae** [comment]
I just remembered about this issue. As far as I can see, https://github.com/simpeg/simpeg/pull/786 will break almost all code and require some adjustments in most scripts, right? Wouldn't that be a good place to rethink the `SimPEG`/`simpeg` import? Along the lines of now or never... ;-)

Re-reading the discussing above actually points towards that as well.

@lheagy , @jcapriot

**Comment by prisae** [comment]
I am closing this. As it didn't happen in the simulation-PR it is unlikely going to happen. Re-open if you disagree ;-)
