### ISSUE TITLE
`DataMisfit.std` is always 5%, no matter the `survey.std`

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#746]
`DataMisfit.std` is always 5% and never take into consideration `survey.std`. So you are forced to set `DataMisfit.W` manually... (so many example to rerun on my end ^^')

Taking care of in PR #745

**Comment by micmitch** [comment]
That sucks.... Lots to rerun on my end too. Thanks for catching this @thast !

**Comment by thast** [comment]
fixed in PR #745
