### ISSUE TITLE
pip install trouble

### ISSUE THREAD

**Issue by xtt790894620** [simpeg/simpeg#750]
Dear professers:
        i tried to 'pip install SimPEG',but caught a mistake as follows:
![image](https://user-images.githubusercontent.com/43670539/50829364-402d5d80-137f-11e9-98ad-74dd368b56cc.png)
![image](https://user-images.githubusercontent.com/43670539/50829374-491e2f00-137f-11e9-8ed3-f41441069c8f.png)
        i tried a lot of times,but couldnot solve it by myself,i would appreciate you if you could help me

**Comment by lheagy** [comment]
How do you have python installed? is it through anaconda (https://anaconda.com/download/). Also it looks like you are running windows - do you have the most recent version of visual studio installed (https://visualstudio.microsoft.com/visual-cpp-build-tools/)?

**Comment by lheagy** [comment]
correction: please try the community version: https://visualstudio.microsoft.com/vs/community/

**Comment by xtt790894620** [comment]
Hi,lheagy：
    it works for me.thank you a lot. I am trying my best to learn how to use SimPEG. In addition,i still have one question whether SimPEG can forward 2-D MT model and achieve MT data Ex,Ey,Hx,Hy.
    hope for your reply,thank you a lot.

**Comment by lheagy** [comment]
Hi @xtt790894620: glad to hear it! The way that you would forward model 2D MT data in SimPEG would be to use [Maps.Surject2Dto3D](http://docs.simpeg.xyz/content/api_core/api_Maps.html#map-2d-cross-section-to-3d-model). There is an example that uses that map for an airborne em simulation [here](https://github.com/simpeg-research/heagy-2018-aem). See the forward simulation: [1_TEM_VerticalConductor_2D_forward.ipynb](https://mybinder.org/v2/gh/simpeg-research/heagy-2018-AEM/master?filepath=notebooks%2F1_TEM_VerticalConductor_2D_forward.ipynb)

This same process can be used to simulate MT data (see the 3D forward simulation [here]( http://docs.simpeg.xyz/content/examples/08-nsem/plot_foward_MTTipper3D.html#sphx-glr-content-examples-08-nsem-plot-foward-mttipper3d-py) ). I hope these are helpful in getting started. Please feel free to post workflow questions on the SimPEG google group: https://groups.google.com/forum/#!forum/simpeg

**Comment by lheagy** [comment]
I am going to close this issues since the pip install is working. Feel free to open a new one if you have further questions about the code.
