### ISSUE TITLE
run black on SimPEG

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#751]
similar to simpeg/discretize#132, I think we should be using [black](https://github.com/ambv/black) on SimPEG to format the code. This will help with line-spacing and should simplify the diffs on pull-requests. It also means we do not need to format the code by hand.

**Comment by prisae** [comment]
`black` uses by default a line length of 88.  They say it makes code shorter. Most likely it does, as the line length is longer. However, if you look at code through a terminal or an IPython terminal or vim or emacs etc (which I think still many do), then a line length of 88 is simply horrible.

I am fine with `black`, but I'd suggest to set `--line-length 80` to restore the "normal" behavior.

**Comment by prisae** [comment]
See https://github.com/fatiando/verde/issues/177 for examples and more reasoning why (I think/argue) you should, please please, set `max-line-length` to 80.

**Comment by prisae** [comment]
It is archived, but I still find it hilarious: https://github.com/kenneth-reitz/white
It is basically a wrapper for `$ black --line-length 79`

**Comment by jcapriot** [comment]
This was closed with 0.14.0!
