### ISSUE TITLE
tolerances on VRM tests

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#753]
The VRM tests seem quite sensitive to the random seed. We should either:
- soften the tolerances so that the tests are less susceptible to failure 
- or set a reliable seed for the random aspects of the test 

@dccowan: would you be willing to take this on?

**Comment by fourndo** [comment]
@dccowan is away for another month. I would say we should just fix the seed.

**Comment by lheagy** [comment]
okay, we can do that

**Comment by thast** [comment]
This is what I did on my branch. 
![image](https://user-images.githubusercontent.com/13682747/51492826-f45bba80-1d67-11e9-80d7-4a8fa48a6c9c.png)

I can get a PR in this afternoon.

Note: 518936 is the closest I could get to 'SimPEG' with numbers

**Comment by lheagy** [comment]
closed with #754
