### ISSUE TITLE
Properties `_check_model_valid`

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#760]
I'm no expert with `properties` so I require help on that one.
I get warnings for the shape of my model and my mapping (while they are the right shape, as it computes the right things).

It seems to come down to that, in the `_check_model_valid` test, one warning is not conditioned to an `if` statement. Is that a bug or am I missing something? Thanks for the help

https://github.com/simpeg/simpeg/blob/f4d03c44d7bd0369bf73b5b51131bd7f0c6a718d/SimPEG/Props.py#L424

**Comment by lheagy** [comment]
@thast: could you include a minimal example that generates the error you are describing?

**Comment by thast** [comment]
@lheagy : Here is a slight modification of the Gravity linear example to demonstrate it (the modification adds a wire to the mapping, which seems to cause the issue.) (to run before PR #762 is merged, as it fixes the issue but for Gravity only... there is something deeper going on I feel)
[Demo Jupyer notebook](https://drive.google.com/open?id=1UcZ-fnfHQ7ayxq-wGWk5Drh2Q5DFlMIu)

**Comment by lheagy** [comment]
excellent, thanks @thast! I am at the Jupyter meeting this week so have minimal bandwidth at the moment, but  I will plan to jump in before the meeting next week

**Comment by thast** [comment]
No rush @lheagy , enjoy the conference :)

**Comment by lheagy** [comment]
Hi @thast, I had a look and I think what was happening is that there was a bit of a subtle name-clash going on. `model` has specific meaning in the base problem, when it was over-written, the name still got called, but the behaviour was based on the new definition not on the `model` at the base of the code. 

https://github.com/simpeg/simpeg/blob/master/SimPEG/Props.py#L355

So it didn't go through the setter defined at the base (which keeps track of things like size, and checks compatibility with the mapping size). 

I hope this helps and am happy to chat further if it is still confusing.

**Comment by thast** [comment]
Thanks for taking a look @lheagy. Has said, It was fixed in PR #762 but I wanna make sure there was nothing deeper happening. I think we can close it for now.
