### ISSUE TITLE
DOC: Source code not linked, 404

### ISSUE THREAD

**Issue by prisae** [simpeg/simpeg#765]
Some (all?) of the source codes are not linked anymore. To reproduce: Go to, e.g., http://docs.simpeg.xyz/content/em/api_FDEM.html?highlight=fdem%20src%20rawvec_e#SimPEG.EM.FDEM.SrcFDEM.RawVec_e and there click on "source". It results in the following 404 error-page:

### The requested URL /_modules/SimPEG/EM/FDEM/SrcFDEM.html was not found on this server.

**Comment by prisae** [comment]
Looks like the possibility to view the API source-code got removed completely? (The `[source]`-button that shows the python-code.)

I always like that feature in the docs, will that be back? Otherwise this issue can be closed...

**Comment by prisae** [comment]
:-D I just wanted to create an issue reporting that the source-links are not working. Turns out I reported that already a year ago.

So this issue still holds, the `[source]` links do not work for the entire SimPEG-documentation.

**Comment by prisae** [comment]
It does work for discretize, so it must be somehow a setup-issue with the SimPEG docs.

**Comment by prisae** [comment]
I guess this is related to #764 in a way, in general properly setting up the docs.

**Comment by prisae** [comment]
@jcapriot this issue was marked as closed in the release notes of 0.14.0, but I just checked, and the issue is still there?

**Comment by prisae** [comment]
E.g., klicking here:

http://docs.simpeg.xyz/content/em/api_FDEM.html#SimPEG.electromagnetics.frequency_domain.simulation.BaseFDEMSimulation

on the   [[source]](http://docs.simpeg.xyz/_modules/SimPEG/electromagnetics/frequency_domain/simulation.html#BaseFDEMSimulation)

results in
![Selection_001](https://user-images.githubusercontent.com/8020943/83098215-44f4cd80-a0aa-11ea-99c6-aac9a901c745.png)

**Comment by jcapriot** [comment]
Try it now :)
