### ISSUE TITLE
grounded source implementation for octree

### ISSUE THREAD

**Issue by sgkang** [simpeg/simpeg#766]
- `LineCurrent` class used for time-domain EM code needs to be extended to `FDEM` problem and Octree Meshes. 

- This basically requires to extend `getSourceTermLineCurrentPolygon` in CurrentUtils.py

- May need some help from @jcapriot

**Comment by micmitch** [comment]
I also need to start working with grounded sources on the octree mesh soon. Not sure how much help I will be with the octree side of things but I'm happy to try and help.

**Comment by jcapriot** [comment]
My first inclination of this, is that it shouldn't be too much additional work, as there is already a function to locate the cell (or cells) in a TreeMesh a given point (or list of points) is in.

**Comment by jcapriot** [comment]
The source terms for LineCurrents now all support TreeMesh's
