### ISSUE TITLE
Writing new stencils the SimPEG way

### ISSUE THREAD

**Issue by bsmithyman** [simpeg/simpeg#77]
I'm wondering how to go about putting together operators and stencils that are different from the baked-in mesh operators. For example, different versions of the Laplacian, stencils with absorbing boundaries, etc.

Is there a SimPEG way to do this correctly, and if not how do we go about setting the framework up to do that?

**Comment by lheagy** [comment]
@rowanc1 , @bsmithyman : can we close this??

**Comment by bsmithyman** [comment]
@lheagy, @rowanc1 : I think so. Some good points here that are on my long-term todo list, but it's not like it won't continue to be archived. I don't think it's really serving any purpose at the moment.
