### ISSUE TITLE
NSEM : incorrect shape of rhs (right hand system?)

### ISSUE THREAD

**Issue by acceph** [simpeg/simpeg#774]
Hello everyone

Recently, I tried to build NSEM inverse modeling using SimPEG (syntethics model) and my further plan is to inverse my MT field data in 3D, hopefully I got something better than my previous works.

I think the model and its calculation (forward modeling) is running good so far, but I got problems when trying to run the inversion command, the error tell me about the incorrect shape of rhs. might be I feed something not proper to the package, but I don't know which was the problem..
my forward modeling is following the NSEM example, "plot_forward_MTTipper_3D.ipynb" while the inversion I follow "plot_loop_loop2Dinversion.ipynb". my modification is only at defining the model (m_true value). 

**Here is the command being executed,**

mrec = inv.run(m0)

**Here is the error i found,** 

SimPEG.InvProblem will set Regularization.mref to m0.

    SimPEG.InvProblem is setting bfgsH0 to the inverse of the eval2Deriv.
    ***Done using same Solver and solverOpts as the problem***

_/home/angelwings/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/Props.py:400: UserWarning: Cannot add model as there are no active mappings, choose from: ['muMap', 'muiMap', 'rhoMap', 'sigmaMap']
  "', '".join(self._all_map_names)_

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-11-588cd3591813> in <module>
----> 1 mrec = inv.run(m0)
      2 print("\n Inversion Complete. Elapsed Time = {:1.2f} s".format(time.time() - t))

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/Utils/CounterUtils.py in wrapper(self, *args, **kwargs)
     97         if type(counter) is Counter:
     98             counter.countTic(self.__class__.__name__+'.'+f.__name__)
---> 99         out = f(self, *args, **kwargs)
    100         if type(counter) is Counter:
    101             counter.countToc(self.__class__.__name__+'.'+f.__name__)

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/Inversion.py in run(self, m0)
     63         """
     64         self.invProb.startup(m0)
---> 65         self.directiveList.call('initialize')
     66         print('model has any nan: {:b}'.format(np.any(np.isnan(self.invProb.model))))
     67         self.m = self.opt.minimize(self.invProb.evalFunction, self.invProb.model)

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/Directives.py in call(self, ruleType)
    173         )
    174         for r in self.dList:
--> 175             getattr(r, ruleType)()
    176 
    177     def validate(self):

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/Directives.py in initialize(self)
    229                 t += x0.dot(dmis.deriv2(m, x0, f=f[i_count]))
    230             else:
--> 231                 t += x0.dot(dmis.deriv2(m, x0, f=f))
    232             b += x0.dot(reg.deriv2(m, v=x0))
    233             i_count += 1

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/Utils/CounterUtils.py in wrapper(self, *args, **kwargs)
     97         if type(counter) is Counter:
     98             counter.countTic(self.__class__.__name__+'.'+f.__name__)
---> 99         out = f(self, *args, **kwargs)
    100         if type(counter) is Counter:
    101             counter.countToc(self.__class__.__name__+'.'+f.__name__)

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/DataMisfit.py in deriv2(self, m, v, f)
    163             f = self.prob.fields(m)
    164         return self.prob.Jtvec_approx(
--> 165             m, self.W * (self.W * self.prob.Jvec_approx(m, v, f=f)), f=f
    166         )
    167 

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/Utils/CounterUtils.py in wrapper(self, *args, **kwargs)
     97         if type(counter) is Counter:
     98             counter.countTic(self.__class__.__name__+'.'+f.__name__)
---> 99         out = f(self, *args, **kwargs)
    100         if type(counter) is Counter:
    101             counter.countToc(self.__class__.__name__+'.'+f.__name__)

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/Problem.py in Jvec_approx(self, m, v, f)
    193         :return: approxJv
    194         """
--> 195         return self.Jvec(m, v, f)
    196 
    197     @Utils.timeIt

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/SimPEG/EM/NSEM/ProblemNSEM.py in Jvec(self, m, v, f)
     73                 dRHS_dm_v = self.getRHSDeriv(freq, v) # Size: nE,2 (u_px,u_py) in the columns.
     74                 # Calculate du/dm*v
---> 75                 du_dm_v = Ainv * ( - dA_dm_v + dRHS_dm_v)
     76                 # Calculate the projection derivatives
     77                 for rx in src.rxList:

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/pymatsolver/solvers.py in __mul__(self, val)
     80     def __mul__(self, val):
     81         if type(val) is np.ndarray:
---> 82             return self._solve(val)
     83         raise TypeError('Can only multiply by a numpy array.')
     84 

~/anaconda3/envs/simpeg/lib/python3.7/site-packages/pymatsolver/solvers.py in _solve(self, rhs)
     59 
     60         n = self.A.shape[0]
---> 61         assert rhs.size % n == 0, 'Incorrect shape of rhs.'
     62         nrhs = rhs.size // n
     63 

AssertionError: Incorrect shape of rhs.

**Comment by lheagy** [comment]
:wave: Hi @acceph, would you mind posting your notebooks somewhere so we can download and run it? For example, you could put it in a new github repository on your profile or put it in dropbox and send a link. Thanks!

**Comment by acceph** [comment]
The notebook's file I have trying to run can be found [here](https://github.com/acceph/NSEM3D)
I would like to thanks for any advices or corrections to solve this problems..

**Comment by grosenkj** [comment]
Hi @acceph 

Thanks for your interest and dedication in using the SimPEG NSEM code. 

Thanks for sharing your notebook. For your specific problem, the issue is that the size of your matrices don't match up. After looking at your code, I think the problem comes from how you construct yoru initail model, `m_0`. You make it with
```python
m0 = 1e-8 * np.ones(mesh.nC)
```
so that it only has air values. Combined with the `Map` will make the initial model become 0 long, hence not matching the size of your mesh. 

I would recommend using a half space as a intial model, something like

```python
m0 = 1e-8 * np.ones(mesh.nC)
m0[active_inds] = 1e-2 # or value you prefere
```
Please try changing this and see if the inversion doesn't run.

**Comment by acceph** [comment]
Hello @grosenkj 

> Please try changing this and see if the inversion doesn't run.

Thank you for your kindly attention to help me.
Would you mind giving me another clues?

**Comment by acceph** [comment]
hi all..
I would like to close this issue, the inversion is running very smoothly without any error now.. I was made mistake before, grosenkj was right..

**Comment by kashkoulimohammad** [comment]
Dear @acceph ,
May I use your code?

Sincerely,
Mohammad
