### ISSUE TITLE
Problem with TimeSteps TDEM

### ISSUE THREAD

**Issue by jc-barreto** [simpeg/simpeg#775]
Hello, 

I'm trying to run a TDEM field case but I'm not getting good results. 
My problem is that I don't understand how to define the Time mesh.
When I put timesteps = [(1e-6, 3), 1e-5, (1e-4, 2)]  I'm giving the dt and how many dt will be with that width right? How can I define the first point? will be always zero? Should I start always at the first point of the waveform? Should I stop before the end of the waveform? or should I go until the end of the timechannels?

I have tried several meshes and when I don't have an error the result is not good.
The error I get often is "Points outside of mesh"
![image](https://user-images.githubusercontent.com/42352209/55483477-90cef280-561e-11e9-99e6-19060bd0cf3e.png)

My problem is in the function timeMesh.getInterpolationMat(self.times, self.projTLoc(f))
![image](https://user-images.githubusercontent.com/42352209/55483308-3897f080-561e-11e9-96bb-140fbed73ff5.png)

But I couldn´t figure out what means the "zerosOutside".

Here  are the notebooks I've trying to run. 

https://github.com/jc-barreto/SimPEG_Tests_Jenny

If someone can help me I would be very thankful

**Comment by lheagy** [comment]
Hi @jc-barreto, What is likely happening is that you  are trying to compute data that are at later times that the simulation. The time vector that is created needs to be long enough to simulate the waveform and extend long enough that the latest receiver times are captured. 

Under the hood, when you create the time vector using the notation `[(1e-6, 3), 1e-5, (1e-4, 2)]`, the utility `meshTensor` is called

```python
import numpy as np
from SimPEG.Utils import meshTensor
dt = meshTensor([(1e-6, 3), 1e-5, (1e-4, 2)])
```
if we look at the values of `dt` they are 
```python
array([1.e-06, 1.e-06, 1.e-06, 1.e-05, 1.e-04, 1.e-04])
```
The times that the fields are computed at are then the cumulative sum of [0, dt]
```python
times = np.hstack([[0], dt]).cumsum()
```
which gives an output of 
```python
array([0.00e+00, 1.00e-06, 2.00e-06, 3.00e-06, 1.30e-05, 1.13e-04,
       2.13e-04])
```

So, if any of your receiver measurements are beyond 2.13e-04 s, then the simulation hasn't been run long enough and you will get a "zerosOutside" error (which I agree is a bit cryptic!) 

I hope this helps!

**Comment by jc-barreto** [comment]
Thank you @lheagy  ! now that I understood, I could run a test with a nice result (https://github.com/jc-barreto/SimPEG_Tests_Jenny) =D
I'm improving the notebook, to be readable for people like me, that has no knowledge with SimPEG and just a little with geophysical methods. So, I have some questions that I also would like to put the answers in the notebook, if you could help me...
-The data we load in TDEM SimPEG, which unit should be? I put the same from the example of bookpurnong that is V/(A.turns.m^4), but just for following the example, can I put other units?

-Where I take into account the current of the equipment? Is it in this part?
 src=EM.TDEM.Src.CircularLoop([dbdtz],waveform=src_waveform,loc=rxloc,orientation='z',radius=radius,current=1./area) 
the 1 is the equipment current? in this case 1A ? or since I have the waveform with maximum amplitude of 1, I don't need to think about the current?if not, where can I put the current of the equipment, like in TEMFAST is 4 A, there is some place to introduce this information?
