### ISSUE TITLE
Active Cell Mapping bug.

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#78]
If we have a mapping of:

```
S*(P*m + v)
```

Where S is some weighting, P is a projection up to the full domain, and v is the background this will NOT work for the regularization. Here we are multiplying by the difference: (m - mref) and the v vector is in the wrong place.

This could either be fixed by changing the regularization to map both m and mref up separately and then subtract them, but I think that is confusing.

Also, really the active cell mapping should have a background of **zero** rather than the background conductivity... which circumvents this issue all together.

At any rate, the active cell mapping is not really a linear operator...and could lead to some difficulties in usage.

**Comment by lheagy** [comment]
This will close with #254

**Comment by lheagy** [comment]
@rowanc1, I believe we can close this now that the `regmesh` and has been implemented which allows us to regularize only in the active cells. Thoughts?

**Comment by lheagy** [comment]
This closed with the implementation of the Regularization Mesh in #254. If you wish to use active cells and have those not included in the regularization, you need to pass the `indActive` to the regularization
