### ISSUE TITLE
Colorbar functionality mesh.plotImage not working for OcTree mesh

### ISSUE THREAD

**Issue by sarahgarre** [simpeg/simpeg#782]
Hi, I have to change the default colorbar used by mesh.plotImage to prevent images from being counterintuitive for my application. However, the cb='colorbar_name' option does not seem to have any effect. Is this a bug or am I doing something wrong?

`out = my_mesh.plotImage(sigma_wrong,clim=[0,6],ax=ax1,cb='jet') `

**Comment by sarahgarre** [comment]
@fourndo I think you already identified the problem, no? The TreeMesh plotImage function does not have the dictionary for colorOpts. Is it possible to fix this somewhere soon?

**Comment by lheagy** [comment]
Thanks for raising this @sarahgarre! This is an `discretize` specific issue, so I will transfer it over there

**Comment by lheagy** [comment]
moved to simpeg/discretize#173
