### ISSUE TITLE
gravity inversion

### ISSUE THREAD

**Issue by ROSHIV** [simpeg/simpeg#789]
Hello,
I am really new to simpeg, and need help in garvity inversion. I wrote the code but does not work, I appreciate if anybody here can help me to fix it.

Regards

**Comment by fourndo** [comment]
@ROSHIV can you provide more details?

**Comment by lheagy** [comment]
I am going to close this since there hasn't been further discussion. Please feel free to reopen if you still have questions @ROSHIV
