### ISSUE TITLE
PlotSlice

### ISSUE THREAD

**Issue by rowanc1** [simpeg/simpeg#79]
Have the ability to flip the x-y axis:

```
M.plotSlice(...,flipXY=False,...)
```

**Comment by lheagy** [comment]
This issue should be moved over to discretize. @rowanc1, I am not sure how to do that? or we can just open a new issue there

**Comment by rowanc1** [comment]
This issue was moved to simpeg/discretize#37

**Comment by rowanc1** [comment]
https://github-issue-mover.appspot.com/
