### ISSUE TITLE
`from SimPEG.Regularization import BaseRegularization` gives an error

### ISSUE THREAD

**Issue by sgkang** [simpeg/simpeg#803]
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a33003996a06> in <module>
----> 1 from SimPEG.Regularizationg import BaseRegularization

ModuleNotFoundError: No module named 'SimPEG.Regularization'
```

Had to use 

`from SimPEG.regularization import BaseRegularization`

Any idea @lheagy ?

**Comment by lheagy** [comment]
Hi @sgkang: yes, we broke up the `Regularization.py` into multiple files in a `regularization` module in [0.11.6](https://github.com/simpeg/simpeg/releases/tag/0.11.6). You can still `import Regularization`, but if you would like to import the base classes, you now need to do `from SimPEG.regularization import BaseRegularization`

**Comment by sgkang** [comment]
Ah, so it is supposed to then no problem.
