### ISSUE TITLE
Error when using a Tree mesh for MT inversion

### ISSUE THREAD

**Issue by JKutt** [simpeg/simpeg#805]
Hi all, I've run into a problem when attempting to use a Tree-mesh for MT inversion. It fails looking for the 'r' method that I assume tensor meshes use. Is there a different method that should be used for tree meshes or should I make a similar re-shape method for the tree-mesh? The following is the error that is output:

c:\programdata\anaconda3\lib\site-packages\SimPEG\EM\NSEM\SrcNSEM.py in ePrimary(self, problem)
     67                         problem._sigmaPrimary, 'CC', 'CC', 'M')[:]
     68                 elif problem.mesh.dim == 3:
---> 69                     self.sigma1d = problem.mesh.r(
     70                         problem._sigmaPrimary, 'CC', 'CC', 'M')[0, 0, :]
     71             # Or as the 1D model that matches the vertical cell number

AttributeError: 'TreeMesh' object has no attribute 'r

**Comment by JKutt** [comment]
Thanks for the response @jcapriot . I'm not very familiar about how to go about coming up with function for this, but with some guidance I am more than willing to take a stab at this. I will also dig around and see if I can spot other places this assumption is made. Thanks again!

**Comment by jcapriot** [comment]
TreeMesh's now work with the MT class #946
