### ISSUE TITLE
Documentation link on http://pypi.python.org/pypi/SimPEG/0.1.1 outdated

### ISSUE THREAD

**Issue by mtb-za** [simpeg/simpeg#81]
Just so that you are aware, [this](http://pypi.python.org/pypi/SimPEG/0.1.1) is the top link if I search for SimPEG on duckduckgo, but the link still points to http://simpeg.3ptscience.com

**Comment by rowanc1** [comment]
Thanks Martin, I have been meaning to update the pypi site. Thanks for letting us know about the broken link. In the meantime, I have asked 3point to put up a forwarding redirect to our new website http://simpeg.xyz. That should be live soon.

I will close the issue when I update pypi.

**Comment by rowanc1** [comment]
(should be live now...)

**Comment by lheagy** [comment]
Hey Rowan,

The link now directs to sipeg.xyz, but the text still says:
http://simpeg.3ptscience.com

**Comment by rowanc1** [comment]
Yep. It will change when we bump simpeg to a new version and push that to pypi.

**Comment by rowanc1** [comment]
I just updated PiP, this has been fixed.
