### ISSUE TITLE
Potential Field Guide/Tutorial?

### ISSUE THREAD

**Issue by mtb-za** [simpeg/simpeg#82]
I have gone through the docs, (and the ones for https://github.com/simpeg/simpegpf/ ) but I wondered if there was something written up about getting started for someone with a pretty limited background in geophysics. The theory there is fine and clear, but I am not 100% up to speed on actually importing some data and doing things with it.

I am mostly looking at potential field methods (airborne mag/grav/radiometric) techniques. From what I understand, I would create meshes based on the survey?

If this does not exist, I will figure it out (and probably write up my notes as I go), but if there is something, I would be grateful if someone could point me at it.

**Comment by sgkang** [comment]
Dear Martin,

     I am writing a tutorial for mag problem, and hopefully commit this in
this morning. Currently, we have mag package, but we do not have
grav/radiometric packages. However, you can perform forward modeling and
inversion for airborne mag.

All the best,

Seogi.

2015-01-28 2:46 GMT-08:00 Martin Bentley <notifications@github.com>:

**Comment by sgkang** [comment]
I put a tutorial for mag forward problem (See git hub repository:
simpegPF/notebooks/tutorials). Hopefully, that is helpful for you.

All the best,

Seogi

2015-01-28 2:46 GMT-08:00 Martin Bentley <notifications@github.com>:

**Comment by mtb-za** [comment]
Great, thanks.

If I have questions, should I address them as an issue there or here?

Because for some reason I am not able to import things from simpegPF, possibly because the setup.py file seems a bit empty. Not sure if I am installing that wrong. SimPEG works though....

**Comment by sgkang** [comment]
Dear Martin,

     That might be better to put some questions on github for simpegPF. You
do not have to run setup.py for simpegPF. I assume you cloned simpegPF on
your machine. Then you simply add that directory to your pythonpath. After
that open up ipython through command window and check if you can import
simpegPF.

Cheers,

Seogi



2015-01-28 23:31 GMT-08:00 Martin Bentley <notifications@github.com>:

**Comment by rowanc1** [comment]
Just looked at the setup.py, it is about a year old and is very much a hack for getting TravisCI to work. As Seogi said, you should be able to git clone it and add the git directory to your python path in a .bashrc file or similar. Hope that helps,
R
