### ISSUE TITLE
Direct magnetic problem problem

### ISSUE THREAD

**Issue by ASmelov** [simpeg/simpeg#823]
Hi everyone! First of all, the SimPeg project looks amazing, thanks a lot for it! I had difficulties in solving the direct magnetic problem. As a basis, I chose the example presented here (http://docs.simpeg.xyz/content/examples/05-mag/plot_mag_inversion_linear.html#sphx-glr-content-examples-05-mag-plot-mag-inversion-linear-py). I began to gradually complicate the initial model of magnetic susceptibility and look at the anomalous field on the surface of the model. For a model with a cube that has a different susceptibility from the host rocks, the resulting field seems plausible (Figure 1). Next, I set a model with a sloping oblique border, in this case the result also seems logical - the resulting field is gradually changing (Figure 2). After that, I complicated the model: I defined a three-layered medium, with complex boundaries between the layers. The values of magnetic susceptibility within the layers are constant and increase with depth. At the output of the algorithm, I expect to see an anomalous field of complex shape, however, regardless of the complexity of the model, I observe the field as in Figure 3. Can someone tell me where I made a mistake or didn’t take something into account?
<img width="635" alt="Figure 1" src="https://user-images.githubusercontent.com/54511532/68572805-65936800-0477-11ea-9b76-cdee0f1d92a0.PNG">
<img width="633" alt="Figure 2" src="https://user-images.githubusercontent.com/54511532/68572806-65936800-0477-11ea-87c2-7facf3e9bff2.PNG">
<img width="635" alt="Figure 3" src="https://user-images.githubusercontent.com/54511532/68572807-65936800-0477-11ea-9f5e-c9ea4a850e23.PNG">

**Comment by domfournier** [comment]
This looks like amazing work @Artem Smelov!

Two things to look out for:

1) for bulk physical property model like these you need to make sure your domain extends much further beyond the extent of your data
By the shape of the anomaly, I suspect that right now you are mostly seeing the edge of the model

2) grav and mag are weakly sensitive to vertical contrasts. For instance, you could probably reverse the order of the green and yellow zone, and get relatively similar data.

**Comment by domfournier** [comment]
[From Slack]
Increasing the domain size outside of the core can be done pretty efficiently with `padding cells`.
The rule of thumb is to have padding cells on either side that extend out to a distance half the width of your survey area. For tensor mesh, you can use an[ expansion factor](http://discretize.simpeg.xyz/en/master/tutorials/mesh_generation/2_tensor_mesh.html?highlight=expansion#padding-cells-and-plotting), for octree expand it will just [fill to the extent of the mesh](http://discretize.simpeg.xyz/en/master/tutorials/mesh_generation/4_tree_mesh.html#basic-example).
This mainly comes from best-practice in Fourier transform as you want to be able to absorb the longest wavelength possible captured by the data.

But this is all very much problem-dependent of course. 
Another possible trick would be to run a bunch of simulations with increasing padding distance until the data stops changing.

**Comment by jcapriot** [comment]
This does seem to be an issue of not using enough padding cells to compute the values. The shape of the response is dominated by the bulk contribution of your mesh's size.
