### ISSUE TITLE
bug in Utils.surface2ind_topo

### ISSUE THREAD

**Issue by yezhengkai** [simpeg/simpeg#832]
When I followed the practice of [plot_dipoledipole_2_5Dinversion.py](https://github.com/simpeg/simpeg/blob/master/examples/06-dc/plot_dipoledipole_2_5Dinversion.py) and delved into the function surface2ind_topo, I found that these parts of the function surface2ind_topo may be incorrect.

https://github.com/simpeg/simpeg/blob/41b2ada51de8c2e4e7a9e8509a981d2d23561a99/SimPEG/Utils/modelutils.py#L31-L38

https://github.com/simpeg/simpeg/blob/41b2ada51de8c2e4e7a9e8509a981d2d23561a99/SimPEG/Utils/modelutils.py#L76-L79

From what I understand, the correct code for lines 36 and 79 is
```python
xminTopo, xmaxTopo = topo[:, 0].min(), topo[:, 0].max()
```

**Comment by thast** [comment]
Thanks for sharing @yezhengkai ! That looks suspicious indeed. I'll have a look.
