### ISSUE TITLE
GWB laundry list

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#838]
As @dougoldenburg and I started working through the [GWB notebooks](https://github.com/simpeg-research/gwb-dc-inversions), there were a couple of items that came up. We can use this as a running list. @jcapriot: please feel free to add to this as you work through things with Doug today. 

- [ ] serializing and deserializing the survey class. Currently, we the deserialization of a DC survey fails. We should just need to update the logic in the instantiation of the DC survey. 

- [ ] also add a test for the serialization / deserialization of the survey

- [x] in the instantiation of the `Data` class, we should allow `uncertainty` to be passed as a keyword and go through the setter 

- [x] remove the `mesh` from the 1D code

- [x] rename `t` to `thicknesses` in the DC1D (@sgkang: would you be willing to do this?)

- [ ] when doing a 2D simulation, you are able to define the Pole_ky and Dipole_ky to measure apparent resistivity and apparent conductivity. However, the forward simulation fails when calling the geometric factor for these receivers because it is not defined. This should be fixed.

- [ ] chat through removing the factor of 1/2 from the data misfit and regularization (cc @dougoldenburg) as per #763

**Comment by lheagy** [comment]
I have updated the `Data` class with tests on the `simulation` branch. We will need to propagate this to the `simulation-jk` and `simulation-pf` branches

**Comment by jcapriot** [comment]
I'll get them merged in, there doesn't seem to be many issues with this

**Comment by sgkang** [comment]
> As @dougoldenburg and I started working through the [GWB notebooks](https://github.com/simpeg-research/gwb-dc-inversions), there were a couple of items that came up. We can use this as a running list. @jcapriot: please feel free to add to this as you work through things with Doug today.
> 
> * [ ]  serializing and deserializing the survey class. Currently, we the deserialization of a DC survey fails. We should just need to update the logic in the instantiation of the DC survey.
> * [ ]  also add a test for the serialization / deserialization of the survey
> * [x]  in the instantiation of the `Data` class, we should allow `uncertainty` to be passed as a keyword and go through the setter
> * [x]  remove the `mesh` from the 1D code
> * [x]  rename `t` to `thicknesses` in the DC1D (@sgkang: would you be willing to do this?)
> * [ ]  when doing a 2D simulation, you are able to define the Pole_ky and Dipole_ky to measure apparent resistivity and apparent conductivity. However, the forward simulation fails when calling the geometric factor for these receivers because it is not defined. This should be fixed.
> * [ ]  remove the factor of 1/2 from the data misfit and regularization (cc @dougoldenburg) as per #763

**Comment by sgkang** [comment]
For this comment from @dccowan : 

- [ ] when doing a 2D simulation, you are able to define the Pole_ky and Dipole_ky to measure apparent resistivity and apparent conductivity. However, the forward simulation fails when calling the geometric factor for these receivers because it is not defined. This should be fixed.

In the current 2D simulation structure, you need to input geometric factor into simulation class. This seems a problem of a utility function I guess. Is that right?

**Comment by thast** [comment]
Can we have a discussion/vote at a next SimPEG meeting about the " remove the factor of 1/2 from the data misfit and regularization "? I did not have the impression it was already decided / reached a consensus... or is it just me?

**Comment by lheagy** [comment]
@thast: For sure, sorry my wording made it sound like a decision, which was not my intent - we should definitely talk through this at the next meeting

**Comment by lheagy** [comment]
I am going to close this in favour of parsing out new issues as the GWB project has come to a conclusion.
