### ISSUE TITLE
Master Travis failed

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#839]
While updating the version (commit https://github.com/simpeg/simpeg/commit/6ca23f751de1bdc679d906c889fdad305fe1b592), which should not have changed anything, Travis failed on master :(

Seems there might be a couple of things happening (see the 3 screenshots below). Any ideas?

![image](https://user-images.githubusercontent.com/13682747/72636962-16553200-3915-11ea-81e3-a4882e1f4887.png)

![image](https://user-images.githubusercontent.com/13682747/72636991-1e14d680-3915-11ea-9206-d0de99790f92.png)

![image](https://user-images.githubusercontent.com/13682747/72637000-2240f400-3915-11ea-8c90-53cfce666386.png)

**Comment by lheagy** [comment]
Thanks @thast, we can do some digging. The test of the Tikhonov regularization should be fine (it should register as a pass, even if it is first order, as we expect that the second-derivative should be first-order convergent - it is basically the derivative of `A*x`)

**Comment by jcapriot** [comment]
The second error is a true division vs flooring division, so nC/2 should probably be nC//2.
