### ISSUE TITLE
Standard deviation and it's place in the code base

### ISSUE THREAD

**Issue by jcapriot** [simpeg/simpeg#846]
I brought this up at a previous meeting and would appreciate input from more people as well. Essentially the issue is that most place in the codebase that refer to things as standard deviation (for example in the Data Class) it is not actually standard deviation. It is more akin to the coefficient of variation.

The Problem
------------
For example in https://github.com/simpeg/simpeg/blob/1548d788e8e19f1a5ec8b6264770bbb5374ae3c0/SimPEG/data.py#L24
the data class has three attributes related to the noise level:
`standard_deviation`, `noise_floor`, and `uncertainty`.

The `standard_deviation` in this class is actually a ratio multiplied by the absolute value of the data, which is then added to `noise_floor`, to produce the `uncertainty`,

`uncertainty` = `standard_deviation` x `np.abs(d_obs)` + `noise_floor`

In a statistical sense, this `uncertainty` would actually be the data's standard deviation.

Thus lies the problem, `standard_deviation` does not actually refer to standard deviation. It actually comes from colloquially referring to a data as having "10%" standard deviation.

Suggestions
------------
The definition of `noise_floor` seems to be self explanatory. I would suggest then renaming `uncertainty` to actually be `standard_deviation` (since that is what it is).

Questions
----------
Therefore, we need a better name for what `standard_deviation` was, possibly `noise_ratio`, `relative_error`, `percent_error`, etc.? I'd like to open this up to discussion and suggestions.

**Comment by leonfoks** [comment]
2 cents.
In geobipy that percentage multiplier is referred to as “relative”,  and noise_floor is “additive”.  The standard deviation is sqrt(relative^2 + additive^2)

**Comment by micmitch** [comment]
percent_error seems like a pretty logical choice to me.

**Comment by jcapriot** [comment]
@leonfoks That's interesting, what was the reasoning behind combining them that way?
@micmitch `percent_error` seems logical, but it also raises a bit of confusion on its own, do we expect the number coming in to actually be a percentage? ie 10, or a decimal .1? This could be documented, but just trying to keep it clear.

**Comment by micmitch** [comment]
The way its implemented in the methods I have used its a percentage in decimal form. Always good to have these things clearly documented.

**Comment by jcapriot** [comment]
My preferences would be either for `relative_error` or `noise_ratio`. They both seem to be a little clearer from their names.

**Comment by domfournier** [comment]
I vote for `percent_error` too, and just document it and/or throw a warning if we detect all values >>1. I think it's more along with the notation that Doug et al. have been using, and sort of implies a multiplication.

**Comment by lheagy** [comment]
Interesting point @domfournier - I could see this working. Remove the distinction at the deep level of the code and perhaps relegate this to a higher-level API? I would be curious to hear other thoughts on this - maybe one for the meeting today

**Comment by thast** [comment]
I like `relative_error`. I can also propose  `relative_noise` to do the parallel with `noise_floor`.

**Comment by jcapriot** [comment]
To me it looks like we've been converging on `relative_error` and `noise_floor` which I both think are perfectly reasonably and descriptive of their respective roles.

Thus I think it would be that

`noise_floor` -> `noise_floor`
`standard_deviation` -> `relative_error`
`uncertainty` -> `standard_deviation`
