### ISSUE TITLE
Creating 2.5D IP survey using "from_dc_to_ip_survey" breaks - Pole Source

### ISSUE THREAD

**Issue by JKutt** [simpeg/simpeg#855]
https://github.com/simpeg/simpeg/blob/8e573083a7dda92edaba6fd3074d28b434f67f00/SimPEG/electromagnetics/static/induced_polarization/survey.py#L27

Ran into an issue while attempting to run 2.5D IP using simulation with pole source:
The line above should be `rxList_ip, src.location`. Same thing is seen using Problem class (master), should be `rxList_ip, src.loc` not `rxList_ip, src_ip.loc`

Should I make a quick pull request?

**Comment by jcapriot** [comment]
I think the best course of action would be to just return a copy of the DC survey, as there isn't anything specific to IP.

**Comment by jcapriot** [comment]
I'll get a patch to simulation to fix this up.

**Comment by JKutt** [comment]
Cool, sounds good Joe!
