### ISSUE TITLE
Accessing Fields for DC 2.5D

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#856]
In DC 2.5D, trying to access any other field than "Phi" raises the current error (btw, those other fields appear in the documentation and the 2.5Dcode, they are just not fully implemented yet):
![image](https://user-images.githubusercontent.com/13682747/79374558-40b28d80-7f0c-11ea-988c-c98975be9a44.png)

Side note:
Accessing the 'Phi' field is working. However, I have a question about its shape. See example below. The second dimension is the number of spatial frequencies but I am unsure what is the first dimension: it is neither the size of the whole mesh nor the size of the active cells....
![image](https://user-images.githubusercontent.com/13682747/79374926-ac94f600-7f0c-11ea-9cf4-012879cccb29.png)

Extra information: here is the scripts I ended up using to compute and visualize the field. The em-apps are using a similar approach. So improving on the Fields object will likely improve the em-apps.
```
# Plot vector field of one quadrupole for mtrue
Mx = meshList20[0].gridCC
rx = DC.Rx.Pole_ky(Mx)
src = DC.Src.Dipole([rx],dcsurvey20[0].srcList[0].loc[0],dcsurvey20[0].srcList[0].loc[1])
dcsurvey = DC.Survey_ky([src])
dcprob = DC.Problem2D_N(meshList20[0],sigmaMap=mapping20[0],Solver=PardisoSolver)
dcprob.pair(dcsurvey)

mtrue = 1./res20[0]*1000
phipotential = dcsurvey.dpred(mtrue[actind_air20[0]])
efield = -meshList20[0].cellGrad * phipotential
efieldx = -meshList20[0].cellGradx * phipotential
efieldy = -meshList20[0].cellGrady * phipotential

jfield = dcprob.MfRhoI * efield

from scipy.interpolate import LinearNDInterpolator, NearestNDInterpolator
import matplotlib

tensormesh = Mesh.TensorMesh(meshList20[0].h)
tensormesh.x0 = meshList20[0].x0
indcore, tensormesh = Utils.ExtractCoreMesh(np.c_[[-3,-1],[3,1]],tensormesh)

InterpolateEField_x = LinearNDInterpolator(meshList20[0].gridEy,efieldx)
ExField_tensor = InterpolateEField_x(tensormesh.gridEy)
InterpolateEField_y = LinearNDInterpolator(meshList20[0].gridEx,efieldy)
EyField_tensor = InterpolateEField_y(tensormesh.gridEx)
EField_tensor = np.r_[ExField_tensor,EyField_tensor]

InterpolateJField_x = NearestNDInterpolator(meshList20[0].gridEy,jfield[meshList20[0].gridEx.shape[0]:])
JxField_tensor = InterpolateField_x(tensormesh.gridEy)
InterpolateJField_y = NearestNDInterpolator(meshList20[0].gridEx,jfield[:meshList20[0].gridEx.shape[0]])
JyField_tensor = InterpolateField_y(tensormesh.gridEx)
JField_tensor = np.r_[JxField_tensor,JyField_tensor]

tensormesh.plotImage(EField_tensor,view='vec',vType='F',pcolorOpts={'norm':matplotlib.colors.LogNorm()})
```

**Comment by jcapriot** [comment]
The issue here is that the 2D dc code's field is only meant to be used for simulation, meaning it contains the computed field for each (15 + 1) wavenumbers.
If you'd like to investigate the other components, it first needs to be converted into a normal field. This operation is provided by:

https://github.com/simpeg/simpeg/blob/2cb11643517881f683cdc33a67f9d28223392609/SimPEG/EM/Static/DC/ProblemDC_2D.py#L51

So, can you try the following?
```
f_2d = prob.fields(m)
f = prob.fields_to_space(f_2d)
f[src, 'e']
```

This needs to be better described in the documentation.

**Comment by thast** [comment]
That seems to be working.

**Comment by thast** [comment]
@sarahgarre maybe try it with your final visualization

**Comment by thast** [comment]
@micmitch : Yes, I went back to those scripts. And they do exactly what I did: put Poles receivers everywhere and compute the E-field by hand.

**Comment by sarahgarre** [comment]
@thast I am sorry, but I am not following completely anymore. Do I have to replace this portion
`phipotential = dcsurvey.dpred(mtrue[actind_air20[i]])
efield = -meshList20[i].cellGrad * phipotential # Total field
efieldx = -meshList20[i].cellGradx * phipotential # X-direction
efieldy = -meshList20[i].cellGrady * phipotential # Y-direction

# ???
jfield = dcprob.MfRhoI * efield`

by what @jcapriot wrote and my jfield is then his f?

**Comment by thast** [comment]
@sarahgarre, yes, that's right:

```
f_2d = prob.fields(mtrue[actind_air20[i]])
f = prob.fields_to_space(f_2d)
jfield = f[src, 'j']
```

**Comment by dccowan** [comment]
I can think of a way to demonstrate this in a tutorial.

**Comment by dccowan** [comment]
@thast @sgkang I believe I found the problem. I match a patch. See PR #868

**Comment by dccowan** [comment]
This bug was fixed in pull request #868

**Comment by jcapriot** [comment]
@dccowan I think the bug here is actually a lack of documentation. So I'd like to leave this open until there is either an example or tutorial on how to access and plot fields for the 2D code.

The bug you found in simulation was a separate thing though, so thanks for catching that!

**Comment by jcapriot** [comment]
This has now been taken care of in `0.14.1`. You can directly access the `phi` and other solutions from the 2.5D fields object (it will take care of the transformation object behind the scenes).
