### ISSUE TITLE
Non major axis aligned orientations for (EM dipole) sources

### ISSUE THREAD

**Issue by TobiasGlaubach** [simpeg/simpeg#871]
Hi,
thanks for all the work you put into making this awesome toolbox!
I haven't found any possibility to supply non major axis aligned orientations for (EM dipole) sources is something like this possible?

I saw, that the orientation is internally actually mapped to a three element vector. 

If no possibly exists, is there a way of implementing this? If it's not too much work and you point me in the right direction, I am happy to make a PR. 

Alternatively I could implement a workaround to rotate the whole domain and simulate everything in the rotated coordinate system.

Kind regards,
Tobi

**Comment by thast** [comment]
Hi @TobiasGlaubach,

As far as I know, the easiest way right now for you is what you proposed last: rotate the domain and work with a local coordinates system so that your dipoles are aligned wit the cell edges. @fourndo or @dccowan might have experiences with rotating meshes.

I think there might be some tools in for interpolating non-aligned dipoles, but interpolation come with its own drawbacks and limitations. @sgkang and @micmitch would know better than me on the subject.

Thanks a lot for proposing to contribute to SimPEG :) Whatever way you choose to move forward, having an example of EM dipoles that are not aligned NS or EW would be huge! So when you have an example working that you are keen to share, let us know, that would be awesome! We can also help if you encounter obstacles with your first SimPEG PR.

**Comment by lheagy** [comment]
Hi @TobiasGlaubach, Thanks for your issue! 

There is an implementation of an arbitrary dipole source as long as you are using a 3D mesh. You just need to input the `orientation` as a vector. I have attached an example here (both as a notebook and as a pdf). We do need to update this in the documentation, and if you would like to contribute an example to the docs we always welcome them! Please let us know if you have any questions about the code

- [arbitrary_dipole - Jupyter Notebook.pdf](https://github.com/simpeg/simpeg/files/4611193/arbitrary_dipole.-.Jupyter.Notebook.pdf)
- [arbitrary_dipole.ipynb.zip](https://github.com/simpeg/simpeg/files/4611198/arbitrary_dipole.ipynb.zip)

**Comment by TobiasGlaubach** [comment]
Hi everyone,
Thanks for the reply!
@lheagy : Thanks for the example! Is there a way of defining arbitrarily oriented 3D Receivers as well?

**Comment by lheagy** [comment]
We don't yet have arbitrary receivers plugged in. This would be a great contribution that we can sketch out! Right now, the simplest way to get arbitrary receivers would be to define the orientation and then sum the results from the x, y, z receivers with the appropriate weights.

**Comment by prisae** [comment]
@TobiasGlaubach, a simple routine how you could get rotated receivers is the following (to what @lheagy refers):
```
# Get azimuth and dip in radians.
azm = np.deg2rad(azm_deg)
dip = np.deg2rad(dip_deg)

# Get factors in the different directions.
xfact = np.cos(azm)*np.cos(dip)
yfact = np.sin(azm)*np.cos(dip)
zfact = np.sin(dip)

# Assemble the response.
resp = xfact*x_resp
resp += yfact*y_resp
resp += zfact*z_resp
```
where `x_resp`, `y_resp`, and `z_resp` are three SimPEG receivers in x, y, and z direction. The `azm` and `dip` in this case are defined like this
https://empymod.readthedocs.io/en/stable/_images/sphx_glr_coordinate_system_001.png
For other definitions you have to adjust the rotation matrix accordingly (the `cos`'s and `sin`'s).

**Comment by TobiasGlaubach** [comment]
@prisae: Thank you! I think this will work as a starter for me.

@lheagy: Thanks for the answer! As I said I am happy to contribute to this. I looked into the code today and saw this implementation:

https://github.com/simpeg/simpeg/blob/37ddbd4d8e2be83570eb810d3e1185779685286a/SimPEG/EM/FDEM/RxFDEM.py#L49-L53


Which leads to:
https://github.com/simpeg/simpeg/blob/37ddbd4d8e2be83570eb810d3e1185779685286a/SimPEG/Survey.py#L64

Which then leads to the discretize library. 

I think we could extend the code above to do something like this:

```python
    def projGLoc(self, f, orientation=None):
        """Grid Location projection (e.g. Ex Fy ...)"""
        o = self.projComp if orientation is None else orientation 
        return f._GLoc(self.projField) + o


    def eval(self, src, mesh, f):
(...)
        Px = self.getP(mesh, self.projGLoc(f, 'x'))
        Py = self.getP(mesh, self.projGLoc(f, 'y'))
        Pz = self.getP(mesh, self.projGLoc(f, 'z'))
(...)

        ret_vec = np.r_[Px*f_part, Py*f_part, Pz*f_part]
        
        # todo: insert projection on desired output orientation here
        ret_vec_proj = ... 

        return ret_vec_proj 
```

as well as of course allowing for `self.projComp = orientation` to be a non major axis aligned orientation, and only executing the code above if it is not major axis aligned. What do you think?

**Comment by TobiasGlaubach** [comment]
> Hi @TobiasGlaubach, Thanks for your issue!
> 
> There is an implementation of an arbitrary dipole source as long as you are using a 3D mesh. You just need to input the `orientation` as a vector. I have attached an example here (both as a notebook and as a pdf). We do need to update this in the documentation, and if you would like to contribute an example to the docs we always welcome them! Please let us know if you have any questions about the code
> 
> * [arbitrary_dipole - Jupyter Notebook.pdf](https://github.com/simpeg/simpeg/files/4611193/arbitrary_dipole.-.Jupyter.Notebook.pdf)
> * [arbitrary_dipole.ipynb.zip](https://github.com/simpeg/simpeg/files/4611198/arbitrary_dipole.ipynb.zip)

Actually. What is the definition for the `orientation` argument, if it is not a string? The dipole major axis alignment in 3D space?  This is not documented, or did I miss something?

**Comment by jcapriot** [comment]
Now we support arbitrary receiver orientations as well!
