### ISSUE TITLE
DC - instantiating sources and receivers

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#877]
rather than `locationA` or `locationsM`, I would suggest that we use `a_location` and `m_locations` for instantiating sources and receivers. These also should be allowed to be None in the case that the user wants to input `locations` as a 2D array (which will happen when we deserialize a survey)

**Comment by jcapriot** [comment]
I agree with this! I had some of my own thoughts in my head the other day about this. 
I kinda want the class to be able to be instantiated the class would be:

`rx.Dipole(locations=(locs_m, locs_n))` or `rx.Dipole(m_locations=locs_m, n_locations=locs_n)`

**Comment by lheagy** [comment]
:+1: I really like that!

**Comment by lheagy** [comment]
I started this on the `transform-dc-updates` branch
