### ISSUE TITLE
instantiating the DC survey 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#878]
rather than computing the A, B, M, N locations by calling `getABMN_locations` and then calling the properties `a_locations`, I would suggest that we instead have `a_locations` etc as `@property`'s. E.g. 

```python 
@property
def a_locations(self):
    if getattr(self, "_a_locations"):
        # get the a locations 
    return self._a_locations 
```

A few reasons for this suggestion:
- right now, these values would be serialized with the class, which is duplicate information as to what is stored on the sources and receivers
- it is possible that a user could set `a_location` on the survey, and this will not be updated in the sources - which would be confusing 

(related to #877)

**Comment by jcapriot** [comment]
Again reading my mind, these should definitely be `@property`
