### ISSUE TITLE
2D DC Fields object

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#887]
For ease of plotting currents and such, it would be nice if we had the ability to directly access the integrated currents, electric fields, potentials, etc. Would 
- `phi_integrated`
- `j_integrated`
- `e_integrated`
work for folks? 

cc @jcapriot, @sgkang

**Comment by lheagy** [comment]
:wave: @jcapriot: would you be willing to take a pass at the implementation? No worries if not, just let me know what work

**Comment by jcapriot** [comment]
Yup! I’ll get

**Comment by jcapriot** [comment]
just had a thought that might work better... what if we changed the default field to `phi_ky` and then just did the integration if someone asks for `phi`, `j` or `e`?

**Comment by lheagy** [comment]
:+1: I really like that @jcapriot! 

It would also be nice if we could add charge density to the mix too (we have this in the 3D case)
