### ISSUE TITLE
different cell weights for "Small" term in the regularization 

### ISSUE THREAD

**Issue by jedman** [simpeg/simpeg#898]
As currently implemented, the regularization classes `Simple`, `Tikhonov` and `Sparse` apply the user-specified `cell_weights` to every term in the objective function. In some cases (such as when the reference model is well-constrained at only a few mesh cells) it might only be appropriate to apply the cell weights to the "small" term in the objective function, i.e. the deviation from the reference model.

 I can think of a few ways to address this, but the simplest might be adding a flag to the `__init__` (something like `cell_weights_on_small_term_only=True`} and then only passing the `cell_weights` to the `Small` term.  If this makes sense, I'm happy to put together a small PR to implement

**Comment by lheagy** [comment]
Thanks for this @jedman! This would be good to have. I like the approach you suggest - in the `Simple` or `Tikhonov` and `Sparse` pop the `cell_weights` and then only pass to the smallness term if desired. For consistency with the way `mref` is set (which is currently `mrefInSmooth` - ugh - should go to `mref_in_smooth` 😄 ), I would suggest we go with `cell_weights_in_smooth` for the key-word. 

@jcapriot, @domfournier: do you think that naming works?

**Comment by jcapriot** [comment]
I think this is a case for not using the pre-made ``Simple``, ``Small``, and ``Tikhonov`` regularizations, and instead use the components of them individually for this purpose.
I,e. ``Simple`` is a summation of ``SimpleSmall`` + ``SimpleSmoothDeriv`` (one derivative for each dimension).

**Comment by domfournier** [comment]
This raises a slightly bigger issue regarding `cell_weights` being used for the sensitivity weighting. Right now it is almost impossible to apply a second layer of user-defined custom weights (like what @jedman is trying to do) on top of automated sensitivity re-weighting that the Directives are targeting. I am wondering if we would not be better off adding an extra layer to each component of the reg (default all ones), which the user could then micro-manage and keep constant throughout.

**Comment by domfournier** [comment]
Agree with @jcapriot above. You are just better of applying the weights on the component of the reg directly rather than on the top level. i.e.

`for objfun, weights in zip(reg.objfcts, my_special_weights):
    objfun.cell_weights = weights`

**Comment by jedman** [comment]
Thanks everybody! If this use case is not that common, then I think the solutions suggested by @jcapriot and @domfournier are sufficient-- a new keyword argument would just be convenient. On the other hand, @domfournier makes a good point about the user-defined weights not really being compatible with the sensitivity weighting directive, as currently written. In most cases, I would think one would want to apply custom cell weights on top of the sensitivity weighting-- the current behavior (overwriting any user-defined weights) actually seems more obscure to me, but maybe I'm missing something...
