### ISSUE TITLE
Problem installing SimPEG new version 14.1

### ISSUE THREAD

**Issue by jc-barreto** [simpeg/simpeg#901]
Hello,

I have been using SimPEG 13.1 and in order to try to run just inversion and to get used to  the new version,
I have created a new environment and tried to install SimPEG 14.1 in this environment, but It gives an error.
Since I already have SimPEG 13.1 working, I'm wondering if in the new version is necessary to install something else before...
this is the error I'm getting:
![image](https://user-images.githubusercontent.com/42352209/86419473-24ccb580-bccb-11ea-9ea2-bd64d15dd41f.png)
![image](https://user-images.githubusercontent.com/42352209/86419495-3b730c80-bccb-11ea-9dc6-fb8b61dd7d46.png)
![image](https://user-images.githubusercontent.com/42352209/86419573-75441300-bccb-11ea-8ce5-a10f82ddbadf.png)

**Comment by lheagy** [comment]
Hi @jc-barreto! Sorry you are running into issues... 

It looks like you are installing via `pip`, is that correct? If so, the installation via `conda` should be much more straightfoward (esp. on Windows). In that case, what I would recommend is that you uninstall your current versions of SimPEG and discretize

```
> pip uninstall discretize
```
and 
``` 
> pip uninstall simpeg
```

and then re-install via conda (this will install discretize and SimPEG). 
```
> conda install -c conda-forge simpeg
```

Let us know how it goes!

**Comment by jc-barreto** [comment]
Hi! your advice worked! now I have SimPEG 14 installed in an environment. Thank you =)
