### ISSUE TITLE
Upgrading sympeg 

### ISSUE THREAD

**Issue by ezraermy** [simpeg/simpeg#926]

**Comment by ezraermy** [comment]
Sorry guys I already solved the issue. However, my upgraded simpeg is 0.5.1 instead of 0.7.1. I don't understand why.

**Comment by craigmillernz** [comment]
I'll close this as insufficient description is given to assess the issue.  Feel free to resubmit with more details.

**Comment by ezraermy** [comment]
I am sorry for the insufficient description. I already fixed the problem.
