### ISSUE TITLE
Reading all modeling parameters at once using 'MagneticsDriver_Inv'

### ISSUE THREAD

**Issue by ezraermy** [simpeg/simpeg#930]

**Comment by ezraermy** [comment]
Hi all,

Once I provided all model parameters to read in using 'MagneticsDriver_Inv', assuming that it needs the same data format with the gravity one provided in example 'plot_laguna_del_maule_inversion.py', as shown the initial code bellow,
![Q1](https://user-images.githubusercontent.com/35451409/95303086-71f09280-088b-11eb-8ecf-9adafce32fc2.png)

Running the initial code keep getting failed saying: 
![Q2](https://user-images.githubusercontent.com/35451409/95303590-0e1a9980-088c-11eb-92cf-d3351f923bbf.png)

Can anyone kindly tell me what my mistake is?

**Comment by domfournier** [comment]
Hi Ezra,

It sounds like a change in the input file. I suspect that there has been a syntax change between what you are using and what it is expecting.

Can you show your input?

**Comment by ezraermy** [comment]
@domfournier thank you for your reply. 

My inputs are: magnetics_inp.inp, magnetics_mesh.txt, magnetics_topo.txt and magnetics_data.txt
magnetics_inp.inp looks like:
![Q3](https://user-images.githubusercontent.com/35451409/95420613-6b722180-0944-11eb-9762-a839d2444649.png)
.

**Comment by ezraermy** [comment]
I also tried by changing the file's extension to:   magnetics_inp.inp, magnetics_mesh.mesh, magnetics_topo.topo and magnetics_data.obs. I still got the same issue.

**Comment by ezraermy** [comment]
@domfournier , I think I fixed the problem. Adding Magnetization model in the input file (line 6). Now the driver works fine. 

Thanks for your tips once again.
