### ISSUE TITLE
Unnecessary warning trigger with linearSimulation

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#934]
Simply running the tutorial `plot_inv_1_inversion_lsq.py`, I obtain a warning that does not seem to be necessary.

The line `sim = simulation.LinearSimulation(mesh, G=G, model_map=model_map)`

triggers the warning:
 
![image](https://user-images.githubusercontent.com/13682747/97060345-eb54da00-1547-11eb-8716-5f345e940870.png)

where G seems to be by all mean a valid property... it seems to be more an issue on the order on which piece of code are hit.

**Comment by jcapriot** [comment]
I believe this is no longer triggered with #1111
