### ISSUE TITLE
NSEM relying on FDEM base class 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#947]
In order to have the NSEM simulation be able to rely directly on the `FDEM` forward + sensitivity calculations, there are a few things we need to update, particularly with the handling of two polarizations for a 3D simulation. 

## Assumptions that we need to work through: 
In the calculation of the fields, we store both fields: 
https://github.com/simpeg/simpeg/blob/bf765d73d1c104805e30bcd062426e36a1d48d51/SimPEG/electromagnetics/natural_source/simulation.py#L477-L478

and the receivers then need to know about both polarizations in order to calculate the impedances. 

And currently the solution type is a list, which the fields object doesn't know how to handle at the moment 
https://github.com/simpeg/simpeg/blob/bf765d73d1c104805e30bcd062426e36a1d48d51/SimPEG/electromagnetics/natural_source/simulation.py#L344

## A sketch of a solution: 
As we talked about at the [MT meeting on Nov 6](https://youtu.be/r6qhdBH_Cow), it would be nice if the NSEM implementation relies entirely on the FDEM `simulation` classes and the `sources` and `receivers` handle the rest. I would also like to propose that the NSEM implementation also relies on the FDEM fields object. Here is a sketch of what I have in mind... 

- The `source` is a composite source consisting of two sources, one for each polarization. 
- When we call `self.survey.get_sources_by_frequency` in the forward simulation / sensitivity calculations, this then simply collapses that composite source to a regular list, as if we just had 2 FDEM sources. This way, the fields object only cares that `e` is electric field, and it is then indexed by the individual polarizations (and the `_solutionType` is identical to the FDEM simulation)
   - this would require a light adaptation of the fields object to return an array 2-wide if it were indexed by the composite source, but this should really only happen if the user is working with the fields object, it likely shouldn't happen internally inside simpeg
- the calculation of impedances is still fine as each source knows its receiver list and the two individual source terms that are associated with each polarization. 

This should isolate the changes to:
- NSEM sources / receivers 
- `FDEM.Survey.get_sources_by_frequency`
- a light-touch on the FDEM fields for if it is handed a composite source 
- (and I _think_ that is it?) 

and we should not need to touch the `fields`, `Jvec`, `Jtvec` implementations in the FDEM codebase 

Related to #946, #452

**Comment by lheagy** [comment]
@JKutt and I chatted about this yesterday, I don't think we need to create a fancy source, but rather update how the `survey` keeps track of which indices in the fields object are associated with that source. This is currently handled by the `survey._sourceOrder` property that is a dictionary with the sources as keys and the values being the location of the source in the source list. If we instead consider this as a `survey._sourceIndex`, then simply returning two indices for the two polarizations _should_ (I think!) be enough for us to enable an NSEM source to be used by the FDEM simulation 

https://github.com/simpeg/simpeg/blob/bf765d73d1c104805e30bcd062426e36a1d48d51/SimPEG/survey.py#L264-L265

**Comment by jcapriot** [comment]
I think we could get rid of the entire _sourceOrder option, and just not worry about it. essentially this would result in accessing the fields object as an array of (nSrc, nE, 2). For each source this is then an (nE, 2) array. 

I don't think it would then require much to be modified, only would need to update the `MeSigmaDeriv` function to know what to do if it sees something that looks like (..., 2) for both `u` and `v`. Right now it knows what to do if `v` is a matrix and `u` is a single vector, using broadcasting. But it could simply be adding a check that if "u" and "v" are both 2D and of shape(...,2) (and it's asking for the adjoint) then also do ... whatever is necessary.

**Comment by jcapriot** [comment]
I think something like this would work for `MeSigmaDeriv` it in the cases needed for MT... without breaking it for other cases, but I haven't tested it
```
if v is not None:
    if not isinstance(u, Zero):
        if u.ndim > 1
            if u.shape[1] == 1:
                u = u[:, 0]
            # if u is a matrix, promote v if it is a vector
            elif v.ndim == 1:
                v = v[:, None]
        if v.ndim > 1:
            # promote u iff v is a matrix and u is a vector
            if u.ndim == 1:
                u = u[:, None]
    if adjoint:
        out = self._MeSigmaDeriv.T * (u * v)
        if u.ndim > 1 and u.shape == v.shape:
            out = np.sum(out, axis=1)
        return out
    return u * (self._MeSigmaDeriv * v)
```

**Comment by JKutt** [comment]
@jcapriot & @lheagy I can give this a test. I'm working at this currently

**Comment by jcapriot** [comment]
If you need help with it let me know, been thinking through this in my head a bit, just trying to look at where the MT simulation class and the FDEM ElectricField simulation class overlap

**Comment by JKutt** [comment]
feel free to poke around! I got a bit held up on some of the source_utils stuff on the nsem side. but looking at things now.

**Comment by jcapriot** [comment]
This was finished up a bit ago in #946 .
