### ISSUE TITLE
Edit on GitHub Extension failing for windows

### ISSUE THREAD

**Issue by dccowan** [simpeg/simpeg#950]
When trying to make html for the SimPEG docs, I ran into an error. It has to do with the fact that Anaconda was installed on the C: drive, but the SimPEG repository is saved to the D drive. In researching this, I learned that defining a relative path between the two directories with *relpath* is not trivial on windows machines. Below is the error when building the html:

![image](https://user-images.githubusercontent.com/12970009/99171473-36cd5480-26be-11eb-9be3-acd93dba90ca.png)

I tracked down the log file to get more information about the error. The screenshot is below. Perhaps something more robust needs to be used for line 170 in the conf.py file? It was under the heading for the *edit_on_github* extension. Perhaps there is an issue with the extension.

![image](https://user-images.githubusercontent.com/12970009/99171500-6f6d2e00-26be-11eb-83ce-11eb4e76b334.png)

**Comment by dccowan** [comment]
Error occurs in the *conf.py* file within the function *linkcode_resolve*. It happen when executing *relpath*.

![image](https://user-images.githubusercontent.com/12970009/99219262-1de1a380-2791-11eb-8389-faeaafe47b66.png)

**Comment by jcapriot** [comment]
I would suggest turning off the "sphinx.ext.linkcode" extension in your conf.py.

**Comment by jcapriot** [comment]
No longer applicable, the edit on github is handled by the `pydata_theme`
