### ISSUE TITLE
ImportError: cannot import name 'Mesh' from 'SimPEG'

### ISSUE THREAD

**Issue by JuanjoLedo** [simpeg/simpeg#970]
Hello, I'm trying to run the notebooks related to the TLE nonlinear inversion paper and I get this error "ImportError: cannot import name 'Mesh' from 'SimPEG'" 
I have SimPEG installed, please, could you give some hint how to solve it?

thank you very much

best regards

**Comment by thast** [comment]
Hi @JuanjoLedo,

Several things:

- make sure you use the latest version of SimPEG (currently 0.14.3). You can check it like this:
```
import SimPEG
print(SimPEG.__version__)
```

- The preferred way of importing the Mesh functionality is now to import the package `discretize` separately:
```
import discretize as Mesh
```

**Comment by thast** [comment]
@sgkang might have something to add to this.

**Comment by AyoubBouayaben** [comment]
Hello @thast , @sgkang 
I get the same error when i want to execute ' from SimPEG import Utils, Solver  ' , can you please tell me from which library can i import them from ?
