### ISSUE TITLE
A question using Example of Seismic Inversion

### ISSUE THREAD

**Issue by chrisweird7** [simpeg/simpeg#971]
I'm a researcher on Seismology and recently I found this promising SimPEG and instantly attracted to it.
I installed the environment and had a try at once, I noticed the Seismic Example in the documentation which is about the velocity tomography problem.
I ran the example and got the exactly same results, very cool.
Then, I tried to test more.
I modified the sources and receivers in the example to simulate another scenario like this:
`np.random.seed(0)`
`src_x = (np.random.rand(50)-0.5)*200`
`src_y = (np.random.rand(50)-0.5)*200`
`src_lct = np.c_[src_x, src_y]`

`rcv_x = np.r_[range(-100,100,20), [100]*9, range(100,-100,-20), [-100]*10]`
`rcv_y = np.r_[[-100]*10, range(-100,100,20), [100]*10, range(100,-80,-20)]`
`rcv_lct = np.c_[rcv_x, rcv_y]`
![Figure_1](https://user-images.githubusercontent.com/41539950/108583477-a8c7d080-7374-11eb-9191-55e38a76b3b3.png)
From forward simulation, I got the right arrival times data of all the receivers from all the sources successfully.
Then I tried the inversion process.
I set the initial model a uniform model with 2500m/s (3000m/s in the example), and left the other settings without change.
Then the iteration began.
The total iteration number soon reached 100 which is the maxIter and unfortunately I got a fairly wrong result like this:
![Figure_2](https://user-images.githubusercontent.com/41539950/108583678-453ea280-7376-11eb-84e5-74845082f098.png)
I tried to modify the parameters in regularization, optimization and inversion processes but I just couldn't get the point.
I think my modification is simple and there should be a right way to get a good recovery of the true model.
I hope someone can help me with this issue by setting the appropriate parameters and I'll very appreciate with that.

**Comment by ckohnke** [comment]
I gave this a shot. Without seeing more code, my guess is that you aren't making observed data for your modified survey, or making dobs in a way that is valid to the inversion, but not consistent with the survey you are using. To accomplish this, you should probably move the simulation definition to much earlier in the program and use the `make_synthetic_data` function in the simulation to generate the observed data. 

The code blocks I came up, while a bit crude, go:
1. Define the sources, receivers, survey 
2. Define the mesh and starting/reference/true models
3. Define the simulation
4. Compute the synthetic "observed" data using the simulation
5. Inversion

The only blocks that should need editing from the original example are 1 and 4, and the other pieces are just moved around slightly. You can delete the parts about loading and reading observed data, but you will need the true velocity model (read in from file in the example) for use in 4.

I can't easily upload a jupyter notebook right now, but here are the inversion results I got by just changing the source/receivers out and computing the observed data using the true model and keeping the inversion directives the same.

![download-2](https://user-images.githubusercontent.com/5299556/108617453-bd878100-73d3-11eb-9e23-ac8e6e67f7fc.png)

**Comment by chrisweird7** [comment]
> I gave this a shot. Without seeing more code, my guess is that you aren't making observed data for your modified survey, or making dobs in a way that is valid to the inversion, but not consistent with the survey you are using. To accomplish this, you should probably move the simulation definition to much earlier in the program and use the `make_synthetic_data` function in the simulation to generate the observed data.
> 
> The code blocks I came up, while a bit crude, go:
> 
> 1. Define the sources, receivers, survey
> 2. Define the mesh and starting/reference/true models
> 3. Define the simulation
> 4. Compute the synthetic "observed" data using the simulation
> 5. Inversion
> 
> The only blocks that should need editing from the original example are 1 and 4, and the other pieces are just moved around slightly. You can delete the parts about loading and reading observed data, but you will need the true velocity model (read in from file in the example) for use in 4.
> 
> I can't easily upload a jupyter notebook right now, but here are the inversion results I got by just changing the source/receivers out and computing the observed data using the true model and keeping the inversion directives the same.
> 
> ![download-2](https://user-images.githubusercontent.com/5299556/108617453-bd878100-73d3-11eb-9e23-ac8e6e67f7fc.png)

Thank you very much. Your result is amazing and encouraging. I'll try to figure it out under your guide.

**Comment by chrisweird7** [comment]
@ckohnke Thank you very much. Your result is amazing and encouraging. I'll try to figure it out under your guide.

**Comment by chrisweird7** [comment]
@ckohnke I've figure it out. I don't know what to say. How careless I am. I did all things right except to copy the code line `np.random.seed(0)`. It means my sources were changing all the time. Haha, my problem becomes a joke. Anyway, now I have the right result and yes, SimPEG is good.

**Comment by thast** [comment]
Glad this worked @chrisweird7 ! And many thanks @ckohnke for championing this issue.

As your issue seems to have been solved @chrisweird7, are you OK with closing it?

**Comment by chrisweird7** [comment]
@thast Sure.
