### ISSUE TITLE
An inconsistence issue of data and model for gravity examples in the tutorial

### ISSUE THREAD

**Issue by xiaolongw1223** [simpeg/simpeg#973]
Hi, guys,

I just noticed the model and data maps are inconsistent. For example, the negative anomaly body locates at left, but the negative gravity response is in right. It is probably caused by the different perspective. 

Is better to make them consistent? 

<img width="1082" alt="Screen Shot 2021-02-24 at 4 36 03 PM" src="https://user-images.githubusercontent.com/56940558/109079225-3fbdc100-76c4-11eb-8abb-6d59ff01a038.png">
<img width="1093" alt="Screen Shot 2021-02-24 at 5 11 46 PM" src="https://user-images.githubusercontent.com/56940558/109079233-42201b00-76c4-11eb-8cd6-f512d3422904.png">

I did a quick test where I flipped the order of observed and predicted data respectively. The results looks good (negative response locates at left position). Please see figure below.

![Figure_3](https://user-images.githubusercontent.com/56940558/109079608-cd99ac00-76c4-11eb-8a75-17d30255bf06.png)

 Thus, I believe if we flipped the data in "gravity_data.obs", the problem will be solved.

What's your guys opinion? @fourndo @jcapriot @lheagy

**Comment by xiaolongw1223** [comment]
The two data figures look a bit different because I changed the number of contour lines from 30 to 100.

**Comment by jcapriot** [comment]
SimPEG uses a right hand sided coordinate system with z to be positive upwards (x- positive east, y positive north). This cause most gravity anomalies to "look" backwards, but we intentionally made that decision to keep the entire package self-consistent.

**Comment by xiaolongw1223** [comment]
> SimPEG uses a right hand sided coordinate system with z to be positive upwards (x- positive east, y positive north). This cause most gravity anomalies to "look" backwards, but we intentionally made that decision to keep the entire package self-consistent.

I see! Thanks for clarify this for me. I will close this right later.
