### ISSUE TITLE
The problem with an all purpose DC survey class

### ISSUE THREAD

**Issue by dccowan** [simpeg/simpeg#975]
I am spearheading a clean up and refactor of the DC/IP utilities as part of PR #974 . I have noticed a fundamental problem with the survey class that we should make a decision on.

**Problem:**
When working within SimPEG and when reading and writing UBC-GIF formatted data files, we want the ability to **not** include the vertical position of the electrodes and assume a surface survey. The way we have things, there is no way to differentiate a 2D survey with elevation locations defined, and a 3D survey without elevations defined. The locations of the electrodes in both cases are (n, 2).  This is creating issues when trying to write general utilities because there is no way to determine if the second column is elevation or y location.

**Possible Solutions:**
- We create a property for the survey class that requires the user to state if the geometry is 2D or 3D, or to state whether the survey is 'surface data' without elevation. This property is a required argument when creating an instance of the class. (i like this)
- Within the SimPEG framework, 3D surveys MUST have the elevation defined for the electrodes. If 3D data in surface format are loaded, the elevation is given some dummy value.
- We add keyword arguments to a bunch of the utilities (i hate this)

**Comment by jcapriot** [comment]
I believe a 3D survey without elevations defined should not be a supported format for the receivers and sources in a survey. It is something that should be handled by the IO routines to get it into the proper SimPEG format.

The drape_topo functions already take care of adding in the elevations to the electrodes.

I don’t see any problem with keyword arguments, and would prefer those.
The focus should not be on designing classes around the utilities but on the functionality of the simulation and inversion engines.

**Comment by jcapriot** [comment]
Maybe something along the lines of a warning when a user is reading in a surface UBCGIF formatted file that says “you must attach elevations using the drape_topo function”

**Comment by dccowan** [comment]
Ya I like this. SimPEG is its own framework and you can take care of these problems in 1 step in the IO.

**Comment by domfournier** [comment]
I agree, we just need to specify what type of simulation we are expecting on the read, and return nan on the elevations if not included. The issue is more about ambiguity in the legacy UBC file format.

**Comment by jcapriot** [comment]
This is now how the IO is implemented for DC, although there are still legacy references to `survey_type` in the DC module that need to be removed.
