### ISSUE TITLE
Fields indexing very slow. 

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#99]
Using the source indexing in the fields object is very slow, compared to slice the full object. Here are some examples of fieldsMT object that is dict of 4 fields, which are ~22000 data long. 

%time fields[:,:]
CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 37 µs

%time fields[fields.survey.srcList[0],:]
CPU times: user 1.26 ms, sys: 9 µs, total: 1.27 ms
Wall time: 957 µs

%time fields[:,'e_px']
CPU times: user 22 µs, sys: 0 ns, total: 22 µs
Wall time: 25 µs

%time fields[fields.survey.srcList[0],'e_px']
CPU times: user 898 µs, sys: 6 µs, total: 904 µs
Wall time: 522 µs

**Comment by rowanc1** [comment]
Line 73 - 84 in Problem.py is the thing that is probably taking the longest time.
```python
    def _srcIndex(self, srcTestList):
        if type(srcTestList) is slice:
            ind = srcTestList
        else:
            if type(srcTestList) is not list:
                srcTestList = [srcTestList]
            for srcTest in srcTestList:
                if srcTest not in self.survey.srcList:
                    raise KeyError('Invalid Source, not in survey list.')

            ind = np.in1d(self.survey.srcList, srcTestList)
        return ind
```

These lines in particular:
```python
for srcTest in srcTestList:
    if srcTest not in self.survey.srcList:
        ...
```

We are doing a for loop over each source requested, and then doing an `in` call, which is essentially another for loop.

We should be initializing a map of sources to index that can easily be looked up. Perhaps a function `survey.sourceIndex([src0, src1])` might be a good way to handle this, then the map is global to the survey.

```python
survey._sourceOrder = dict()
survey._sourceOrder = [setdefault(src.uid, ii) for ii, src in enumerate(self.survey.srcList)]
```

Then `sourceIndex`:

```python
def sourceIndex(self, mySrcList):
    inds = map(lambda src: getattr(self._sourceOrder, src.uid, None), mySrcList)
    if None in inds:
        raise Exception()
    return inds
```

I will try to get to this soon!

**Comment by rowanc1** [comment]
```
from SimPEG import *
mesh = Mesh.TensorMesh([np.ones(n)*5 for n in [10,11,12]],[0,0,-30])
x = np.linspace(5,10,3)
XYZ = Utils.ndgrid(x,x,np.r_[0.])
srcLoc = np.r_[0,0,0.]
srcList = []
for ii in range(100):
    rxList0 = Survey.BaseRx(XYZ, 'exi')
    srcList += [Survey.BaseSrc([rxList0], loc=srcLoc)]
survey = Survey.BaseSurvey(srcList=srcList)
D = Survey.Data(survey)
F = Problem.Fields(mesh, survey, knownFields={'phi':'CC','e':'E','b':'F'}, dtype={"phi":float,"e":complex,"b":complex})

F[:,'phi'] = np.random.rand(mesh.nC, survey.nSrc)

import time
tic = time.time()
F[:,'phi']
print time.time() - tic



import time
tic = time.time()
F[srcList[0],'phi']
print time.time() - tic
```

Before:
1.59740447998e-05
0.000329971313477

After:
7.86781311035e-06
5.69820404053e-05

**Comment by lheagy** [comment]
Nice :)

**Comment by grosenkj** [comment]
I agree, that is sweet. Thanks.
