### ISSUE TITLE
latest discretize (v0.7.0) with SimPEG.EM.Static.2DCellCentered generates shape mismatch error

### ISSUE THREAD

**Issue by ngodber** [simpeg/simpeg#992]
![image](https://user-images.githubusercontent.com/11834846/116775459-6e7e5c00-aaa6-11eb-9609-c5f23f14ecc6.png)
Previously get_BC_projections_simple was undefined for TreeMesh as the DiffOperators mixin was not inherited. With discretize 0.7.0 is is, so code path executes further than previously (where a missing operator was encountered previously). Now utilising CellCentered2D with treemesh generates attached error.

**Comment by ngodber** [comment]
Note, above code works substituting Simulation2DNodal.

**Comment by jcapriot** [comment]
I’m in the process of updating the boundary condition implementation for DC, hold your horses!

**Comment by ngodber** [comment]
No worries, I'm just near militant about doing whatever I can to contribute back and often noone bothers to ever log stuff!
