### ISSUE TITLE
DC Resistivity Forward Simulation in 2.5D

### ISSUE THREAD

**Issue by 07638** [simpeg/simpeg#995]
Hello seniors, I am a beginner and I want to ask you a question.(DC Resistivity Forward Simulation in 2.5D)In this experiment, why do I use the code provided in the tutorial to get the forward images and examples that are different
!
![1)YCM}UHello seniors, I am a beginner and I want to ask you a question.(DC Resistivity Forward Simulation in 2.5D)In this experiment, why do I use the code provided in the tutorial to get the forward images and examples that are different
!
0}47R@A(CFYJMK](https://user-images.githubusercontent.com/81788016/117337608-27420200-aed0-11eb-96b8-3be93e77ef13.png)

**Comment by sgkang** [comment]
Hi @07638, 

Thanks for your question. 
It is not clear to know which tutorial that you are using, and what different results that you are getting. 
Please provide a bit more information such that we can help you.

**Comment by 07638** [comment]
This is what the tutorial produced
![image](https://user-images.githubusercontent.com/81788016/117930301-69d06800-b330-11eb-800d-1439de1e58f6.png)

**Comment by 07638** [comment]
Come a kind-hearted person to help me! I'm about to die with this question. please!!!

**Comment by sgkang** [comment]
Hi @sgkang, 

Which version of SimPEG are you using?
Make sure you use the latest version of the SimPEG to have compatible results shown in the documentation. 

`conda install SimPEG --channel conda-forge`

latest version is 0.14.3, you can check the version of SimPEG:
`import SimPEG`
`SimPEG.__version__`

**Comment by 07638** [comment]
Thank you for your answer! I tried the method you just provided, but my version is up to date .This is the result of running the program

![Uploading image.png…]()

**Comment by 07638** [comment]
Thank you for your answer! I tried the method you just provided, but my version is up to date .This is the result of running the program
![image](https://user-images.githubusercontent.com/81788016/118030852-65d83080-b398-11eb-8c41-18ce601b30d1.png)

**Comment by thast** [comment]
This is an issue with `mkl` and `pardiso` (not SimPEG). So all we can do for now until they fix it is to hide the warning.

solution 1: set a environment variable KMP_WARNINGS=0 (there are lots of resources online to learn how to set environment variable on mac or window). 

solution 2: at the start of your script, add the following lines: 
```
import os
os.environ["KMP_WARNINGS"] = "0"
```

**Comment by jcapriot** [comment]
If any other issues pop up, let us know.
